import { Recipe } from './types';

/**
 * Weeknight mains — the gaps the planner could not fill.
 *
 * Every dish here exists because a profile combination came back empty rather
 * than because the menu wanted another recipe. A 15-minute cook had almost
 * nothing to pick from; a vegan on 2,400 kcal could not reach the target
 * without eating four bowls of soup; nothing in the pool carried omega-3 or
 * vitamin D at all. A constraint solver returns nothing when the pool is thin,
 * and "no plan found" is the worst answer an app can give.
 *
 * One honest note on sourcing: the bundled nutrient table has no entry for
 * tinned tuna, so the tuna pasta bake is costed and analysed against
 * `white_fish`, the nearest thing in the table. Protein and calories land
 * within a few per cent; the price of a tin does not. Treat that one figure as
 * indicative until the table gains a tuna row.
 */
export const RECIPES_D: Recipe[] = [
  {
    id: 'chicken_stir_fry',
    name: 'Chicken and Vegetable Stir Fry with Rice',
    cuisine: 'Chinese',
    country: 'CN',
    blurb: 'Forty grams of protein a serving, on the table in twenty-five minutes, and nothing in it you have to have done before.',
    servings: 2,
    activeMin: 20,
    totalMin: 25,
    difficulty: 'easy',
    restaurantGBP: 9.5,
    tags: ['halal', 'dairy_free', 'nut_free'],
    items: [
      { ref: 'chicken_breast', grams: 300, note: 'sliced thin across the grain' },
      { ref: 'jasmine_rice', grams: 150, note: 'rinsed' },
      { ref: 'water', grams: 360, note: '330 g for the rice, 30 g for the sauce' },
      { ref: 'cornflour', grams: 8, note: 'tossed through the raw chicken' },
      { ref: 'soy_sauce', grams: 30, note: '10 g on the chicken, 20 g in the sauce' },
      { ref: 'oyster_sauce', grams: 20 },
      { ref: 'vinegar_rice', grams: 10 },
      { ref: 'sugar', grams: 4 },
      { ref: 'vegetable_oil', grams: 20 },
      { ref: 'sesame_oil', grams: 5, note: 'off the heat, at the very end' },
      { ref: 'garlic', grams: 12, note: '3 cloves, finely chopped' },
      { ref: 'ginger', grams: 10, note: 'grated on the coarse side of the grater' },
      { ref: 'red_pepper', grams: 160, note: 'sliced into strips' },
      { ref: 'carrot', grams: 100, note: 'matchsticks — thin, or it will not cook in time' },
      { ref: 'beansprouts', grams: 100 },
      { ref: 'spring_onion', grams: 40, note: 'cut into 3 cm lengths' },
      { ref: 'black_pepper', grams: 1, note: 'into the marinade with the cornflour' },
      { ref: 'sesame_seeds', grams: 4, optional: true },
    ],
    method: [
      { n: 1, text: 'Rinse the rice in a sieve, tip it into a small pan with 330 g of the water, bring to a boil, then drop to the lowest heat with the lid on for 10 minutes. Take it off the heat and leave it, still covered, until you serve.', minutes: 15, tip: 'Do not lift the lid to check. The rice is cooking in trapped steam, and every peek lets it out — that is the whole mechanism.' },
      { n: 2, text: 'While the rice cooks, slice the chicken. Cut across the grain — the lines running through the meat should be at right angles to your knife — into strips about 5 mm thick.' },
      { n: 3, text: 'Toss the chicken strips with the cornflour and 10 g of the soy sauce until every piece is slick and coated.', tip: 'This is the one trick that separates home stir fry from takeaway stir fry. The cornflour holds moisture in the meat and gives the sauce something to grip. Two minutes of work, and it is the difference.' },
      { n: 4, text: 'Mix the sauce in a mug now rather than later: the remaining 20 g soy sauce, the oyster sauce, rice vinegar, sugar and 30 g water, stirred until the sugar has gone. Once the pan is hot the whole dish runs on a six-minute clock and there is no time to measure anything.' },
      { n: 5, text: 'Prepare all the vegetables and put them in one bowl, with the garlic, ginger and spring onion in a separate small one. Everything must be within arm reach of the hob before you start.' },
      { n: 6, text: 'Put your largest frying pan or wok on the highest heat for 2 minutes, dry.', minutes: 2, tip: 'Flick a drop of water in. If it skitters across the surface and vanishes, it is ready. If it sits and bubbles slowly, wait longer — this is the most common reason a home stir fry turns grey.' },
      { n: 7, text: 'Add the vegetable oil, then the chicken in a single layer. Leave it completely alone for 90 seconds, then toss and cook another 90 seconds until no pink is showing and the thickest piece reads 75 C. Tip it onto a plate.', minutes: 3, tip: 'If the chicken will not fit in one layer, do it in two batches. Crowded meat releases water, the pan temperature collapses, and you end up boiling it.' },
      { n: 8, text: 'Straight back into the empty pan: carrot and red pepper, still on high, tossing constantly for 2 minutes.', minutes: 2 },
      { n: 9, text: 'Add the garlic and ginger and toss for 30 seconds.', tip: 'Thirty seconds, no more. Garlic on a wok-hot pan goes from fragrant to acrid in about the time it takes to read this.' },
      { n: 10, text: 'Return the chicken and any juice from the plate, pour in the sauce, and toss for 60 seconds until it thickens and clings to everything instead of pooling.', minutes: 1 },
      { n: 11, text: 'Throw in the beansprouts and spring onion, toss for 30 seconds — they should still squeak — then take the pan off the heat and stir through the sesame oil.' },
      { n: 12, text: 'Fluff the rice with a fork and serve the stir fry on top, with the sesame seeds if using.' },
    ],
    failures: [
      { symptom: 'Chicken grey, and a pool of liquid in the pan', cause: 'Pan not hot enough, or too much in it at once. Preheat properly and cook the meat in two batches — it costs 90 seconds and fixes the dish.' },
      { symptom: 'Sauce thin and sliding off into a puddle', cause: 'The cornflour on the chicken is the thickener, so it only works if the sauce boils for a full minute with the chicken back in. Give it another 30 seconds on high.' },
      { symptom: 'Vegetables limp and grey', cause: 'Cooked too long, or a lid went on. Nothing here needs more than 2 minutes, and a stir fry is always uncovered.' },
      { symptom: 'Rice claggy and wet', cause: 'Not rinsed, or the lid came off during the 10 minutes. Rinse until the water is no longer milky, and leave it alone.' },
      { symptom: 'Too salty', cause: 'The soy and oyster sauce are the salt. Do not add any more, and if it has already happened, serve it over more rice.' },
    ],
    variants: [
      {
        id: 'stir_fry_tofu',
        label: 'Vegan, with tofu',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'chicken_breast', to: 'tofu_firm', grams: 400 },
          { from: 'oyster_sauce', to: 'mushroom', grams: 150 },
        ],
        methodDeltas: [
          { step: 3, change: 'Press the tofu first: wrap the block in kitchen paper, put a plate and a tin on top, leave 10 minutes. Then cube it into 2 cm pieces and toss with the cornflour and soy. Wet tofu will not take a coating and will not brown.' },
          { step: 7, change: 'Tofu needs 6-8 minutes, not 3, and it needs to be left still. Lay the cubes out, leave them 3 minutes untouched until the underside is genuinely golden, turn once, another 3 minutes. Tossing it early is how tofu ends up as scrambled rubble.' },
          { step: 8, change: 'Fry the mushrooms hard on their own for 5 minutes before the carrot and pepper go in. They replace the oyster sauce, and they only replace it once they have driven off their water and started to brown — the savoury depth arrives at that point, not before.' },
          { step: 10, change: 'Without oyster sauce the sauce is thinner and sharper. Add an extra teaspoon of sugar with it.' },
        ],
        note: 'Oyster sauce is neither vegan nor vegetarian, which is easy to miss on a bottle that mostly says "sauce".',
      },
      {
        id: 'stir_fry_lean',
        label: 'Leaner, higher protein',
        tags: ['halal', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'chicken_breast', to: 'chicken_breast', grams: 420 },
          { from: 'vegetable_oil', to: 'vegetable_oil', grams: 10 },
          { from: 'jasmine_rice', to: 'jasmine_rice', grams: 110 },
        ],
        methodDeltas: [
          { step: 1, change: 'Less rice needs less water — 250 g, not 330. The ratio matters more than the quantity.' },
          { step: 7, change: 'This much chicken will not fit in one layer in any domestic pan. Two batches, no exceptions, and add half the oil to each.' },
          { step: 8, change: 'With half the oil the pan runs drier and the vegetables catch. Keep them moving continuously and add a tablespoon of water if anything starts to stick.' },
        ],
      },
    ],
  },

  {
    id: 'tuna_pasta_bake',
    name: 'Tuna Pasta Bake',
    cuisine: 'British',
    country: 'GB',
    blurb: 'Four tins and a bag of pasta. The cheapest hot dinner in the book, and the one most likely to already be in your cupboard.',
    servings: 2,
    activeMin: 20,
    totalMin: 45,
    difficulty: 'easy',
    restaurantGBP: 8.5,
    tags: ['halal', 'nut_free'],
    items: [
      { ref: 'spaghetti', grams: 180, note: 'snapped in half — or use macaroni if you have it' },
      { ref: 'tuna_tinned', grams: 300, note: 'two 145 g tins of tuna in spring water, drained hard' },
      { ref: 'sweetcorn', grams: 150, note: 'drained' },
      { ref: 'peas_frozen', grams: 100, note: 'straight from the freezer, no defrosting' },
      { ref: 'onion', grams: 100, note: 'finely diced' },
      { ref: 'butter', grams: 30 },
      { ref: 'plain_flour', grams: 25 },
      { ref: 'milk_semi', grams: 450, note: 'cold, straight from the fridge' },
      { ref: 'cheddar', grams: 90, note: 'grated — 60 g into the sauce, 30 g on top' },
      { ref: 'dijon_mustard', grams: 8 },
      { ref: 'breadcrumbs', grams: 30, note: 'for the topping' },
      { ref: 'salt', grams: 5, absorption: 0.46, note: '3 g in the pasta water, 2 g in the sauce' },
      { ref: 'black_pepper', grams: 1 },
      { ref: 'nutmeg', grams: 0.3, optional: true },
      { ref: 'parsley_fresh', grams: 8, optional: true },
    ],
    method: [
      { n: 1, text: 'Heat the oven to 200C (180C fan, gas 6) and put a large pan of water on with 3 g of the salt.' },
      { n: 2, text: 'Cook the pasta for 2 minutes LESS than the packet says — genuinely under, because it cooks again for 25 minutes in the oven and pasta that was already done goes to porridge in a bake. Drain it and run cold water over it for 10 seconds.', minutes: 8 },
      { n: 3, text: 'Melt the butter in a medium saucepan over medium heat and soften the diced onion in it for 5 minutes until translucent.', minutes: 5 },
      { n: 4, text: 'Stir in the flour and keep stirring for a full minute. It will look like wet sand and pull away from the pan.', minutes: 1, tip: 'A full minute. Under-cooked flour tastes of raw flour, and no amount of cheese hides it. It should smell faintly biscuity.' },
      { n: 5, text: 'Take the pan off the heat and add the cold milk in five or six additions, whisking each one completely smooth before the next.', tip: 'The first two additions are the only ones that can go wrong. Add a splash, whisk to a thick smooth paste, then a splash more. Pour the whole lot in at once and you get lumps you cannot whisk out.' },
      { n: 6, text: 'Back on medium heat. Whisk steadily for 3-4 minutes until it thickens enough to coat the back of a spoon.', minutes: 4, tip: 'It stays watery, stays watery, then thickens all at once in about 15 seconds. Do not walk away in the last minute.' },
      { n: 7, text: 'Off the heat, stir in 60 g of the cheddar, the mustard, the remaining 2 g salt, the pepper and the nutmeg if using.', tip: 'Off the heat. Cheese stirred into a boiling sauce splits — you get grainy strings and a slick of orange fat on top, and it cannot be brought back.' },
      { n: 8, text: 'Drain the tuna properly, pressing the lid down hard against the tin, then flake it into large pieces with a fork.' },
      { n: 9, text: 'Fold the pasta, tuna, sweetcorn and frozen peas into the sauce with a spatula, lifting from the bottom.', tip: 'Fold, do not stir. Stirring shreds tuna into paste and you lose the point of using it — you want visible flakes, not a beige sauce.' },
      { n: 10, text: 'Tip it all into an oven dish of about 20 x 25 cm and level the top.' },
      { n: 11, text: 'Mix the remaining 30 g cheddar with the breadcrumbs and scatter over the surface.' },
      { n: 12, text: 'Bake for 22-25 minutes until the top is properly browned and the sauce is bubbling at the edges of the dish, not just in the middle.', minutes: 25 },
      { n: 13, text: 'Rest it for 5 minutes before serving, with the parsley if using.', minutes: 5 },
    ],
    failures: [
      { symptom: 'Lumpy sauce', cause: 'Milk added too fast at the start. Next time, add the first two splashes tiny and whisk each to a paste. This time, a stick blender or a sieve will rescue it.' },
      { symptom: 'Sludgy, pasta indistinguishable from sauce', cause: 'Pasta boiled to full doneness before it went in. Two minutes under is not a suggestion.' },
      { symptom: 'Greasy and grainy, orange fat on top', cause: 'Cheese added while the sauce was still on the heat. Always off the heat.' },
      { symptom: 'Dry and stiff by the time it comes out', cause: 'Not enough milk for the amount of pasta. The mixture should look slightly too wet going into the dish — the pasta drinks the rest in the oven.' },
      { symptom: 'Top pale and soft after 25 minutes', cause: 'Dish too deep, or oven not preheated. Grill it for 2 minutes, watching it the whole time.' },
    ],
    variants: [
      {
        id: 'bake_veggie',
        label: 'Vegetarian, with chickpeas',
        tags: ['vegetarian', 'halal', 'kosher', 'nut_free'],
        swaps: [{ from: 'tuna_tinned', to: 'chickpeas_tinned', grams: 400 }],
        methodDeltas: [
          { step: 8, change: 'Drain and rinse the chickpeas rather than just draining — the tin liquid tastes metallic in a mild cheese sauce. Then crush about a third of them against the side of the bowl with a fork.' },
          { step: 9, change: 'Chickpeas hold their shape where tuna melts into the sauce, so the bake can taste like two separate things. The crushed third is what binds it together — do not skip that.' },
          { step: 12, change: 'No fish to dry out, so give it 5 minutes longer for a better crust.' },
        ],
      },
      {
        id: 'bake_lean',
        label: 'Leaner, higher protein',
        tags: ['halal', 'nut_free'],
        swaps: [
          { from: 'tuna_tinned', to: 'tuna_tinned', grams: 420 },
          { from: 'cheddar', to: 'cheddar', grams: 55 },
          { from: 'butter', to: 'olive_oil', grams: 18 },
          { from: 'spaghetti', to: 'spaghetti', grams: 150 },
        ],
        methodDeltas: [
          { step: 4, change: 'An oil-based roux never goes sandy the way a butter one does — it stays a loose paste. Judge it by smell instead, and give it 90 seconds rather than 60.' },
          { step: 7, change: 'With a third less cheese the sauce needs more help: double the mustard and add an extra pinch of salt.' },
          { step: 11, change: 'Only a scraping of cheese for the top now, so the breadcrumbs will not brown on their own. Toss them with a teaspoon of oil first.' },
        ],
      },
    ],
  },

  {
    id: 'beef_chilli',
    name: 'Chilli con Carne with Rice',
    cuisine: 'Tex-Mex',
    country: 'US',
    blurb: 'Twenty-five minutes of work and forty of waiting. Doubles without complaint, and it is better the next day.',
    servings: 2,
    activeMin: 25,
    totalMin: 65,
    difficulty: 'easy-medium',
    restaurantGBP: 10.5,
    tags: ['halal', 'gluten_free', 'nut_free'],
    items: [
      { ref: 'beef_mince_5', grams: 400 },
      { ref: 'kidney_beans_tinned', grams: 400, note: 'drained and rinsed' },
      { ref: 'tomato_tinned', grams: 400 },
      { ref: 'tomato_puree', grams: 30 },
      { ref: 'onion', grams: 180, note: 'diced' },
      { ref: 'garlic', grams: 16, note: '4 cloves' },
      { ref: 'red_pepper', grams: 160, note: 'diced to roughly the size of the beans' },
      { ref: 'cumin_ground', grams: 4, note: '2 tsp' },
      { ref: 'paprika_smoked', grams: 4, note: '2 tsp — smoked, not sweet' },
      { ref: 'chilli_powder', grams: 2, note: '1 tsp; start here, you can always add more' },
      { ref: 'oregano_dried', grams: 2 },
      { ref: 'cinnamon_ground', grams: 1, note: 'sounds wrong, do it anyway' },
      { ref: 'stock_cube_beef', grams: 6 },
      { ref: 'water', grams: 580, note: '250 g for the chilli, 330 g for the rice' },
      { ref: 'vegetable_oil', grams: 20 },
      { ref: 'long_grain_rice', grams: 150, note: 'rinsed' },
      { ref: 'salt', grams: 5 },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'lime', grams: 20, optional: true },
      { ref: 'coriander_fresh', grams: 10, optional: true },
      { ref: 'greek_yogurt', grams: 60, optional: true, note: 'to serve, instead of soured cream' },
    ],
    method: [
      { n: 1, text: 'Heat half the oil in a large heavy pan on high. Add half the mince, press it flat, and leave it completely alone for 4 minutes until the underside is dark brown. Break it up, cook 2 more minutes, then tip it into a bowl. Repeat with the second half.', minutes: 12, tip: 'This browning is where most of the flavour of the finished dish comes from, and it only happens in a hot uncrowded pan. All 400 g at once will steam in its own liquid and go grey — you cannot get that flavour back later.' },
      { n: 2, text: 'Drop the heat to medium. In the same pan, with all the fat and brown bits still in it, soften the onion and red pepper for 8 minutes with a pinch of the salt.', minutes: 8 },
      { n: 3, text: 'Add the garlic and cook for 1 minute.', minutes: 1 },
      { n: 4, text: 'Add the cumin, smoked paprika, chilli powder, oregano, cinnamon and the tomato puree. Stir constantly for 90 seconds.', minutes: 2, tip: 'Watch the puree: it starts bright red and turns brick-dark. That colour change is the raw tinny taste cooking off, and it is the difference between chilli and mince in tomato sauce.' },
      { n: 5, text: 'Return the mince with any juice, add the tinned tomatoes, the crumbled stock cube, 250 g of the water, the rest of the salt and the pepper. Scrape the bottom of the pan hard as it comes up to heat.' },
      { n: 6, text: 'Bring to a boil, then reduce to a bare simmer with the lid slightly ajar. Cook for 30 minutes.', minutes: 30, tip: 'A bare simmer means one lazy bubble every second or two. A rolling boil will reduce it to paste in 20 minutes and toughen the meat at the same time.' },
      { n: 7, text: 'Add the drained kidney beans and simmer uncovered for another 10 minutes.', minutes: 10, tip: 'Beans go in late on purpose. Tinned beans are already cooked, and 40 minutes of simmering turns them into a floury mush that thickens the whole pot in the wrong way.' },
      { n: 8, text: 'While that happens, put the rice on: rinsed rice and 330 g water, bring to a boil, lowest heat with the lid on for 10 minutes, then off the heat still covered until you serve.', minutes: 15 },
      { n: 9, text: 'Taste and fix it in this order: salt first, then acid (a squeeze of lime), then heat (more chilli powder), then sweetness only if it tastes sharp.', tip: 'Almost every "it tastes like it is missing something" chilli is missing salt or acid, not chilli. Add heat last, once you can actually taste the rest.' },
      { n: 10, text: 'Take it off the heat and let it sit for 10 minutes. It thickens noticeably and the spices stop tasting separate.', minutes: 10 },
      { n: 11, text: 'Fluff the rice and serve, with the yogurt and coriander if using.' },
    ],
    failures: [
      { symptom: 'Grey mince, watery pot', cause: 'Mince browned all at once in a crowded pan. Two batches, high heat, and leave it still for the first 4 minutes.' },
      { symptom: 'Thin and soupy after the full time', cause: 'Lid on too tight, so nothing evaporated. Finish it uncovered on a higher heat for 10 minutes.' },
      { symptom: 'Beans collapsed into mush', cause: 'Added at the start. They only need the last 10 minutes.' },
      { symptom: 'Catches and tastes scorched', cause: 'Heat too high once it thickened. Drop it, and scrape along the base with a flat-ended spoon rather than stirring in circles.' },
      { symptom: 'Harsh and sharp', cause: 'Tomato puree never got fried, or the tomatoes were acidic. A teaspoon of sugar helps, but frying the puree properly next time is the actual fix.' },
    ],
    variants: [
      {
        id: 'chilli_vegan',
        label: 'Vegan, with soya',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'nut_free'],
        swaps: [
          { from: 'beef_mince_5', to: 'soya_chunks', grams: 90 },
          { from: 'stock_cube_beef', to: 'stock_cube_veg', grams: 6 },
          { from: 'greek_yogurt', to: null },
        ],
        methodDeltas: [
          { step: 1, change: 'Cover the dry soya chunks with boiling water for 10 minutes, then drain and squeeze them out hard in your hands, as you would frozen spinach. Only then fry them, in one batch, for 5 minutes until the edges catch and darken — they will not brown at all if they are still holding water.' },
          { step: 5, change: 'Soya chunks keep drinking liquid for the whole simmer. Use 400 g of water here rather than 250 g and check it again halfway.' },
          { step: 7, change: 'Give it 15 minutes at this stage rather than 10. Undercooked soya stays springy and squeaks against the teeth, which is the single thing that puts people off it.' },
          { step: 9, change: 'There is no meat fat carrying the spices now, so it will taste flatter at this point than the beef version does. Add an extra teaspoon of smoked paprika and a good glug of oil, and taste again.' },
        ],
      },
      {
        id: 'chilli_leaner',
        label: 'Leaner, more beans',
        tags: ['halal', 'gluten_free', 'nut_free'],
        swaps: [
          { from: 'beef_mince_5', to: 'beef_mince_5', grams: 250 },
          { from: 'black_beans_tinned', to: 'black_beans_tinned', grams: 400 },
        ],
        methodDeltas: [
          { step: 1, change: '250 g browns comfortably in one batch. Still leave it flat and untouched for the first 4 minutes.' },
          { step: 2, change: 'Less mince leaves less fat in the pan. Add the second half of the oil here or the onions will stick.' },
          { step: 7, change: 'Both tins of beans go in at this point. There is now more bean than meat, so mash a ladleful against the side of the pan — the starch thickens the sauce that the fat used to.' },
        ],
      },
      {
        id: 'chilli_tortillas',
        label: 'With tortillas instead of rice',
        tags: ['halal', 'gluten_free', 'nut_free'],
        swaps: [{ from: 'long_grain_rice', to: 'tortilla_corn', grams: 180 }],
        methodDeltas: [
          { step: 6, change: 'Simmer with the lid fully off for the last 10 minutes. Anything loose enough to serve over rice will soak straight through a tortilla and fall apart in your hands.' },
          { step: 8, change: 'No rice to cook. Instead, warm the tortillas 20 seconds a side in a dry pan just before serving, and stack them under a clean tea towel so they steam each other soft.' },
        ],
      },
    ],
  },

  {
    id: 'roast_chicken_traybake',
    name: 'Chicken, Potato and Pepper Traybake',
    cuisine: 'British',
    country: 'GB',
    blurb: 'Twelve minutes of chopping, then the oven does the next hour while you do something else.',
    servings: 2,
    activeMin: 12,
    totalMin: 65,
    difficulty: 'easy',
    restaurantGBP: 11.5,
    tags: ['halal', 'gluten_free', 'dairy_free', 'nut_free'],
    items: [
      { ref: 'chicken_thigh', grams: 500, note: 'boneless, left whole — do not cut them up' },
      { ref: 'potato', grams: 500, note: 'skin on, cut into 3 cm chunks' },
      { ref: 'carrot', grams: 200, note: 'thick batons, about the size of your thumb' },
      { ref: 'red_onion', grams: 150, note: 'cut into wedges through the root so they hold together' },
      { ref: 'red_pepper', grams: 160, note: 'thick strips' },
      { ref: 'garlic', grams: 20, note: '5 cloves, skins left on, whole' },
      { ref: 'olive_oil', grams: 35 },
      { ref: 'paprika_smoked', grams: 4 },
      { ref: 'oregano_dried', grams: 3 },
      { ref: 'lemon', grams: 70, note: 'half in wedges on the tray, half squeezed over at the end' },
      { ref: 'salt', grams: 6 },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'parsley_fresh', grams: 8, optional: true },
    ],
    method: [
      { n: 1, text: 'Heat the oven to 220C (200C fan, gas 7) with a shelf in the upper third. Give it a full 15 minutes to come up.', minutes: 15, tip: 'The light going off does not mean the oven is ready — that is the element cycling, not the walls being hot. Roast potatoes put into a not-quite-hot oven never recover.' },
      { n: 2, text: 'Cut the potatoes into 3 cm chunks and the carrots into thick batons. Dry the potatoes on a tea towel if they have been washed.' },
      { n: 3, text: 'Toss the potatoes and carrots with 20 g of the oil, half the salt and the pepper, directly on the largest baking tray you own.', tip: 'Largest tray, single layer, visible gaps between the pieces. Crowded vegetables trap their own steam and boil instead of roasting, and no amount of extra time will crisp them afterwards.' },
      { n: 4, text: 'Roast for 20 minutes.', minutes: 20 },
      { n: 5, text: 'Meanwhile, toss the chicken thighs in a bowl with the remaining 15 g oil, the smoked paprika, oregano and the rest of the salt. Get it under and over each piece.' },
      { n: 6, text: 'Pull the tray out. Turn the vegetables with a fish slice — they should have taken colour underneath — and push them out to the edges.' },
      { n: 7, text: 'Lay the chicken thighs flat in the cleared middle, smoothest side up. Tuck the red onion wedges, pepper strips, whole garlic cloves and lemon wedges into the gaps.' },
      { n: 8, text: 'Roast for another 25-30 minutes.', minutes: 30, tip: 'Chicken thigh is done at 75C in the thickest part. Without a thermometer, cut into the fattest piece: the juices should run clear with no pink, and the meat should look matt rather than glossy.' },
      { n: 9, text: 'If the chicken is done but the potatoes are still pale, lift the chicken onto a plate to rest and give the tray 8 more minutes on its own.', minutes: 8 },
      { n: 10, text: 'Rest the chicken on the tray for 5 minutes.', minutes: 5, tip: 'The juices that run out during resting land on the vegetables, which is exactly where you want them. Do not rest it on a separate plate and then pour that away.' },
      { n: 11, text: 'Squeeze the roasted lemon wedges over everything, squash the garlic cloves out of their skins and mash them into the juices, and scatter the parsley if using.' },
    ],
    failures: [
      { symptom: 'Potatoes pale, soft and steamed', cause: 'Tray overcrowded, or the oven was not fully preheated. Two trays is better than one full one.' },
      { symptom: 'Chicken dry and stringy', cause: 'It went in at the start with the vegetables. Thighs need 30 minutes at this temperature, not 50 — that is why the potatoes get a head start.' },
      { symptom: 'A pool of liquid in the tray', cause: 'Wet vegetables, or a tray with high sides that stops steam escaping. Dry the potatoes, and use a flat baking sheet rather than a roasting tin.' },
      { symptom: 'Garlic burnt black and bitter', cause: 'Cloves peeled. The skin is a jacket — leave it on and the inside steams to a sweet paste.' },
      { symptom: 'Chicken cooked but nothing browned', cause: 'Tray too low in the oven. Upper third, where the heat is most direct.' },
    ],
    variants: [
      {
        id: 'traybake_vegan',
        label: 'Vegan, chickpea and tofu',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'chicken_thigh', to: 'chickpeas_tinned', grams: 400 },
          { from: 'tofu_firm', to: 'tofu_firm', grams: 280 },
        ],
        methodDeltas: [
          { step: 5, change: 'Press the tofu under a plate and a tin for 10 minutes, then cut it into 3 cm cubes. Drain and rinse the chickpeas and dry them thoroughly on a tea towel — wet chickpeas steam and stay soft instead of blistering. Toss both with the oil and spices.' },
          { step: 7, change: 'Chickpeas and tofu need 20 minutes, not 30, so put them in 10 minutes later than the chicken would have gone in — give the vegetables 30 minutes on their own first.' },
          { step: 8, change: 'There is no doneness test here, only a colour one. You want the chickpeas wrinkled and blistered so they rattle when you shake the tray, and the tofu browned on the up-facing side.' },
          { step: 10, change: 'Nothing to rest and no juices to catch. Serve straight from the oven while the chickpeas are still crisp — they soften within 10 minutes.' },
        ],
      },
      {
        id: 'traybake_breast',
        label: 'Leaner, with chicken breast',
        tags: ['halal', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'chicken_thigh', to: 'chicken_breast', grams: 450 },
          { from: 'olive_oil', to: 'olive_oil', grams: 22 },
        ],
        methodDeltas: [
          { step: 4, change: 'Give the vegetables 30 minutes on their own rather than 20. Breast goes in much later than thigh.' },
          { step: 8, change: 'Breast needs 18-20 minutes and is ruined at 25. Start checking at 16 — cut into the thickest part and look for the last trace of translucency to have just gone.' },
          { step: 10, change: 'Rest it for the full 5 minutes and then some. Breast has almost no fat to keep it moist, so the resting step matters more here than it does with thigh.' },
        ],
      },
      {
        id: 'traybake_sweet_potato',
        label: 'With sweet potato',
        tags: ['halal', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [{ from: 'potato', to: 'sweet_potato', grams: 500 }],
        methodDeltas: [
          { step: 4, change: 'Sweet potato cooks in about half the time of a maincrop potato and burns at the thin edges. Roast for 12 minutes here, not 20.' },
          { step: 9, change: 'Never give sweet potato the extra 8 minutes — it will be black. If the chicken needs longer, take the sweet potato off the tray instead.' },
        ],
      },
    ],
  },

  {
    id: 'veg_curry_coconut',
    name: 'Sweet Potato, Chickpea and Coconut Curry',
    cuisine: 'Indian',
    country: 'IN',
    blurb: 'A vegan plate that actually lands over a thousand calories, without being four bowls of anything.',
    servings: 2,
    activeMin: 20,
    totalMin: 45,
    difficulty: 'easy-medium',
    restaurantGBP: 9.5,
    tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
    items: [
      { ref: 'chickpeas_tinned', grams: 400, note: 'drained and rinsed' },
      { ref: 'coconut_milk', grams: 400, note: 'full fat; the light version will not carry this dish' },
      { ref: 'sweet_potato', grams: 350, note: '2.5 cm cubes — bigger than feels right' },
      { ref: 'spinach_fresh', grams: 100, note: 'stirred in off the heat' },
      { ref: 'onion', grams: 150, note: 'finely sliced' },
      { ref: 'garlic', grams: 16, note: '4 cloves' },
      { ref: 'ginger', grams: 15, note: 'grated' },
      { ref: 'green_chilli', grams: 10, note: 'deseeded if you want it mild' },
      { ref: 'cumin_ground', grams: 4, note: '2 tsp' },
      { ref: 'coriander_ground', grams: 4, note: '2 tsp' },
      { ref: 'turmeric', grams: 3 },
      { ref: 'garam_masala', grams: 3, note: 'half in the pan, half stirred in at the end' },
      { ref: 'kashmiri_chilli', grams: 2, note: 'for colour more than heat' },
      { ref: 'tomato_puree', grams: 30 },
      { ref: 'vegetable_oil', grams: 25 },
      { ref: 'basmati_rice', grams: 160, note: 'rinsed until the water runs almost clear' },
      { ref: 'water', grams: 480, note: '150 g into the curry, 330 g for the rice' },
      { ref: 'stock_cube_veg', grams: 5 },
      { ref: 'lime', grams: 20, note: 'juice, off the heat' },
      { ref: 'salt', grams: 6 },
      { ref: 'coriander_fresh', grams: 12, optional: true },
    ],
    method: [
      { n: 1, text: 'Rinse the basmati in a sieve until the water running off is only faintly milky, then leave it to drain.' },
      { n: 2, text: 'Peel the sweet potato and cut it into 2.5 cm cubes. Chop the onion, garlic, ginger and chilli.' },
      { n: 3, text: 'Fry the onion in the oil over medium heat for 8 minutes, until soft and just starting to colour at the edges.', minutes: 8, tip: 'Eight minutes, properly timed. Underdone onion leaves a raw sharp note that sits on top of the finished curry, and nothing added later covers it.' },
      { n: 4, text: 'Add the garlic, ginger and green chilli and cook for 1 minute.', minutes: 1 },
      { n: 5, text: 'Add the cumin, ground coriander, turmeric, kashmiri chilli and HALF the garam masala. Stir constantly for 45 seconds.', minutes: 1, tip: 'You are waiting for the moment the pan smells fragrant rather than dusty. Ground spices in hot oil burn inside a minute, and burnt turmeric is bitter in a way you cannot season around.' },
      { n: 6, text: 'Stir in the tomato puree and cook for 1 more minute until it darkens.', minutes: 1 },
      { n: 7, text: 'Add the sweet potato, the coconut milk, the crumbled stock cube, 150 g water and the salt. Bring it up to a gentle simmer.' },
      { n: 8, text: 'Simmer uncovered for 18-20 minutes, until a knife slides into a cube of sweet potato with no resistance at all.', minutes: 20, tip: 'Gentle is not optional. Coconut milk boiled hard splits into oil and grainy solids, and once it has split it will not come back together.' },
      { n: 9, text: 'While that simmers, cook the rice: rinsed rice and 330 g water, bring to a boil, then the lowest heat with the lid on for 10 minutes, then off the heat still covered.', minutes: 15, tip: 'Lid on, and do not lift it. Basmati cooks by absorbing a measured amount of steam, and letting it out is what produces the crunchy grains at the top.' },
      { n: 10, text: 'Add the drained chickpeas and simmer for 5 more minutes.', minutes: 5 },
      { n: 11, text: 'Take the pan off the heat. Stir in the spinach a handful at a time — it wilts in the residual heat in about a minute — then the remaining garam masala and the lime juice.', tip: 'The second half of the garam masala goes in off the heat. It is an aromatic blend, not a base spice, and everything that makes it smell good boils away if you add it all at the start.' },
      { n: 12, text: 'Taste. It usually wants more salt and more lime than you expect. Serve over the rice with the coriander if using.' },
    ],
    failures: [
      { symptom: 'Oily slick on top and a grainy sauce', cause: 'Coconut milk boiled rather than simmered. Keep it at a lazy bubble from the moment it goes in.' },
      { symptom: 'Thin and watery', cause: 'Too much water, or a lid left on so nothing reduced. This simmers uncovered — that is how it thickens.' },
      { symptom: 'Sweet potato disintegrated into the sauce', cause: 'Cut too small or simmered too long. 2.5 cm cubes and a knife test at 18 minutes.' },
      { symptom: 'Bitter, dusty aftertaste', cause: 'Spices burnt at step 5. There is no rescue; next time have the sweet potato and coconut milk standing by so you can kill the heat fast.' },
      { symptom: 'Rich but flat', cause: 'Not enough acid. Coconut fat mutes everything, and the lime at the end is doing structural work, not garnish work.' },
    ],
    variants: [
      {
        id: 'curry_tofu',
        label: 'Higher protein, with tofu',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'tofu_firm', to: 'tofu_firm', grams: 280 },
          { from: 'sweet_potato', to: 'sweet_potato', grams: 250 },
        ],
        methodDeltas: [
          { step: 2, change: 'Press the tofu under a plate and a tin for 10 minutes while you chop, then cut it into 2.5 cm cubes.' },
          { step: 3, change: 'Fry the tofu FIRST, in the oil, on medium-high for 6-8 minutes until two sides are properly golden, then lift it out onto a plate. Tofu added raw to a simmering sauce disintegrates into cloudy shreds within 10 minutes.' },
          { step: 10, change: 'Return the tofu with the chickpeas and fold rather than stir for the last 5 minutes, so the browned faces survive.' },
        ],
        note: 'Roughly doubles the protein. Still no B12 unless something else on the day is fortified.',
      },
      {
        id: 'curry_chicken',
        label: 'With chicken',
        tags: ['halal', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [{ from: 'chickpeas_tinned', to: 'chicken_thigh', grams: 350 }],
        methodDeltas: [
          { step: 7, change: 'Cut the thighs into 3 cm pieces and add them here, with the sweet potato — they need the full simmer, not the last 5 minutes. It must read 75 C at the thickest point, not merely look opaque.' },
          { step: 8, change: 'Same 20 minutes, but now you are checking two things: the sweet potato soft, and the chicken opaque all the way through with no pink at the centre of the thickest piece.' },
          { step: 10, change: 'Nothing to add at this stage any more. Go straight from step 8 to the spinach and lime.' },
        ],
      },
    ],
  },

  {
    id: 'lentil_bolognese',
    name: 'Lentil Bolognese',
    cuisine: 'Italian',
    country: 'IT',
    blurb: 'Thirty-six grams of protein a serving from a pan of lentils, and it tastes like the thing it is named after rather than an apology for it.',
    servings: 2,
    activeMin: 25,
    totalMin: 50,
    difficulty: 'easy-medium',
    restaurantGBP: 9.5,
    tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
    items: [
      { ref: 'red_lentils', grams: 170, note: 'rinsed until the water runs clear' },
      { ref: 'mushroom', grams: 200, note: 'chopped as finely as you can be bothered to' },
      { ref: 'spaghetti', grams: 200 },
      { ref: 'tomato_tinned', grams: 400 },
      { ref: 'tomato_puree', grams: 40 },
      { ref: 'onion', grams: 150, note: 'diced to 5 mm' },
      { ref: 'carrot', grams: 120, note: 'diced to 5 mm' },
      { ref: 'garlic', grams: 16, note: '4 cloves' },
      { ref: 'olive_oil', grams: 25 },
      { ref: 'stock_cube_veg', grams: 8 },
      { ref: 'water', grams: 450 },
      { ref: 'soy_sauce', grams: 15, note: 'sounds wrong in an Italian sauce, tastes right' },
      { ref: 'oregano_dried', grams: 2 },
      { ref: 'bay_leaf', grams: 1, note: '2 leaves' },
      { ref: 'salt', grams: 8, absorption: 0.44, note: '5 g in the pasta water, 3 g in the sauce' },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'sugar', grams: 3, note: 'only if the tomatoes taste sharp' },
      { ref: 'basil_fresh', grams: 8, optional: true },
    ],
    method: [
      { n: 1, text: 'Rinse the lentils in a sieve under cold water until the water running through is clear rather than cloudy.', tip: 'That cloudiness is loose surface starch. Left in, it thickens the sauce into something closer to porridge than ragu.' },
      { n: 2, text: 'Dice the onion and carrot as small as you can manage — about 5 mm.', tip: 'This is the only job in the recipe worth being fussy about. Chunky vegetables make it read as a vegetable stew with pasta; a fine dice disappears into the sauce and reads as bolognese.' },
      { n: 3, text: 'Chop the mushrooms finely — smaller than the vegetable dice.' },
      { n: 4, text: 'Heat the olive oil in a wide pan over medium heat and cook the onion and carrot for 10 minutes with a pinch of the salt, until soft but not coloured.', minutes: 10 },
      { n: 5, text: 'Turn the heat up and add the mushrooms. Cook for 8 minutes.', minutes: 8, tip: 'They will release a load of water and the pan will look wrong. Keep going. The flavour arrives after the pan goes dry again and the mushrooms start to squeak and brown — that is usually around the 6 minute mark.' },
      { n: 6, text: 'Add the garlic for 1 minute, then the tomato puree, and stir for 90 seconds until it darkens from bright red to brick.', minutes: 3 },
      { n: 7, text: 'Add the lentils, tinned tomatoes, crumbled stock cube, water, bay leaves, oregano, soy sauce, pepper and the remaining 3 g of salt.' },
      { n: 8, text: 'Bring it to a boil, then drop to a bare simmer, uncovered, for 30 minutes. Stir along the bottom of the pan every 5 minutes or so.', minutes: 30, tip: 'Scrape flat along the base, not in circles. Lentils sink as they soften and the layer sitting on the bottom is the bit that catches and taints the whole pan.' },
      { n: 9, text: 'Put a large pan of water on with the remaining 5 g of salt, ready for the pasta.' },
      { n: 10, text: 'At 30 minutes the lentils should have lost their shape completely and a spoon dragged through should leave a track that holds for a second. If it is soupy, simmer on; if it is stiff, splash in hot water.' },
      { n: 11, text: 'Cook the spaghetti for 1 minute less than the packet says.', minutes: 9 },
      { n: 12, text: 'Fish out the bay leaves. Taste the sauce: salt first, then the sugar only if it tastes sharp rather than flat.' },
      { n: 13, text: 'Drain the pasta but keep a mugful of the water. Tip the pasta into the sauce pan and toss it through for a minute over low heat, adding splashes of the pasta water until it coats every strand.', minutes: 1, tip: 'Tossed through, not dolloped on top. The starchy water is what makes the sauce cling instead of sliding off into a puddle at the bottom of the bowl — this step is where the dish is actually made.' },
      { n: 14, text: 'Serve immediately, with torn basil if using.' },
    ],
    failures: [
      { symptom: 'Gluey, porridge-like sauce', cause: 'Lentils not rinsed, or boiled hard instead of simmered. Loosen it with hot water and rinse properly next time.' },
      { symptom: 'Scorched taste through the whole pan', cause: 'Heat too high after the lentils went in, or not stirred along the base. Do not stir a burnt pan — decant the good sauce off the top into a clean pan and leave the bottom behind.' },
      { symptom: 'Tastes like tomato soup with lentils in it', cause: 'The tomato puree was not fried, or the soy sauce was skipped. Those two steps are carrying all the savoury depth that meat would otherwise bring.' },
      { symptom: 'Sauce sitting in a puddle under naked pasta', cause: 'Not tossed together. Pasta and sauce need a minute in the same pan with a splash of pasta water.' },
      { symptom: 'Sharp and metallic', cause: 'Acidic tinned tomatoes. A pinch of sugar now; a longer simmer and a properly fried puree next time.' },
    ],
    variants: [
      {
        id: 'bolognese_soya',
        label: 'Higher protein, with soya',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'red_lentils', to: 'red_lentils', grams: 130 },
          { from: 'soya_chunks', to: 'soya_chunks', grams: 50 },
        ],
        methodDeltas: [
          { step: 7, change: 'Add the dry soya chunks along with the lentils, and increase the water to 600 g. They rehydrate in the sauce and drink far more liquid than looks reasonable.' },
          { step: 8, change: 'Simmer for 40 minutes, not 30. Soya chunks that are undercooked stay springy and squeak, which is exactly the texture that makes people decide they do not like them.' },
          { step: 10, change: 'Judge it by the spoon track, not the clock — with soya in it the sauce thickens later and more suddenly than the plain lentil version.' },
        ],
      },
      {
        id: 'bolognese_beef',
        label: 'With beef mince',
        tags: ['halal', 'dairy_free', 'nut_free'],
        swaps: [{ from: 'red_lentils', to: 'beef_mince_5', grams: 400 }],
        methodDeltas: [
          { step: 1, change: 'Nothing to rinse. Instead, brown the mince first: high heat, half the oil, half the meat, pressed flat and left untouched for 4 minutes, then the second batch. Lift it out and keep it.' },
          { step: 4, change: 'Soften the onion and carrot in the fat and brown scrapings the mince left behind, with the rest of the oil. That fond is the reason for browning in batches.' },
          { step: 7, change: 'Return the mince here, and use 250 g of water rather than 450 g. Meat does not absorb liquid the way lentils do, so the same amount would leave you with soup.' },
          { step: 8, change: 'Simmer for 45 minutes rather than 30. Lentils are done when they collapse; mince is done when it stops being chewy, and that takes longer.' },
        ],
      },
    ],
  },

  {
    id: 'salmon_traybake',
    name: 'Salmon Traybake with Potatoes and Greens',
    cuisine: 'British',
    country: 'GB',
    blurb: 'The only thing in the menu carrying serious omega-3 and vitamin D, and it is a one-tray dish with fifteen minutes of work in it.',
    servings: 2,
    activeMin: 15,
    totalMin: 50,
    difficulty: 'easy',
    restaurantGBP: 13.5,
    tags: ['halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
    items: [
      { ref: 'salmon', grams: 300, note: '2 fillets, skin on' },
      { ref: 'potato', grams: 500, note: 'new potatoes halved, or maincrop cut to 3 cm' },
      { ref: 'courgette', grams: 200, note: 'thick half-moons, about 1.5 cm' },
      { ref: 'peas_frozen', grams: 120, note: 'from frozen, added at the end' },
      { ref: 'spinach_fresh', grams: 120, note: 'folded through the hot tray off the heat' },
      { ref: 'olive_oil', grams: 30 },
      { ref: 'lemon', grams: 70, note: 'half sliced for the tray, half squeezed over at the end' },
      { ref: 'garlic', grams: 12, note: '3 cloves, crushed' },
      { ref: 'dijon_mustard', grams: 10 },
      { ref: 'dill_fresh', grams: 10, note: 'half into the dressing, half over at the end' },
      { ref: 'salt', grams: 5 },
      { ref: 'black_pepper', grams: 2 },
    ],
    method: [
      { n: 1, text: 'Heat the oven to 220C (200C fan, gas 7) and give it a full 15 minutes.', minutes: 15 },
      { n: 2, text: 'Halve the potatoes and toss them with 20 g of the oil, half the salt and the pepper on a large flat baking tray. Turn them all cut-side down.', tip: 'Cut-side down is the whole point. That flat face is the only part in real contact with the hot metal, and it is where the crisp crust comes from.' },
      { n: 3, text: 'Roast for 25 minutes.', minutes: 25 },
      { n: 4, text: 'Meanwhile, mix the remaining 10 g oil with the mustard, crushed garlic, half the dill and the juice of half the lemon.' },
      { n: 5, text: 'Pat the salmon completely dry on both sides with kitchen paper, then season it with the remaining salt.', minutes: 2, tip: 'Dry first, then salt. A wet fillet steams itself in the oven, the skin goes flabby instead of crisping, and salt on a wet surface just draws out more water.' },
      { n: 6, text: 'Pull the tray, add the courgette, turn everything over and roast for another 8 minutes.', minutes: 8 },
      { n: 7, text: 'Push the vegetables to the edges. Lay the salmon skin-side DOWN in the cleared middle, spoon the mustard mixture over the flesh, and tuck the lemon slices around it.', tip: 'Skin down, directly on the hot tray. Skin up, and you get a pale rubbery layer nobody wants; skin down, it renders and crisps and also shields the flesh from the tray heat.' },
      { n: 8, text: 'Roast for 12-14 minutes.', minutes: 13, tip: 'Press the thickest part with a fork: it is ready the moment the flesh just separates into flakes and the very centre has turned from glassy to opaque. If it is falling apart on its own, it went too far about 2 minutes ago.' },
      { n: 9, text: 'Scatter the frozen peas over the vegetables for the last 4 minutes of that time.', minutes: 4 },
      { n: 10, text: 'Take the tray out, pile the spinach onto the hot vegetables and fold it through. It wilts in about a minute on the residual heat.' },
      { n: 11, text: 'Rest for 3 minutes, then squeeze over the remaining lemon and scatter the rest of the dill.', minutes: 3 },
    ],
    failures: [
      { symptom: 'Salmon dry and chalky, with white curd on the surface', cause: 'Overcooked. That white stuff is protein squeezed out of the muscle. 14 minutes is the ceiling for a standard supermarket fillet.' },
      { symptom: 'Skin soggy and grey', cause: 'Fish put in skin-side up, or not dried before it went in. Both are fixable next time and neither is fixable now.' },
      { symptom: 'Potatoes still hard when the fish is done', cause: 'Cut too large, or the oven was not up to temperature. They get a 33-minute head start for a reason.' },
      { symptom: 'Fish welded to the tray', cause: 'No oil under it. Move a spoonful of oil into the cleared middle before the salmon goes down, or lay it on the lemon slices.' },
      { symptom: 'Watery tray', cause: 'Courgette added at the start. It is about 95 per cent water and only goes in for the last stretch.' },
    ],
    variants: [
      {
        id: 'salmon_white_fish',
        label: 'Cheaper, with white fish',
        tags: ['halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [{ from: 'salmon', to: 'white_fish', grams: 320 }],
        methodDeltas: [
          { step: 5, change: 'Cod and haddock have almost no fat of their own, so dry them and then brush them with oil as well as seasoning, or they will bake to cotton wool.' },
          { step: 8, change: '9-10 minutes, not 13. White fish is done at the very first sign of flaking, and the window between done and ruined is roughly 2 minutes wide.' },
        ],
        note: 'Cheaper and leaner, but this variant does not fill the gap the dish exists for — omega-3 drops by about 90 per cent and vitamin D with it.',
      },
      {
        id: 'salmon_bigger',
        label: 'Higher protein',
        tags: ['halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'salmon', to: 'salmon', grams: 420 },
          { from: 'potato', to: 'potato', grams: 380 },
        ],
        methodDeltas: [
          { step: 3, change: 'Less potato on the tray roasts faster and browns sooner. 20 minutes here, not 25.' },
          { step: 8, change: 'Thicker fillets need 15-16 minutes. Check the fattest one and ignore the thin tail ends, which will always be done first.' },
        ],
      },
      {
        id: 'salmon_halloumi',
        label: 'Vegetarian, with halloumi',
        tags: ['vegetarian', 'halal', 'kosher', 'gluten_free', 'nut_free'],
        swaps: [{ from: 'salmon', to: 'halloumi', grams: 250 }],
        methodDeltas: [
          { step: 5, change: 'Nothing to dry out or worry about. Pat the halloumi dry and cut it into 1 cm slabs. Do not salt it — it is already very salty.' },
          { step: 7, change: 'Halloumi browns long before 13 minutes and then turns to rubber. Add it for the last 10 minutes only, and lay it flat rather than spooning the mustard mixture over it — that just slides off and burns on the tray. Dress it after it comes out.' },
          { step: 8, change: 'There is no flake test. It is ready when the edges are deep golden and it squeaks against a fork.' },
        ],
        note: 'A genuinely different dish nutritionally: no omega-3, no vitamin D, and around six times the sodium.',
      },
    ],
  },

  {
    id: 'omelette_cheese_herb',
    name: 'Cheese and Herb Omelette on Toast',
    cuisine: 'French',
    country: 'FR',
    blurb: 'Ten minutes from cold kitchen to plate, and the only real technique is knowing when to stop.',
    servings: 2,
    activeMin: 10,
    totalMin: 10,
    difficulty: 'easy',
    restaurantGBP: 7.5,
    tags: ['vegetarian', 'halal', 'kosher', 'nut_free'],
    items: [
      { ref: 'egg', grams: 220, note: '4 large' },
      { ref: 'cheddar', grams: 60, note: 'grated, not sliced' },
      { ref: 'butter', grams: 20, note: '10 g per omelette' },
      { ref: 'parsley_fresh', grams: 8, note: 'finely chopped' },
      { ref: 'spring_onion', grams: 20, note: 'green parts only, sliced thin' },
      { ref: 'bread_sourdough', grams: 100, note: '2 thick slices, to serve' },
      { ref: 'salt', grams: 2 },
      { ref: 'black_pepper', grams: 1 },
      { ref: 'tomato_fresh', grams: 100, optional: true, note: 'halved and salted, on the side' },
    ],
    method: [
      { n: 1, text: 'Grate the cheese and chop the parsley and spring onion before you touch the eggs. Put them next to the hob.', tip: 'An omelette takes three minutes and has no pause button. Anything not already grated, chopped and within arm reach when the eggs hit the pan is not going into this omelette.' },
      { n: 2, text: 'Put the bread in the toaster but do not start it yet.' },
      { n: 3, text: 'Crack all four eggs into a bowl with the salt and pepper and beat with a fork for 30 full seconds, until the colour is completely uniform.', tip: 'Thirty seconds is longer than it feels. Any streaks of unbeaten white left in the bowl set into tough rubbery ribbons that you can find with your teeth.' },
      { n: 4, text: 'Put a 20-24 cm non-stick pan on medium heat for 1 minute, then add 10 g of the butter and swirl it to coat.', minutes: 1, tip: 'The butter should foam gently and then go quiet. If it browns and smells nutty within a few seconds, the pan is too hot — wipe it out, let it cool, start again.' },
      { n: 5, text: 'Pour in half the beaten egg and leave it completely still for 10 seconds.' },
      { n: 6, text: 'With a spatula, push the set edge in toward the middle and tilt the pan so the raw egg floods into the gap. Work your way around the pan for 45-60 seconds.', minutes: 1, tip: 'Big slow pushes, four or five of them. You are building soft layers, not scrambling — if the spatula is moving constantly you are making scrambled eggs in a circle.' },
      { n: 7, text: 'Stop while the surface still looks glossy and slightly wet, and slide the pan off the heat.', tip: 'The residual heat in the pan finishes it during the folding. An omelette that looks perfectly cooked in the pan is a dry one on the plate — this is the single mistake that separates a good omelette from a bad one.' },
      { n: 8, text: 'Scatter half the cheese, parsley and spring onion over one half of the omelette and wait 20 seconds for the cheese to soften.' },
      { n: 9, text: 'Fold the bare half over with the spatula and slide it onto a plate.' },
      { n: 10, text: 'Start the toast, wipe the pan out with kitchen paper, and repeat with the second 10 g of butter and the rest of the egg.', minutes: 4 },
      { n: 11, text: 'Serve each omelette on or beside its toast, with the salted tomatoes if using.' },
    ],
    failures: [
      { symptom: 'Brown, leathery base', cause: 'Heat too high. Medium, and the butter should never brown.' },
      { symptom: 'Torn and stuck when you tried to fold it', cause: 'Moved too early, not enough butter, or a pan whose non-stick has given up. Wait the first 10 seconds out before touching it.' },
      { symptom: 'Water weeping onto the plate', cause: 'Overcooked. The egg proteins tightened and squeezed their water out. Off the heat while glossy.' },
      { symptom: 'Cheese still in cold shreds', cause: 'Sliced rather than grated, or added after the pan had already cooled. Grate it, and give it 20 seconds on the warm egg before folding.' },
      { symptom: 'Rubbery ribbons through an otherwise fine omelette', cause: 'Eggs under-beaten. Beat until you cannot see a single streak of white.' },
    ],
    variants: [
      {
        id: 'omelette_vegan',
        label: 'Vegan tofu scramble',
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
        swaps: [
          { from: 'egg', to: 'tofu_firm', grams: 320 },
          { from: 'cheddar', to: null },
          { from: 'butter', to: 'olive_oil', grams: 20 },
          { from: 'turmeric', to: 'turmeric', grams: 1 },
        ],
        methodDeltas: [
          { step: 3, change: 'Nothing to beat. Press the tofu for 10 minutes, then crumble it with your fingers into irregular curds — even cubes read as tofu, irregular curds read as scramble.' },
          { step: 6, change: 'Tofu has no proteins to set, so the fold-and-tilt technique does nothing. Cook it on MEDIUM-HIGH for 6-8 minutes instead, stirring occasionally, until the water has driven off and the edges brown. That is the opposite of the egg method in every respect.' },
          { step: 7, change: 'There is no glossy stage to stop at. Stop when it stops looking wet and starts sticking to the pan slightly.' },
          { step: 8, change: 'No cheese and no fold. Stir the turmeric in for colour, season it harder than you think — tofu absorbs salt rather than carrying it — and pile it onto the toast.' },
        ],
        note: 'This is a scramble, not an omelette, and it takes about twice as long. Pretending otherwise is why people give up on tofu.',
      },
      {
        id: 'omelette_lean',
        label: 'Leaner, higher protein',
        tags: ['vegetarian', 'halal', 'kosher', 'nut_free'],
        swaps: [
          { from: 'egg', to: 'egg', grams: 300 },
          { from: 'cheddar', to: 'cheddar', grams: 35 },
          { from: 'butter', to: 'butter', grams: 10 },
        ],
        methodDeltas: [
          { step: 4, change: '5 g of butter per omelette barely coats the pan, so the heat has to come down a notch and the non-stick has to be genuinely good. Swirl the butter right to the edges.' },
          { step: 6, change: 'More egg means a thicker omelette that sets more slowly. Expect 75-90 seconds and one or two extra rounds of pushing the edges in.' },
        ],
      },
      {
        id: 'omelette_mushroom',
        label: 'With mushrooms',
        tags: ['vegetarian', 'halal', 'kosher', 'nut_free'],
        swaps: [
          { from: 'tomato_fresh', to: null },
          { from: 'mushroom', to: 'mushroom', grams: 150 },
        ],
        methodDeltas: [
          { step: 1, change: 'Slice the mushrooms and fry them first, in the dry pan on high for 5 minutes until they have released their water, reabsorbed it and started to brown. Tip them out and wipe the pan before the eggs go anywhere near it — mushrooms added wet make the omelette weep.' },
          { step: 8, change: 'Scatter the mushrooms over the same half as the cheese, before folding.' },
        ],
        note: 'Adds about 6 minutes, so this one no longer fits a 10-minute slot.',
      },
    ],
  },
  {
    id: 'buffalo_wings_baked',
    name: 'Buffalo Wings, Baked Not Fried',
    cuisine: 'American',
    country: 'US',
    blurb: 'The wing-shop texture without the fryer. Baking powder and a two-stage oven do what 180 C of oil normally does, and the fat that would have been sealed in renders out and drains away instead.',
    servings: 2,
    activeMin: 15,
    totalMin: 100,
    difficulty: 'easy-medium',
    items: [
      { ref: 'chicken_wing', grams: 700, note: 'split into flats and drumettes, tips discarded or saved for stock' },
      { ref: 'baking_powder', grams: 6, note: 'BAKING POWDER, not bicarbonate of soda — bicarb tastes of metal and soap' },
      { ref: 'salt', grams: 2, note: 'the hot sauce is already very salty — taste before adding more' },
      { ref: 'black_pepper', grams: 1 },
      { ref: 'paprika_smoked', grams: 3 },
      { ref: 'garlic', grams: 6, note: 'granulated or finely grated, into the coating' },
      { ref: 'hot_sauce', grams: 55, note: 'a cayenne sauce — Frank\u2019s is the original' },
      { ref: 'butter', grams: 18, note: 'a third of what a wing shop uses, and the sauce still clings' },
      { ref: 'vinegar_white', grams: 5, note: 'off the heat, to sharpen it back up' },
      { ref: 'carrot', grams: 100, note: 'cut into batons, to serve' },
      { ref: 'cucumber', grams: 80, note: 'batons, to serve' },
      { ref: 'greek_yogurt', grams: 60, note: 'the dip, instead of blue cheese dressing' },
      { ref: 'lemon', grams: 10, note: 'a squeeze into the yogurt' },
    ],
    method: [
      { n: 1, text: 'Pat the wings properly dry with kitchen paper — drier than feels necessary. Every bit of surface water is water the oven has to boil off before it can start browning, and that is the whole difference between crisp and pale.', minutes: 5,
        tip: 'If you have time, salt them and leave them uncovered on a rack in the fridge for 4 to 12 hours first. A dry fridge is a dehydrator, and this single step does more than anything else on the list.' },
      { n: 2, text: 'Mix the baking powder, salt, pepper, smoked paprika and garlic in a large bowl. Add the wings and turn them until every one is evenly, thinly dusted — it should look like a light coating, not a batter.', minutes: 4,
        tip: 'Baking powder raises the skin\u2019s pH, which breaks down proteins faster and pulls moisture to the surface where it can evaporate. Bicarbonate of soda is far more alkaline and will taste of it.' },
      { n: 3, text: 'Set a wire rack inside a foil-lined baking tray and lay the wings out in one layer, not touching. Air has to reach underneath or the bottom steams in its own fat.', minutes: 3 },
      { n: 4, text: 'Bake at 120 C fan on a lower shelf for 30 minutes. Nothing will look like it is happening. It is: the fat under the skin is melting and running out, which is the fat you are not eating.', minutes: 30 },
      { n: 5, text: 'Move the tray to an upper shelf, turn the oven up to 220 C fan and bake for a further 40 to 50 minutes, turning the tray once. The wings must reach 75 C at the thickest part next to the bone.', minutes: 45,
        tip: 'Take them past the point where you think they are done. Wings are forgiving in a way breast is not, and the last ten minutes is where the skin goes from browned to shattering.' },
      { n: 6, text: 'While they finish, warm the hot sauce and butter together in a small pan over a low heat, whisking until it comes together. Take it off the heat and stir in the vinegar.', minutes: 4,
        tip: 'Do not let it boil. Boiled butter sauce splits, and a split sauce slides off the wings instead of coating them.' },
      { n: 7, text: 'Stir the lemon juice into the yogurt with a pinch of salt for the dip. Cut the carrot and cucumber into batons.', minutes: 4 },
      { n: 8, text: 'Tip the hot wings into a clean dry bowl, pour over the sauce and toss for about 15 seconds. Serve straight away, with the dip and the vegetables.', minutes: 2,
        tip: 'Sauce them at the last possible moment. Every minute a wing sits in sauce is a minute the skin you spent 80 minutes building is going soft.' },
    ],
    failures: [
      { symptom: 'Pale and rubbery skin', cause: 'The wings went in wet, or they were crowded. Water and steam both stop browning, and a tray of touching wings makes plenty of both.' },
      { symptom: 'A soapy, metallic aftertaste', cause: 'Bicarbonate of soda instead of baking powder. They are not interchangeable — bicarb is roughly four times as alkaline.' },
      { symptom: 'The sauce slid off and pooled', cause: 'It was boiled and split, or the wings were sauced too early and went soft first.' },
      { symptom: 'Crisp outside, still bloody at the bone', cause: 'The oven ran cool or the wings were very large. Skin colour is not doneness — check 75 C at the thickest part.' },
    ],
    variants: [
      {
        id: 'wings_air_fryer',
        label: 'In an air fryer',
        swaps: [],
        methodDeltas: [
          { step: 4, change: 'Skip the low stage. An air fryer is a small fan oven and renders fat fast enough without it.' },
          { step: 5, change: 'Air fry at 190 C for 12 minutes, shake, then 200 C for 8 to 10 minutes. Still check 75 C at the bone — a smaller machine browns faster than it cooks through.' },
        ],
        tags: ['halal', 'gluten_free', 'nut_free'],
        note: 'Faster and crisper, but you will be doing it in two batches unless the basket is large.',
      },
      {
        id: 'wings_lean_thigh',
        label: 'Leaner, with thigh',
        swaps: [{ from: 'chicken_wing', to: 'chicken_thigh', grams: 600 }],
        methodDeltas: [
          { step: 1, change: 'Use boneless thighs, opened out flat. There is far less skin per gram, so the result is less crisp and considerably leaner.' },
          { step: 4, change: 'Cut the low stage to 15 minutes. There is much less fat under the skin to render.' },
          { step: 5, change: '25 to 30 minutes at 220 C is enough. Check 75 C at the thickest point.' },
        ],
        tags: ['halal', 'gluten_free', 'nut_free'],
      },
      {
        id: 'wings_vegan_cauli',
        label: 'Cauliflower, vegan',
        swaps: [
          { from: 'chicken_wing', to: 'white_cabbage', grams: 600 },
          { from: 'butter', to: 'olive_oil', grams: 15 },
          { from: 'greek_yogurt', to: 'tahini', grams: 50 },
        ],
        methodDeltas: [
          { step: 1, change: 'Nothing to dry. Break into florets roughly the size of a wing.' },
          { step: 2, change: 'Toss with the spices and 15 g of the oil instead of dusting — there is no skin for the baking powder to work on, so leave it out.' },
          { step: 4, change: 'Skip the low stage entirely. There is no fat to render.' },
          { step: 5, change: '25 minutes at 220 C, turning once, until the edges are properly dark. Pale cauliflower tastes of nothing.' },
          { step: 6, change: 'Warm the hot sauce with the olive oil rather than butter.' },
          { step: 7, change: 'Loosen the tahini with water and lemon to a pourable dip.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free'],
        note: 'A different dish that scratches the same itch. It will not be crisp the way skin is crisp.',
      },
    ],
    restaurantGBP: 11.5,
    tags: ['halal', 'gluten_free', 'nut_free'],
  },
];
