import { Recipe } from './types';

export const RECIPES_A: Recipe[] = [
  // ==========================================================================
  // 1. BUTTER CHICKEN
  // ==========================================================================
  {
    id: 'butter_chicken',
    name: 'Butter Chicken (Murgh Makhani)',
    localName: 'मुर्ग़ मखनी',
    cuisine: 'North Indian',
    country: 'IN',
    blurb: 'Yogurt-marinated thigh seared hard, then finished in a cashew-thickened tomato sauce enriched with butter and cream off the heat.',
    servings: 2,
    activeMin: 40,
    totalMin: 85,
    difficulty: 'medium',
    items: [
      { ref: 'chicken_thigh', grams: 400, note: 'boneless and skinless, cut into 3 cm pieces' },
      { ref: 'greek_yogurt', grams: 80, note: 'for the marinade' },
      { ref: 'lemon', grams: 15, note: 'juice only' },
      { ref: 'garlic', grams: 20, note: 'crushed; half to the marinade, half to the sauce' },
      { ref: 'ginger', grams: 20, note: 'finely grated; half to the marinade, half to the sauce' },
      { ref: 'kashmiri_chilli', grams: 6, note: 'mild, this is the colour not the heat' },
      { ref: 'turmeric', grams: 2 },
      { ref: 'cumin_ground', grams: 4 },
      { ref: 'coriander_ground', grams: 4 },
      { ref: 'garam_masala', grams: 5, note: 'half in the marinade, half stirred in at the very end' },
      { ref: 'salt', grams: 8 },
      { ref: 'vegetable_oil', grams: 15, note: 'for searing' },
      { ref: 'butter', grams: 50, note: 'half for the onions, half diced and cold for finishing' },
      { ref: 'onion', grams: 120, note: 'finely diced' },
      { ref: 'tomato_puree', grams: 30 },
      { ref: 'passata', grams: 300 },
      { ref: 'cashews', grams: 40, note: 'soaked in just-boiled water for 20 min' },
      { ref: 'double_cream', grams: 60, note: 'off the heat' },
      { ref: 'sugar', grams: 6, note: 'balances the tomato acidity' },
      { ref: 'fenugreek_leaves', grams: 2, note: 'kasuri methi, crushed between the palms' },
      { ref: 'basmati_rice', grams: 150, note: 'dry weight, rinsed until the water runs clear' },
      { ref: 'water', grams: 480, note: '300 g for the rice, 180 g split between the sauce and the cashew paste' },
      { ref: 'coriander_fresh', grams: 8, note: 'chopped, to finish', optional: true },
      { ref: 'flatbread', grams: 120, note: 'naan, warmed', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'Pat the chicken dry with kitchen paper. In a bowl mix the yogurt, half the garlic, half the ginger, the kashmiri chilli, turmeric, cumin, ground coriander, half the garam masala, half the salt and the lemon juice. Fold the chicken through until every piece is coated. Cover and refrigerate for at least 30 minutes, or up to 12 hours.',
        minutes: 30,
        tip: 'Dry the chicken first. Marinade slides straight off wet meat and you lose both the seasoning and the char.',
      },
      {
        n: 2,
        text: 'Put the cashews in a mug, cover with just-boiled water and leave them to soften while you cook.',
        minutes: 20,
      },
      {
        n: 3,
        text: 'Heat the vegetable oil in a wide frying pan over high heat until it shimmers. Sear the marinated chicken in a single layer for about 3 minutes per side, in two batches, until there are dark charred patches. The chicken does not need to be cooked through yet. Set it aside on a plate with any juices.',
        minutes: 12,
        tip: 'Two batches, always. A crowded pan drops in temperature and the chicken boils grey in its own liquid instead of catching colour.',
      },
      {
        n: 4,
        text: 'Turn the heat to medium. Add 25 g of the butter and the diced onion to the same pan and cook for 8 minutes, scraping the browned bits off the base, until the onion is soft and pale gold.',
        minutes: 8,
      },
      {
        n: 5,
        text: 'Add the remaining garlic and ginger and stir constantly for 60 seconds.',
        minutes: 1,
        tip: 'Stop the moment it smells sweet and fragrant rather than raw and dusty. Garlic burns in about 20 seconds past that point and turns the sauce bitter.',
      },
      {
        n: 6,
        text: 'Add the tomato puree and fry it for 2 minutes, stirring, until the colour shifts from bright red to a darker brick red and it starts to stick.',
        minutes: 2,
      },
      {
        n: 7,
        text: 'Pour in the passata and 100 g of the water, add the sugar and the remaining salt, and simmer uncovered over medium-low heat for 12 minutes.',
        minutes: 12,
        tip: 'You are waiting for beads of orange oil to pool at the edge of the pan. That is the signal the tomato is cooked out. If you stop before it, the sauce tastes sharp and raw no matter how much cream goes in.',
      },
      {
        n: 8,
        text: 'While that simmers, cook the rice. Put the rinsed basmati and 300 g water in a small pan with a pinch of salt, bring to a boil uncovered, then clamp on a lid, drop to the lowest heat for 10 minutes, and leave it off the heat for a further 10 minutes.',
        minutes: 20,
        tip: 'Do not lift the lid to check. Every peek releases the steam that is actually cooking the top layer of grains.',
      },
      {
        n: 9,
        text: 'Drain the cashews and blend them with 80 g fresh water to a completely smooth cream. Blend the tomato sauce smooth too, with a stick blender in the pan or in a jug blender, then return it to the pan.',
        minutes: 4,
      },
      {
        n: 10,
        text: 'Stir the cashew cream into the sauce and return the seared chicken with all its resting juices. Simmer gently for 8 minutes until the chicken reaches 74 C at the centre of the thickest piece.',
        minutes: 8,
      },
      {
        n: 11,
        text: 'Take the pan completely off the heat and wait 2 minutes. Now stir in the double cream, the remaining 25 g of cold diced butter a piece at a time, the remaining garam masala and the fenugreek leaves crushed between your palms.',
        minutes: 3,
        tip: 'Off the heat is not optional. Cream and butter added to a bubbling pan will break into grainy curds and an oil slick within seconds.',
      },
      {
        n: 12,
        text: 'Let it sit for 5 minutes, then taste. It should be faintly sweet, clearly sour and salty enough to taste the spices; adjust with a pinch of salt or sugar. Fluff the rice with a fork, scatter the coriander over the curry and serve with warm naan.',
        minutes: 5,
      },
    ],
    failures: [
      { symptom: 'Sauce tastes sharp and raw, like warm tinned tomato', cause: 'The tomato was not cooked out at step 7; keep simmering uncovered until oil beads at the edge, then correct with 2 g more sugar off the heat.' },
      { symptom: 'Sauce split into grainy curds with an oil slick', cause: 'Cream went in over direct heat; pull the pan off, let it cool 2 minutes, then whisk in the cream and cold butter a piece at a time.' },
      { symptom: 'Chicken is dry and stringy', cause: 'It was seared until cooked through and then simmered as well; sear only for colour and let it finish to 74 C in the sauce at step 10.' },
      { symptom: 'Colour is dull brown instead of orange', cause: 'Hot chilli powder was used in place of kashmiri chilli, or the tomato puree scorched at step 6; kashmiri chilli is a colouring spice and needs to fry, not burn.' },
      { symptom: 'Sauce is thin and slides off the rice', cause: 'The passata was not reduced enough or the cashews were skipped; simmer 5 minutes longer before the cream, or blend in 10 g more soaked cashews.' },
    ],
    variants: [
      {
        id: 'bc_breast_lean',
        label: 'Leaner, with breast and yogurt',
        swaps: [
          { from: 'chicken_thigh', to: 'chicken_breast', grams: 380 },
          { from: 'double_cream', to: 'greek_yogurt', grams: 80 },
        ],
        methodDeltas: [
          { step: 3, change: 'Breast has no fat to protect it: sear 90 seconds per side for colour only, not 3 minutes.' },
          { step: 10, change: 'Cut the simmer from 8 minutes to 4 minutes and pull the pan the moment the centre hits 74 C. Breast goes chalky within a minute of that.' },
          { step: 11, change: 'Yogurt curdles far more readily than cream. Let the pan stand off the heat for a full 4 minutes, slacken the yogurt with 2 tablespoons of the hot sauce first, then stir the loosened yogurt back in.' },
        ],
        tags: ['halal'],
        note: 'Roughly a third less fat and a little more protein per portion; the sauce is tangier and thinner.',
      },
      {
        id: 'bc_paneer',
        label: 'Paneer makhani (vegetarian)',
        swaps: [
          { from: 'chicken_thigh', to: 'paneer', grams: 300 },
        ],
        methodDeltas: [
          { step: 1, change: 'Do not marinate paneer in yogurt for hours; the acid makes it rubbery. Toss the cubes in the spices and yogurt for 15 minutes only.' },
          { step: 3, change: 'Fry the paneer over medium-high heat for 2 minutes per side until just golden, then drop the cubes into a bowl of warm salted water while the sauce cooks. This keeps them soft instead of squeaky.' },
          { step: 10, change: 'Add the drained paneer for the last 3 minutes only, just to heat through. There is nothing to cook through, and a long simmer tightens the curd.' },
        ],
        tags: ['vegetarian'],
      },
      {
        id: 'bc_vegan_tofu',
        label: 'Vegan, with tofu and coconut cream',
        swaps: [
          { from: 'chicken_thigh', to: 'tofu_firm', grams: 350 },
          { from: 'greek_yogurt', to: 'soya_yogurt', grams: 80 },
          { from: 'butter', to: 'vegetable_oil', grams: 35 },
          { from: 'double_cream', to: 'coconut_cream', grams: 70 },
        ],
        methodDeltas: [
          { step: 1, change: 'Press the tofu between two plates under a heavy tin for 20 minutes before it goes anywhere near the marinade, otherwise it releases water into the sauce.' },
          { step: 3, change: 'Tofu will not char like chicken. Fry it for 4 minutes per side over medium-high heat until the edges are firm and golden, and turn it with a fish slice rather than tossing the pan.' },
          { step: 10, change: 'Nothing needs to reach a safe temperature, so simmer the tofu for just 4 minutes.' },
          { step: 11, change: 'Coconut cream tolerates a little more heat than dairy but it will taste flat; add 5 g extra lemon juice with it to replace the sourness the yogurt and cream were providing.' },
        ],
        tags: ['vegan', 'vegetarian', 'dairy_free'],
      },
      {
        id: 'bc_prawn',
        label: 'Prawn makhani',
        swaps: [
          { from: 'chicken_thigh', to: 'prawns_raw', grams: 300 },
        ],
        methodDeltas: [
          { step: 1, change: 'Marinate the prawns for 15 minutes maximum. The lemon juice will start to cure them and turn the texture mealy if you leave them longer.' },
          { step: 3, change: 'Skip the sear entirely; raw prawns go straight into the finished sauce.' },
          { step: 10, change: 'Add the prawns to the simmering sauce and cook for 3 minutes only, until they curl into a loose C and turn opaque. A tight O means they are overcooked.' },
        ],
        tags: ['halal'],
      },
    ],
    restaurantGBP: 11.95,
    tags: ['halal'],
  },

  // ==========================================================================
  // 2. CHICKEN BIRYANI
  // ==========================================================================
  {
    id: 'chicken_biryani',
    name: 'Chicken Biryani',
    localName: 'بریانی',
    cuisine: 'South Asian',
    country: 'IN',
    blurb: 'Marinated chicken and parboiled basmati layered in one pot with fried onions and saffron milk, then steamed sealed under dum until the grains finish in the trapped steam.',
    servings: 2,
    activeMin: 55,
    totalMin: 130,
    difficulty: 'hard',
    items: [
      { ref: 'chicken_thigh', grams: 450, note: 'boneless, cut into large 5 cm pieces' },
      { ref: 'greek_yogurt', grams: 200, note: '120 g for the marinade, 80 g for the raita' },
      { ref: 'garlic', grams: 20, note: 'crushed to a paste' },
      { ref: 'ginger', grams: 20, note: 'grated to a paste' },
      { ref: 'green_chilli', grams: 12, note: 'slit lengthways' },
      { ref: 'turmeric', grams: 2 },
      { ref: 'kashmiri_chilli', grams: 5 },
      { ref: 'garam_masala', grams: 6 },
      { ref: 'cumin_ground', grams: 5, note: '4 g in the marinade, a pinch saved for the raita' },
      { ref: 'coriander_ground', grams: 4 },
      { ref: 'salt', grams: 30, absorption: 0.23, note: '6 g in the marinade, 24 g in the 2 L parboil water — it must taste properly salty, and nearly all of it is poured away' },
      { ref: 'basmati_rice', grams: 250, note: 'aged basmati, soaked 30 min in cold water' },
      { ref: 'onion', grams: 200, note: 'halved and sliced as thinly as you can manage' },
      { ref: 'vegetable_oil', grams: 60, note: 'for frying the onions' },
      { ref: 'ghee', grams: 30, note: 'drizzled over the layers' },
      { ref: 'cardamom_green', grams: 3, note: 'pods, lightly crushed' },
      { ref: 'cloves_whole', grams: 1 },
      { ref: 'cinnamon_ground', grams: 2 },
      { ref: 'bay_leaf', grams: 1 },
      { ref: 'star_anise', grams: 1 },
      { ref: 'saffron', grams: 0.2, note: 'crumbled' },
      { ref: 'milk_semi', grams: 40, note: 'warmed, for steeping the saffron' },
      { ref: 'mint_fresh', grams: 12, note: 'leaves picked' },
      { ref: 'coriander_fresh', grams: 12, note: 'roughly chopped, stalks included' },
      { ref: 'lemon', grams: 20, note: 'juice, over the top layer' },
      { ref: 'water', grams: 2000, note: 'for parboiling the rice' },
      { ref: 'cucumber', grams: 80, note: 'coarsely grated and squeezed dry, for the raita' },
      { ref: 'plain_flour', grams: 60, note: 'mixed with water into a dough to seal the lid', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'Mix 120 g of the yogurt with the garlic and ginger pastes, the green chilli, turmeric, kashmiri chilli, half the garam masala, the ground cumin, ground coriander and 6 g salt. Fold in the chicken along with half the mint and half the coriander. Cover and refrigerate for at least 45 minutes, ideally overnight.',
        minutes: 45,
      },
      {
        n: 2,
        text: 'Rinse the basmati in a bowl of cold water, swirling and pouring off the cloudy water, four or five times until it runs almost clear. Cover with fresh cold water and leave it to soak for 30 minutes, then drain.',
        minutes: 30,
        tip: 'Soaking is what gives you long separate grains. Unsoaked rice absorbs water unevenly in the pot and snaps into short broken pieces when you fold it.',
      },
      {
        n: 3,
        text: 'Heat the vegetable oil in a frying pan over medium heat and fry the sliced onion, stirring often, for 15 to 18 minutes until deep golden brown. Lift it out with a slotted spoon onto kitchen paper, where it will crisp as it cools. This is your birista. Keep 2 tablespoons of the oil.',
        minutes: 18,
        tip: 'Take the onions out one shade lighter than you want them. They carry on darkening on the paper, and burnt onion makes the entire pot taste bitter in a way nothing can fix.',
      },
      {
        n: 4,
        text: 'Warm the milk until it is hot but not boiling, crumble in the saffron and leave it to steep. It should turn a strong orange within 10 minutes.',
        minutes: 10,
      },
      {
        n: 5,
        text: 'In a heavy casserole with a tight lid, heat the reserved onion oil over medium heat. Add the cardamom, cloves, bay leaf and star anise and let them sizzle for 40 seconds, then tip in the marinated chicken with all its marinade. Cook uncovered for 15 minutes, stirring occasionally.',
        minutes: 16,
        tip: 'Wait for the yogurt to stop looking like a pale sauce and start looking like a thick paste with oil separating at the edges. Watery marinade at the bottom means a soggy biryani base.',
      },
      {
        n: 6,
        text: 'Stir the cinnamon and half the birista through the chicken, level the surface and turn off the heat. This is your bottom layer.',
        minutes: 2,
      },
      {
        n: 7,
        text: 'Bring 2 litres of water to a hard rolling boil in a large pan with 8 g salt. Add the drained rice and boil, uncovered, for 4 to 5 minutes only. Drain it immediately in a colander.',
        minutes: 6,
        tip: 'This is where most biryani fails. Fish out a grain and press it: it should snap into three pieces with a chalky white core still visible. Fully cooked rice here becomes mush after the dum.',
      },
      {
        n: 8,
        text: 'Tip the drained rice straight onto the chicken in an even layer without pressing it down. Scatter over the remaining birista, the remaining mint and coriander, the remaining garam masala, the lemon juice, the saffron milk in stripes, and finally the ghee.',
        minutes: 5,
      },
      {
        n: 9,
        text: 'Seal the pot. Either roll the flour and water dough into a rope and press it around the rim before clamping the lid on, or cover the pot tightly with foil and put the lid on top of that.',
        minutes: 5,
        tip: 'A lid that merely sits on the pot lets the steam escape and the top layer of rice stays hard and dry. It has to be airtight.',
      },
      {
        n: 10,
        text: 'Put the sealed pot over high heat for 3 minutes to build steam, then set it on the lowest possible flame, or on an empty frying pan or heat diffuser, and leave it for 25 minutes. Do not open it.',
        minutes: 28,
        tip: 'The diffuser matters. Direct low heat on a thin base will still scorch the chicken layer, and burnt-bottom smell travels through the whole pot.',
      },
      {
        n: 11,
        text: 'Take the pot off the heat and leave it sealed for a further 10 minutes to settle.',
        minutes: 10,
      },
      {
        n: 12,
        text: 'While it rests, make the raita: stir the remaining 80 g yogurt with the grated and squeezed cucumber, a pinch of salt and the extra pinch of ground cumin.',
        minutes: 4,
      },
      {
        n: 13,
        text: 'Break the seal. Push a flat spoon down the side of the pot to the base and lift a wedge of rice and chicken together onto each plate so the layers stay visible. The thigh pieces must reach 75 C at the thickest point before the rice goes on.',
        minutes: 3,
        tip: 'Never stir a biryani. Stirring smashes the grains and turns the whole thing into a uniform orange pilaf; lift and fold from the edge instead.',
      },
    ],
    failures: [
      { symptom: 'Rice is mushy and the grains have broken up', cause: 'The rice was boiled past 70 per cent at step 7, or it was stirred at the end; boil to a chalky core and lift rather than stir.' },
      { symptom: 'Top layer of rice is still hard and chalky', cause: 'Steam escaped because the lid was not sealed, or the dum was too short; reseal with foil, add 2 tablespoons of hot water down the side and give it another 10 minutes.' },
      { symptom: 'Bottom layer is burnt and the pot smells scorched', cause: 'Direct heat on a thin base; move the pot onto a heat diffuser or an empty frying pan for the whole dum stage.' },
      { symptom: 'Bland and one-note despite all the spices', cause: 'The rice water was underseasoned; the parboiling water should taste properly salty, because that is the only chance the grains get to be seasoned.' },
      { symptom: 'Watery, stew-like base under the rice', cause: 'The marinade was not reduced at step 5; cook the chicken until the yogurt is a thick paste with oil separating before any rice goes on top.' },
    ],
    variants: [
      {
        id: 'biryani_gosht_lamb',
        label: 'Lamb biryani (gosht)',
        swaps: [
          { from: 'chicken_thigh', to: 'lamb_diced', grams: 450 },
        ],
        methodDeltas: [
          { step: 1, change: 'Lamb needs the acid: marinate for a minimum of 4 hours, overnight is better.' },
          { step: 5, change: 'Fifteen minutes will leave lamb tough. Cook it covered with 150 g added water for 50 to 60 minutes until a piece gives easily to a fork, then uncover and boil the liquid away until the fat separates.' },
          { step: 10, change: 'The meat is already tender, so the dum is only about the rice; keep it at 25 minutes and do not extend it.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'biryani_breast_lean',
        label: 'Leaner, with chicken breast',
        swaps: [
          { from: 'chicken_thigh', to: 'chicken_breast', grams: 420 },
        ],
        methodDeltas: [
          { step: 3, change: 'Drop the frying oil from 60 g to 40 g and drain the birista harder on kitchen paper; with no thigh fat rendering into the pot, the onions are the main fat and you want them crisp rather than oily. Check 75 C at the thickest point.' },
          { step: 5, change: 'Cut the initial cook from 15 minutes to 7. Breast that is fully cooked before the dum will be dry cotton by the time the rice is done.' },
          { step: 10, change: 'The breast finishes during the steam, so start timing the 25 minutes from the moment the pot is properly steaming rather than from when it goes on the heat.' },
        ],
        tags: ['halal'],
        note: 'Fry the onions in less oil and drain them harder; the birista is the main fat source in this version.',
      },
      {
        id: 'biryani_paneer',
        label: 'Paneer biryani (vegetarian)',
        swaps: [
          { from: 'chicken_thigh', to: 'paneer', grams: 300 },
        ],
        methodDeltas: [
          { step: 1, change: 'Marinate the paneer cubes for 20 minutes only. Left overnight in yogurt they go firm and squeaky.' },
          { step: 5, change: 'Fry the spices in the oil, add the marinade alone and cook it down for 6 minutes until thick, then fold the paneer in for the last minute so it never boils.' },
          { step: 10, change: 'Reduce the dum to 18 minutes. There is no meat to tenderise and paneer tightens with prolonged heat.' },
        ],
        tags: ['vegetarian'],
      },
      {
        id: 'biryani_vegan_soya',
        label: 'Vegan soya chunk biryani',
        swaps: [
          { from: 'chicken_thigh', to: 'soya_chunks', grams: 120 },
          { from: 'greek_yogurt', to: 'soya_yogurt', grams: 200 },
          { from: 'ghee', to: 'vegetable_oil', grams: 30 },
          { from: 'milk_semi', to: 'water', grams: 40 },
        ],
        methodDeltas: [
          { step: 1, change: 'Soak the dry soya chunks in boiling salted water for 15 minutes first, then squeeze them out hard like a sponge before marinating. Unsqueezed chunks flood the pot.' },
          { step: 4, change: 'Saffron infuses more weakly in water than in milk; steep it in hot water for a full 20 minutes and add a pinch of extra salt to the infusion.' },
          { step: 5, change: 'Soya yogurt is thinner and splits less predictably; cook the marinade down for 10 minutes rather than 15 and stir more often to stop it catching.' },
        ],
        tags: ['vegan', 'vegetarian', 'dairy_free'],
        note: 'Serve the raita made with soya yogurt as well.',
      },
    ],
    restaurantGBP: 12.95,
    tags: ['halal'],
  },

  // ==========================================================================
  // 3. SHAKSHUKA
  // ==========================================================================
  {
    id: 'shakshuka',
    name: 'Shakshuka',
    localName: 'شكشوكة',
    cuisine: 'North African and Levantine',
    country: 'TN',
    blurb: 'Eggs poached directly in a reduced pepper and tomato sauce spiced with cumin and smoked paprika, eaten straight from the pan with bread.',
    servings: 2,
    activeMin: 20,
    totalMin: 40,
    difficulty: 'easy',
    items: [
      { ref: 'olive_oil', grams: 30 },
      { ref: 'onion', grams: 150, note: 'halved and sliced' },
      { ref: 'red_pepper', grams: 160, note: 'deseeded and cut into 1 cm strips' },
      { ref: 'garlic', grams: 16, note: 'thinly sliced' },
      { ref: 'cumin_ground', grams: 4 },
      { ref: 'paprika_smoked', grams: 4 },
      { ref: 'chilli_powder', grams: 1, note: 'or more to taste' },
      { ref: 'tomato_puree', grams: 20 },
      { ref: 'tomato_tinned', grams: 400, note: 'whole plum tomatoes, crushed by hand' },
      { ref: 'sugar', grams: 4 },
      { ref: 'salt', grams: 5 },
      { ref: 'black_pepper', grams: 1, note: 'freshly ground' },
      { ref: 'egg', grams: 200, note: '4 medium eggs, cracked into separate cups first' },
      { ref: 'feta', grams: 60, note: 'crumbled over at the end', optional: true },
      { ref: 'harissa', grams: 15, note: 'stirred into the sauce for heat', optional: true },
      { ref: 'parsley_fresh', grams: 10, note: 'chopped' },
      { ref: 'coriander_fresh', grams: 8, note: 'chopped', optional: true },
      { ref: 'bread_sourdough', grams: 160, note: 'thick slices, toasted' },
    ],
    method: [
      {
        n: 1,
        text: 'Crack each egg into its own small cup or ramekin and set them by the hob. Chop everything else before you start cooking.',
        minutes: 5,
        tip: 'Cracking eggs directly into a hot pan means shell fragments and a broken yolk with no way to fix either. The cups take thirty seconds and remove both risks.',
      },
      {
        n: 2,
        text: 'Heat the olive oil in a 24 to 26 cm frying pan that has a lid, over medium heat. Add the onion and red pepper with a pinch of the salt and cook for 10 minutes, stirring now and then, until the pepper is limp and the onion is translucent and starting to colour at the edges.',
        minutes: 10,
      },
      {
        n: 3,
        text: 'Add the sliced garlic and cook for 1 minute more, keeping it moving.',
        minutes: 1,
      },
      {
        n: 4,
        text: 'Push the vegetables to one side, add the cumin, smoked paprika and chilli powder to the bare oil and stir them for 30 seconds before mixing them through.',
        minutes: 1,
        tip: 'Blooming the spices in oil rather than dropping them into wet tomato is the difference between a rounded sauce and a raw, dusty one. Thirty seconds is the whole window before paprika turns bitter.',
      },
      {
        n: 5,
        text: 'Stir in the tomato puree and fry it for 90 seconds until it darkens.',
        minutes: 2,
      },
      {
        n: 6,
        text: 'Crush the tinned tomatoes into the pan with your hand, add the sugar, the remaining salt, the black pepper and the harissa if using. Bring to a simmer.',
        minutes: 3,
      },
      {
        n: 7,
        text: 'Simmer uncovered over medium-low heat for 12 to 15 minutes, stirring occasionally, until the sauce is thick enough that a spoon dragged across the base leaves a channel that holds for a second or two.',
        minutes: 14,
        tip: 'Reduce it further than feels right. The eggs release a surprising amount of water as they poach, and a loose sauce ends up as tomato soup with eggs floating in it.',
      },
      {
        n: 8,
        text: 'Taste and correct: it should be sweet, sour and salty in roughly equal measure. Put the toast on now.',
        minutes: 2,
      },
      {
        n: 9,
        text: 'Use the back of a spoon to make four shallow wells in the sauce, spaced apart, each going almost to the base of the pan. Slide one egg into each well.',
        minutes: 2,
      },
      {
        n: 10,
        text: 'Season the yolks lightly, turn the heat to low, cover the pan and cook for 6 to 8 minutes.',
        minutes: 8,
        tip: 'Check at 6 minutes. The whites should be opaque all the way to the yolk with no clear jelly left, while the yolk still wobbles when you shake the pan. Past 9 minutes the yolks set solid and there is no going back.',
      },
      {
        n: 11,
        text: 'Take the pan off the heat, crumble over the feta and scatter the parsley and coriander. Bring the whole pan to the table with the toast and let people spoon it out themselves.',
        minutes: 2,
      },
    ],
    failures: [
      { symptom: 'Watery sauce pooling around the eggs', cause: 'The sauce was not reduced far enough before the eggs went in; lift the eggs out with a slotted spoon, boil the sauce hard for 3 minutes, then slide them back.' },
      { symptom: 'Yolks set hard before the whites cooked', cause: 'The heat was too high, so the base cooked before the steam did; lower the flame and rely on the lid, which sets the tops of the whites from above.' },
      { symptom: 'Sauce tastes dusty and bitter', cause: 'The paprika burned or was never bloomed; fry the ground spices in oil for 30 seconds only, off to one side of the pan.' },
      { symptom: 'Eggs slid together into one sheet', cause: 'The wells were too shallow and too close; press each well right down to the pan base with the back of a spoon and keep them a spoon-width apart.' },
    ],
    variants: [
      {
        id: 'shakshuka_vegan_tofu',
        label: 'Vegan, with crumbled tofu',
        swaps: [
          { from: 'egg', to: 'tofu_firm', grams: 250 },
          { from: 'feta', to: null },
        ],
        methodDeltas: [
          { step: 1, change: 'No eggs to portion; instead press the tofu for 15 minutes and crumble it into rough 2 cm pieces so it holds together in the sauce.' },
          { step: 9, change: 'There are no wells. Fold the crumbled tofu through the sauce, add 1 g turmeric for colour and 1 g extra salt, since tofu is bland where an egg yolk is rich.' },
          { step: 10, change: 'Cover and cook for 5 minutes only, just to heat the tofu through. There is nothing to set, and longer simmering makes the crumbles disintegrate.' },
        ],
        tags: ['vegan', 'vegetarian', 'dairy_free', 'halal'],
      },
      {
        id: 'shakshuka_kofta',
        label: 'With spiced beef mince',
        swaps: [
          { from: 'feta', to: 'beef_mince_5', grams: 200 },
        ],
        methodDeltas: [
          { step: 2, change: 'Brown the mince in the dry pan over high heat for 5 minutes first, breaking it up, then lift it out and cook the onion and pepper in the fat it leaves behind, using only 15 g of the olive oil.' },
          { step: 6, change: 'Return the browned mince with the tomatoes and add 2 g allspice or baharat with the other spices.' },
          { step: 7, change: 'The mince adds fat and liquid; simmer for 18 minutes rather than 14 and skim any pooled fat before making the wells.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'shakshuka_green',
        label: 'Green shakshuka',
        swaps: [
          { from: 'tomato_tinned', to: 'spinach_fresh', grams: 300 },
          { from: 'red_pepper', to: 'courgette', grams: 200 },
          { from: 'paprika_smoked', to: 'lemon', grams: 20 },
        ],
        methodDeltas: [
          { step: 2, change: 'Courgette holds far more water than pepper; cook it over medium-high heat for 8 minutes until it colours and stops steaming, or the finished pan will be soupy.' },
          { step: 6, change: 'There is no tomato to build a sauce, so add 120 g water with the spinach and wilt it in two handfuls over 3 minutes.' },
          { step: 7, change: 'Reduce for 5 minutes only, to a loose green base rather than a thick sauce, and finish with the lemon juice off the heat.' },
          { step: 9, change: 'The base is thinner, so make the wells by pushing the greens aside right down to the metal, and add the eggs one at a time so the base does not flood back over them.' },
        ],
        tags: ['vegetarian', 'halal', 'nut_free'],
      },
      {
        id: 'shakshuka_chickpea',
        label: 'Higher protein, with chickpeas',
        swaps: [
          { from: 'bread_sourdough', to: 'chickpeas_tinned', grams: 240 },
        ],
        methodDeltas: [
          { step: 6, change: 'Add the drained chickpeas with the tomatoes so they have time to absorb the sauce and soften.' },
          { step: 7, change: 'Chickpeas soak up liquid as they simmer; add 80 g water and extend the reduction to 18 minutes, checking that the base does not catch.' },
          { step: 11, change: 'Without bread you need something to carry it, so crush a few chickpeas against the side of the pan to thicken the sauce into something spoonable.' },
        ],
        tags: ['vegetarian', 'halal', 'gluten_free', 'nut_free'],
        note: 'Roughly 12 g more protein per portion and no wheat, at the cost of the bread.',
      },
    ],
    restaurantGBP: 10.50,
    tags: ['vegetarian', 'halal', 'nut_free'],
  },

  // ==========================================================================
  // 4. PAD THAI
  // ==========================================================================
  {
    id: 'pad_thai',
    name: 'Pad Thai',
    localName: 'ผัดไทย',
    cuisine: 'Thai',
    country: 'TH',
    blurb: 'Soaked rice noodles tossed in a tamarind, fish sauce and palm sugar reduction with prawns, tofu and egg, finished with peanuts, beansprouts and lime.',
    servings: 2,
    activeMin: 25,
    totalMin: 55,
    difficulty: 'medium',
    items: [
      { ref: 'rice_noodles', grams: 160, note: 'flat 5 mm, dry weight' },
      { ref: 'tamarind_paste', grams: 40, note: 'the sour concentrate, not sweetened sauce' },
      { ref: 'fish_sauce', grams: 35 },
      { ref: 'brown_sugar', grams: 40, note: 'palm sugar if you have it' },
      { ref: 'water', grams: 30, note: 'to loosen the sauce' },
      { ref: 'prawns_raw', grams: 200, note: 'peeled and deveined, patted dry' },
      { ref: 'tofu_firm', grams: 100, note: 'pressed and cut into 1 cm cubes' },
      { ref: 'egg', grams: 100, note: '2 eggs, beaten' },
      { ref: 'garlic', grams: 12, note: 'finely chopped' },
      { ref: 'vegetable_oil', grams: 30 },
      { ref: 'spring_onion', grams: 40, note: 'cut into 4 cm lengths' },
      { ref: 'beansprouts', grams: 120, note: 'half in the wok, half raw on top' },
      { ref: 'peanuts', grams: 30, note: 'roasted, roughly crushed' },
      { ref: 'lime', grams: 50, note: 'cut into wedges' },
      { ref: 'chilli_powder', grams: 2, note: 'at the table', optional: true },
      { ref: 'coriander_fresh', grams: 6, note: 'to finish', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'Soak the dry rice noodles in warm tap water, not boiling, for 30 to 40 minutes until they are pliable and bend easily around your finger but still snap if you bite one. Drain them well.',
        minutes: 40,
        tip: 'Boiling water is the classic mistake here. It cooks the noodles through before they reach the wok and they collapse into paste the moment sauce hits them.',
      },
      {
        n: 2,
        text: 'Make the sauce: warm the tamarind paste, fish sauce, brown sugar and water in a small pan over low heat, stirring, for 3 minutes until the sugar has fully dissolved. Taste it. It should be aggressively sour, salty and sweet, in that order, and far too strong to drink.',
        minutes: 4,
        tip: 'Correct the balance now, not in the wok. Once the noodles are in there is no time to taste and adjust, and the noodles will dilute whatever you made by about half.',
      },
      {
        n: 3,
        text: 'Line everything up next to the hob in the order you will use it: garlic, tofu, prawns, drained noodles, sauce, beaten egg, beansprouts, spring onion, peanuts.',
        minutes: 5,
        tip: 'This is the step people skip and it is the one that decides the dish. Once the wok is hot the whole stir-fry takes under five minutes and there is no pause to go and chop something. If it is not on the counter before the pan goes on, it will not make it in.',
      },
      {
        n: 4,
        text: 'Heat a wok or your widest frying pan over the highest heat until a drop of water skitters and evaporates instantly. Add the oil and swirl it round.',
        minutes: 3,
      },
      {
        n: 5,
        text: 'Add the tofu cubes and fry for 2 minutes without moving them, then toss and fry 1 minute more until the edges are golden. Push them up the side of the wok.',
        minutes: 3,
      },
      {
        n: 6,
        text: 'Add the garlic to the centre and stir for 15 seconds, then add the prawns in a single layer and cook for 1 minute per side until just opaque. Push them up the side with the tofu.',
        minutes: 2,
        tip: 'Pull the prawns as soon as they turn from grey to white with pink edges. They will get another minute of heat when everything comes back together at the end.',
      },
      {
        n: 7,
        text: 'Drop the drained noodles into the centre of the wok and pour the sauce over them. Toss constantly with tongs for 2 to 3 minutes until the noodles have drunk the sauce and turned an even amber brown.',
        minutes: 3,
        tip: 'If the noodles seize up and stick in a clump, add water one tablespoon at a time and keep tossing. Adding more oil at this point only makes them greasy without unsticking them.',
      },
      {
        n: 8,
        text: 'Push everything to one side, pour the beaten egg into the bare base, let it sit undisturbed for 20 seconds until the underside sets, then chop through it with your spatula and fold it into the noodles in large curds.',
        minutes: 2,
      },
      {
        n: 9,
        text: 'Add half the beansprouts and all the spring onion, and toss for 45 seconds only.',
        minutes: 1,
        tip: 'Beansprouts are there for the snap. Anything past a minute in the wok and they go limp and start weeping water into the noodles.',
      },
      {
        n: 10,
        text: 'Fold the tofu and prawns back through, add half the crushed peanuts and take the wok off the heat.',
        minutes: 1,
      },
      {
        n: 11,
        text: 'Taste one noodle. If it is flat, add fish sauce; if it is cloying, squeeze in lime; if it is harsh, a pinch of sugar. Adjust in the pan.',
        minutes: 1,
      },
      {
        n: 12,
        text: 'Pile onto two warm plates, top with the remaining raw beansprouts, the rest of the peanuts and the coriander, and serve with lime wedges and chilli powder on the side.',
        minutes: 2,
      },
    ],
    failures: [
      { symptom: 'Noodles turned to a sticky paste', cause: 'They were soaked in boiling water or soaked too long; use warm water and stop while they still have a firm bite, since they finish cooking in the sauce.' },
      { symptom: 'Everything clumped into one solid mass', cause: 'The pan was not hot enough and the noodles stewed; get the pan properly smoking, cook in one batch of two portions maximum, and loosen with splashes of water rather than oil.' },
      { symptom: 'Pale and bland instead of amber and sharp', cause: 'The sauce was underseasoned before it went in; it must taste too strong on its own, because the noodles dilute it heavily.' },
      { symptom: 'Prawns are rubbery', cause: 'They were left in the wok for the whole stir-fry; cook them for 2 minutes, remove them to the side of the pan, and fold them back only at the very end.' },
      { symptom: 'Egg scrambled into tiny dry specks', cause: 'It was poured over the noodles and stirred immediately; clear a space to the bare pan, let it set for 20 seconds, then break it up.' },
    ],
    variants: [
      {
        id: 'pad_thai_gai',
        label: 'Pad thai gai (chicken)',
        swaps: [
          { from: 'prawns_raw', to: 'chicken_breast', grams: 250 },
        ],
        methodDeltas: [
          { step: 3, change: 'Slice the breast across the grain into 5 mm strips as part of your prep; thick chunks will not cook through in wok time.' },
          { step: 6, change: 'Chicken needs longer than prawns: fry the strips for 3 to 4 minutes total, spread out and barely stirred so they catch colour, until no pink remains and the centre reaches 74 C.' },
          { step: 10, change: 'The chicken is already cooked through, so fold it back in off the heat to stop it drying out.' },
        ],
        tags: ['dairy_free', 'halal'],
      },
      {
        id: 'pad_thai_jay',
        label: 'Pad thai jay (vegan)',
        swaps: [
          { from: 'prawns_raw', to: 'tofu_firm', grams: 250 },
          { from: 'fish_sauce', to: 'soy_sauce', grams: 35 },
          { from: 'egg', to: null },
        ],
        methodDeltas: [
          { step: 2, change: 'Soy sauce is saltier and less funky than fish sauce; use 30 g rather than 35 g and add 5 g extra tamarind to put back the sourness you lose.' },
          { step: 5, change: 'With all 350 g of tofu in one wok, fry it in two batches or it will steam instead of browning, and press it for a full 30 minutes first so it holds its shape.' },
          { step: 8, change: 'No egg step. Skip straight from the noodles to the beansprouts, but toss the noodles for an extra 30 seconds first since the egg was part of what bound them.' },
        ],
        tags: ['vegan', 'vegetarian', 'dairy_free'],
      },
      {
        id: 'pad_thai_lean',
        label: 'Leaner, higher protein, less sugar',
        swaps: [
          { from: 'tofu_firm', to: 'chicken_breast', grams: 200 },
          { from: 'brown_sugar', to: 'honey', grams: 22 },
        ],
        methodDeltas: [
          { step: 2, change: 'Honey dissolves instantly but scorches easily; take the sauce off the heat before you stir it in rather than simmering it. With almost half the sugar the sauce will taste sharper, so pull back to 30 g fish sauce to keep it balanced.' },
          { step: 5, change: 'Replace the tofu step with the sliced chicken breast: 3 to 4 minutes over high heat, spread flat, until no pink remains and the centre reaches 74 C. Then out to the side of the wok.' },
          { step: 7, change: 'Cut the oil from 30 g to 18 g. Less oil and less sugar means less non-stick coating on the noodles, so expect to add 40 to 50 g water in splashes while tossing and keep the tongs moving constantly.' },
        ],
        tags: ['dairy_free', 'halal'],
        note: 'Around 45 g protein per portion instead of 30 g, and roughly 9 g less sugar.',
      },
    ],
    restaurantGBP: 11.50,
    tags: ['dairy_free'],
  },

  // ==========================================================================
  // 5. SWEDISH MEATBALLS
  // ==========================================================================
  {
    id: 'swedish_meatballs',
    name: 'Swedish Meatballs with Cream Sauce',
    localName: 'Köttbullar med gräddsås',
    cuisine: 'Swedish',
    country: 'SE',
    blurb: 'Small allspice and nutmeg seasoned beef meatballs bound with milk-soaked breadcrumbs, served with a pan gravy, mashed potato and lingonberry jam.',
    servings: 2,
    activeMin: 45,
    totalMin: 60,
    difficulty: 'easy-medium',
    items: [
      { ref: 'beef_mince_5', grams: 400, note: 'take it out of the fridge 10 min before mixing' },
      { ref: 'breadcrumbs', grams: 40, note: 'fine dry crumbs' },
      { ref: 'milk_semi', grams: 200, note: '70 g to soak the breadcrumbs, 130 g warmed for the mash' },
      { ref: 'onion', grams: 100, note: 'grated on the coarse side of a box grater' },
      { ref: 'egg', grams: 50, note: '1 egg, beaten' },
      { ref: 'allspice_ground', grams: 2 },
      { ref: 'nutmeg', grams: 1, note: 'freshly grated if possible' },
      { ref: 'white_pepper', grams: 1 },
      { ref: 'salt', grams: 7, absorption: 0.62, note: '4 g in the meatballs, 3 g for the potato water' },
      { ref: 'butter', grams: 70, note: '30 g for frying, 15 g for the roux, 25 g for the mash' },
      { ref: 'vegetable_oil', grams: 15, note: 'stops the butter burning' },
      { ref: 'plain_flour', grams: 25 },
      { ref: 'stock_cube_beef', grams: 7, note: 'crumbled — a 10 g cube is made for 500 ml, and this gravy is 350' },
      { ref: 'water', grams: 350, note: 'hot, for the gravy' },
      { ref: 'double_cream', grams: 120 },
      { ref: 'dijon_mustard', grams: 8 },
      { ref: 'soy_sauce', grams: 3, note: 'for colour and depth in the gravy — it is salty, so this is deliberately small' },
      { ref: 'potato', grams: 500, note: 'floury, peeled and cut into even 4 cm chunks' },
      { ref: 'lingonberry_jam', grams: 40, note: 'served alongside, not on top' },
      { ref: 'cucumber', grams: 60, note: 'sliced thin and steeped in vinegar and sugar', optional: true },
      { ref: 'vinegar_white', grams: 20, note: 'for the quick pickled cucumber', optional: true },
      { ref: 'sugar', grams: 10, note: 'for the quick pickled cucumber', optional: true },
      { ref: 'parsley_fresh', grams: 6, note: 'chopped, to finish', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'If you are making the pickled cucumber, do it first: mix the vinegar, sugar and a pinch of salt until dissolved, add the sliced cucumber and leave it in the fridge.',
        minutes: 5,
      },
      {
        n: 2,
        text: 'Put the breadcrumbs in a large bowl with 70 g of the milk and leave them for 10 minutes until the crumbs have swollen into a wet paste with no dry pockets.',
        minutes: 10,
        tip: 'This soaked paste, a panade, is what keeps the meatballs soft. Dry breadcrumbs stirred straight into mince pull moisture out and give you dense little bullets.',
      },
      {
        n: 3,
        text: 'Squeeze the grated onion in your fist over the sink to get rid of the juice, then add it to the bowl with the egg, allspice, nutmeg, white pepper and 6 g salt. Mix to a smooth paste.',
        minutes: 4,
      },
      {
        n: 4,
        text: 'Add the mince and mix with your hands for about 45 seconds, just until no streaks of plain meat remain. Stop there.',
        minutes: 2,
        tip: 'Overworking is the main failure. Keep going past a minute and the proteins tighten into something closer to a sausage than a meatball, springy and rubbery when cooked.',
      },
      {
        n: 5,
        text: 'Wet your hands with cold water and roll the mixture into 20 balls about 30 mm across. Put them on a plate and chill them in the fridge for 15 minutes while you start the potatoes.',
        minutes: 18,
        tip: 'Chilling firms the fat so the balls hold their shape and do not slump into ovals in the pan.',
      },
      {
        n: 6,
        text: 'Put the potato chunks into cold salted water, bring to a boil and simmer for 18 to 20 minutes until a knife slides in with no resistance at all.',
        minutes: 20,
      },
      {
        n: 7,
        text: 'Heat 30 g butter and the oil in a large frying pan over medium heat until the foam subsides. Fry the meatballs in two batches, turning them every minute or so with a spoon, for 8 to 10 minutes per batch until browned all over and 71 C at the centre. Lift them onto a warm plate.',
        minutes: 20,
        tip: 'Roll them around rather than flipping them once. You want an even shell of colour on a sphere, and the browning left in the pan is the entire flavour base for the gravy.',
      },
      {
        n: 8,
        text: 'Drain the potatoes and let them steam dry in the colander for 2 minutes, then mash them with 25 g butter and the 130 g warmed milk. Season and keep warm.',
        minutes: 6,
        tip: 'Warm the milk first. Cold milk in hot potato gives you a gluey mash, and a masher beats a food processor every time, which turns potato into wallpaper paste.',
      },
      {
        n: 9,
        text: 'Pour off all but about 2 tablespoons of fat from the meatball pan, keeping the browned residue. Add the remaining 15 g butter and the flour and stir over medium heat for 2 minutes until it smells like biscuits and turns light brown.',
        minutes: 3,
        tip: 'Cook the flour properly. Two minutes is the difference between a savoury gravy and one that tastes of raw paste no matter what you add later.',
      },
      {
        n: 10,
        text: 'Crumble the stock cube into 350 g hot water and pour it into the pan a third at a time, whisking each addition to a smooth paste before the next goes in. Scrape the base as you whisk.',
        minutes: 4,
        tip: 'Adding all the liquid at once is what makes lumps. If it does go lumpy, push the gravy through a sieve rather than whisking harder.',
      },
      {
        n: 11,
        text: 'Stir in the cream, mustard and soy sauce and simmer gently for 5 minutes until the gravy coats the back of a spoon.',
        minutes: 5,
      },
      {
        n: 12,
        text: 'Return the meatballs and any juices to the pan and turn them in the gravy over low heat for 3 minutes to warm through.',
        minutes: 3,
        tip: 'Keep it just below a simmer. A hard boil with cream and mustard in the pan will split the gravy into fat and grains.',
      },
      {
        n: 13,
        text: 'Taste the gravy for salt, scatter with parsley and serve with the mash, a spoonful of lingonberry jam on the side of the plate and the pickled cucumber.',
        minutes: 3,
      },
    ],
    failures: [
      { symptom: 'Meatballs are dense and bouncy', cause: 'The mince was overmixed or the breadcrumbs went in dry; mix for 45 seconds only and always soak the crumbs in milk first.' },
      { symptom: 'Meatballs fell apart in the pan', cause: 'The mixture was too wet or was not chilled; squeeze the grated onion dry, chill the rolled balls 15 minutes, and do not move them for the first minute in the pan.' },
      { symptom: 'Gravy is lumpy', cause: 'The stock went in all at once; add it in thirds, whisking each to a smooth paste, or press the finished gravy through a sieve.' },
      { symptom: 'Gravy split into grease and grains', cause: 'It boiled hard after the cream went in; keep it at a bare simmer and take the pan off the heat before whisking in a splash of cold stock to bring it back.' },
      { symptom: 'Mash is gluey', cause: 'Cold milk or a food processor; steam the potatoes dry, use warmed milk, and mash by hand.' },
    ],
    variants: [
      {
        id: 'kottbullar_chicken',
        label: 'Chicken thigh meatballs',
        swaps: [
          { from: 'beef_mince_5', to: 'chicken_thigh', grams: 400 },
          { from: 'stock_cube_beef', to: 'stock_cube_chicken', grams: 10 },
        ],
        methodDeltas: [
          { step: 4, change: 'Pulse the diced thigh in a food processor to a coarse mince in short bursts, then chill it for 20 minutes before mixing. Warm chicken mince smears into a paste.' },
          { step: 5, change: 'The mixture is much stickier than beef; keep rewetting your hands and expect the balls to be slightly softer.' },
          { step: 7, change: 'Chicken must reach 74 C rather than 71 C, but it browns faster, so drop the heat to medium-low and give it 10 to 12 minutes per batch.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'kottbullar_lean',
        label: 'Lighter gravy, with peas',
        swaps: [
          { from: 'double_cream', to: 'single_cream', grams: 120 },
          { from: 'cucumber', to: 'peas_frozen', grams: 150 },
        ],
        methodDeltas: [
          { step: 7, change: 'Drop the total butter from 70 g to 45 g: fry the meatballs in 15 g butter plus the oil, keep 15 g back for the roux and 15 g for the mash.' },
          { step: 8, change: 'With only 15 g butter left for the mash, add 30 g more of the warmed milk so it stays loose enough to spoon.' },
          { step: 11, change: 'Single cream is thinner and much more likely to split; add it off the heat at the end rather than simmering it for 5 minutes, and thicken instead with an extra 5 g flour at step 9.' },
          { step: 13, change: 'Boil the peas for 3 minutes in the potato water just before you drain it, and serve them alongside in place of the pickled cucumber.' },
        ],
        tags: ['halal'],
        note: 'Around 12 g less fat per portion, with fibre from the peas.',
      },
      {
        id: 'kottbullar_gf',
        label: 'Gluten free',
        swaps: [
          { from: 'breadcrumbs', to: 'cornflour', grams: 20 },
          { from: 'plain_flour', to: 'cornflour', grams: 15 },
          { from: 'soy_sauce', to: null },
        ],
        methodDeltas: [
          { step: 2, change: 'Cornflour cannot be soaked into a panade. Instead whisk the 20 g cornflour into the 70 g milk cold and heat it in a small pan for 1 minute until it thickens into a paste, then cool it before mixing with the meat.' },
          { step: 9, change: 'Do not make a roux with cornflour, it will go stringy. Melt the butter, add the stock, and thicken at the end by slurrying the 15 g cornflour with 30 g cold water and whisking it into the simmering gravy.' },
          { step: 11, change: 'Without soy sauce the gravy is pale; add 3 g extra dijon and a pinch of salt, and let the meatball browning do the colour work by scraping the pan base thoroughly.' },
        ],
        tags: ['gluten_free', 'halal'],
      },
      {
        id: 'kottbullar_vegan',
        label: 'Vegan, with soya chunks',
        swaps: [
          { from: 'beef_mince_5', to: 'soya_chunks', grams: 130 },
          { from: 'egg', to: null },
          { from: 'milk_semi', to: 'water', grams: 200 },
          { from: 'butter', to: 'vegetable_oil', grams: 55 },
          { from: 'double_cream', to: 'coconut_cream', grams: 120 },
          { from: 'stock_cube_beef', to: 'stock_cube_veg', grams: 10 },
        ],
        methodDeltas: [
          { step: 2, change: 'Rehydrate the soya chunks in boiling stock for 15 minutes, squeeze them dry hard, then blitz them coarsely. Soak the breadcrumbs in water rather than milk.' },
          { step: 4, change: 'With no egg and no meat protein there is nothing binding the mix; add 15 g cornflour and knead for a full 2 minutes, which is the opposite of the beef instruction, until it holds together when squeezed.' },
          { step: 7, change: 'These will not brown from rendered fat. Fry them in a generous film of oil over medium-high heat for 6 minutes, turning carefully with two spoons, and handle them less because they are more fragile.' },
          { step: 11, change: 'Coconut cream carries its own flavour; add 5 g extra dijon and 10 g lemon juice to cut it, and check the salt twice since the vegetable stock is milder than beef.' },
        ],
        tags: ['vegan', 'vegetarian', 'dairy_free'],
      },
    ],
    restaurantGBP: 13.00,
    tags: ['halal'],
  },

  // ==========================================================================
  // 6. MACHBOOS DAJAJ
  // ==========================================================================
  {
    id: 'machboos_dajaj',
    name: 'Machboos Dajaj',
    localName: 'مكبوس دجاج',
    cuisine: 'Khaleeji (Gulf)',
    country: 'KW',
    blurb: 'Chicken braised with baharat and dried limes, then the rice cooked in that same broth in one pot, served with a raw tomato and coriander daqoos.',
    servings: 2,
    activeMin: 35,
    totalMin: 95,
    difficulty: 'medium',
    items: [
      { ref: 'chicken_thigh', grams: 500, note: 'bone-in if possible, skin on, cut into large pieces' },
      { ref: 'basmati_rice', grams: 250, note: 'rinsed and soaked 20 min' },
      { ref: 'onion', grams: 200, note: 'finely chopped' },
      { ref: 'garlic', grams: 16, note: 'crushed' },
      { ref: 'ginger', grams: 15, note: 'grated' },
      { ref: 'green_chilli', grams: 10, note: 'slit', optional: true },
      { ref: 'tomato_fresh', grams: 300, note: '150 g grated into the pot, 150 g for the daqoos' },
      { ref: 'tomato_puree', grams: 20 },
      { ref: 'baharat', grams: 8, note: 'Gulf seven-spice' },
      { ref: 'turmeric', grams: 3 },
      { ref: 'cinnamon_ground', grams: 2 },
      { ref: 'cardamom_green', grams: 3, note: 'pods, cracked' },
      { ref: 'cloves_whole', grams: 1 },
      { ref: 'bay_leaf', grams: 1 },
      { ref: 'loomi_dried_lime', grams: 12, note: '2 dried limes, pierced twice with a knife' },
      { ref: 'saffron', grams: 0.1, note: 'steeped in 2 tbsp hot water', optional: true },
      { ref: 'stock_cube_chicken', grams: 6, note: 'half a cube — the dish is already seasoned with salt and loomi' },
      { ref: 'water', grams: 800, note: 'for the braise and then the rice' },
      { ref: 'ghee', grams: 40 },
      { ref: 'vegetable_oil', grams: 20 },
      { ref: 'salt', grams: 7, note: 'the stock cube brings its own — taste before adding the last of it' },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'lemon', grams: 20, note: 'juice, for the daqoos' },
      { ref: 'coriander_fresh', grams: 12, note: 'chopped; half for the daqoos, half to finish' },
      { ref: 'parsley_fresh', grams: 8, note: 'chopped', optional: true },
      { ref: 'almonds', grams: 20, note: 'flaked and toasted, scattered over', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'Rinse the basmati until the water runs clear, then leave it to soak in cold water for 20 minutes and drain it.',
        minutes: 22,
      },
      {
        n: 2,
        text: 'Pat the chicken completely dry and season it with 4 g of the salt and the black pepper. Heat the vegetable oil and half the ghee in a heavy lidded casserole over medium-high heat and brown the chicken skin side down for 5 minutes, then 3 minutes on the other side. Lift it out.',
        minutes: 10,
        tip: 'Dry skin and a hot pan, and then do not touch it. If the chicken sticks when you try to turn it, it is not ready; it releases itself when the crust has formed.',
      },
      {
        n: 3,
        text: 'Turn the heat to medium and cook the onion in the same fat for 10 minutes until soft and deeply golden, scraping up the browned bits from the base.',
        minutes: 10,
      },
      {
        n: 4,
        text: 'Add the garlic, ginger and green chilli and stir for 1 minute, then add the baharat, turmeric, cinnamon, cardamom, cloves and bay leaf and stir for a further 45 seconds.',
        minutes: 2,
        tip: 'The spices should smell warm and toasted, not sharp and powdery. If the pan is dry enough that they start to catch, add a splash of water rather than more heat.',
      },
      {
        n: 5,
        text: 'Add the tomato puree and 150 g of the tomato, grated on a box grater so the skin stays in your hand. Cook for 5 minutes until the mixture darkens and thickens.',
        minutes: 5,
      },
      {
        n: 6,
        text: 'Return the chicken with its juices, add the pierced dried limes, the crumbled stock cube, 4 g more salt and 700 g water. Bring to a boil, then cover and simmer over low heat for 30 minutes.',
        minutes: 33,
        tip: 'Pierce the loomi but leave them whole. Broken open they release a bitterness that takes over the whole pot; whole and pierced, they give the sour, slightly smoky note the dish is built on.',
      },
      {
        n: 7,
        text: 'Lift out the chicken and the dried limes onto a plate. Measure the broth left in the pot: you want 480 g of liquid for 250 g of soaked rice. Top up with water or boil it down as needed.',
        minutes: 5,
        tip: 'This measurement is the whole dish. Too much broth and you get a wet risotto; too little and the top layer stays hard. Use a jug, not judgement.',
      },
      {
        n: 8,
        text: 'Return the measured broth to the pot, taste it and correct the salt so it is slightly saltier than you would want a soup. Bring it to a rolling boil, stir in the drained rice and let it boil uncovered until the liquid has dropped to the level of the rice and craters appear on the surface, about 5 minutes.',
        minutes: 6,
        tip: 'Season the broth now. This is the last moment the rice can take on salt, and rice seasoned afterwards always tastes of salt sitting on top rather than through it.',
      },
      {
        n: 9,
        text: 'Sit the chicken pieces and the dried limes back on top of the rice, trickle over the saffron water and the remaining ghee, cover with a tight lid and cook on the lowest heat for 20 minutes. The chicken must reach 75 C at the thickest point.',
        minutes: 20,
        tip: 'If your lid is loose, lay a clean tea towel between the pot and the lid to trap the steam and catch the condensation that would otherwise drip back and make the top wet.',
      },
      {
        n: 10,
        text: 'While it steams, make the daqoos: grate or finely chop the remaining 150 g tomato and mix it with the lemon juice, half the coriander, a crushed clove of the garlic if you saved some, and a pinch of salt.',
        minutes: 5,
      },
      {
        n: 11,
        text: 'Take the pot off the heat and leave it covered for 10 minutes without opening it.',
        minutes: 10,
      },
      {
        n: 12,
        text: 'Lift the chicken aside, fluff the rice with a fork from the edges inwards, then pile it onto a platter with the chicken on top, scattered with the remaining coriander, the parsley and the toasted almonds. Serve the daqoos in a bowl alongside.',
        minutes: 4,
      },
    ],
    failures: [
      { symptom: 'Rice is wet and claggy at the bottom', cause: 'The broth was not measured at step 7; drain to exactly 480 g for 250 g of soaked rice, and boil off any excess before the rice goes in.' },
      { symptom: 'Whole dish tastes bitter', cause: 'A dried lime split open, or the spices scorched at step 4; pierce the loomi rather than crushing them, and add a splash of water if the spice paste starts to catch.' },
      { symptom: 'Rice tastes of nothing while the chicken is well seasoned', cause: 'The broth was underseasoned before the rice went in; it should taste slightly too salty on its own at step 8.' },
      { symptom: 'Chicken is dry by the time the rice is done', cause: 'Boneless breast or a hard boil during the braise; use bone-in thigh and keep the simmer gentle, and set the chicken on top of the rice rather than buried in it.' },
      { symptom: 'Rice is hard on top and burnt underneath', cause: 'The heat was too high during the covered stage; use the lowest possible flame, a heat diffuser if you have one, and let it rest sealed for the full 10 minutes.' },
    ],
    variants: [
      {
        id: 'machboos_laham',
        label: 'Machboos laham (lamb)',
        swaps: [
          { from: 'chicken_thigh', to: 'lamb_diced', grams: 500 },
          { from: 'stock_cube_chicken', to: 'stock_cube_beef', grams: 10 },
        ],
        methodDeltas: [
          { step: 2, change: 'Brown the lamb in three small batches over high heat; crowded lamb releases water and greys instead of crusting.' },
          { step: 6, change: 'Thirty minutes is nowhere near enough for lamb. Simmer covered for 70 to 80 minutes with an extra 200 g water until a cube crushes against the side of the pot.' },
          { step: 7, change: 'The longer braise leaves a fattier broth; skim the surface fat off before measuring the 480 g, or the rice turns greasy.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'machboos_samak',
        label: 'Machboos samak (fish)',
        swaps: [
          { from: 'chicken_thigh', to: 'white_fish', grams: 400 },
          { from: 'stock_cube_chicken', to: 'stock_cube_veg', grams: 10 },
        ],
        methodDeltas: [
          { step: 2, change: 'Dust the fillets in turmeric and salt and fry them for 2 minutes per side purely to firm the surface, then set them aside on a plate and keep them out of the pot entirely for now.' },
          { step: 6, change: 'There is no meat to braise. Simmer the spiced onion base with the water, stock and dried limes for 15 minutes to build a broth, then measure it as usual.' },
          { step: 9, change: 'Lay the fish on the rice only for the last 8 minutes of the covered stage, not the full 20, and do not stir it in; white fish flakes apart into nothing if it steams for longer.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'machboos_breast_lean',
        label: 'Leaner, with chicken breast',
        swaps: [
          { from: 'chicken_thigh', to: 'chicken_breast', grams: 450 },
        ],
        methodDeltas: [
          { step: 2, change: 'Skinless breast has no fat to render; brown it for 2 minutes per side only, in oil alone, purely for colour. Halve the ghee to 20 g and save all of it for step 9. Check 75 C at the thickest point.' },
          { step: 6, change: 'Simmer for 12 minutes instead of 30, then take the breast out immediately. It will finish during the rice stage and would be shredded dry after half an hour.' },
          { step: 9, change: 'Return the breast for the last 10 minutes of the covered cook rather than the full 20, sitting on top of the rice where it only steams.' },
        ],
        tags: ['halal'],
      },
      {
        id: 'machboos_vegan',
        label: 'Vegan, with chickpeas',
        swaps: [
          { from: 'chicken_thigh', to: 'chickpeas_tinned', grams: 400 },
          { from: 'ghee', to: 'vegetable_oil', grams: 40 },
          { from: 'stock_cube_chicken', to: 'stock_cube_veg', grams: 10 },
        ],
        methodDeltas: [
          { step: 2, change: 'Nothing to brown; skip straight to the onions, but give them 14 minutes rather than 10 and let them catch properly, since the browning that the chicken skin was providing now has to come from the onion.' },
          { step: 6, change: 'Simmer the broth with the dried limes for 20 minutes to build flavour, then add the drained chickpeas for the last 5 minutes only so they do not collapse.' },
          { step: 9, change: 'Scatter the chickpeas over the rice before the covered stage and add 15 g more oil, because there is no rendered fat coating the grains.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal'],
      },
    ],
    restaurantGBP: 12.50,
    tags: ['halal'],
  },

  // ==========================================================================
  // 7. SPAGHETTI CARBONARA
  // ==========================================================================
  {
    id: 'spaghetti_carbonara',
    name: 'Spaghetti alla Carbonara',
    localName: 'Spaghetti alla Carbonara',
    cuisine: 'Roman Italian',
    country: 'IT',
    blurb: 'Spaghetti bound in an emulsion of egg, pecorino and starchy pasta water made off the heat, with crisp guanciale and cracked black pepper. No cream.',
    servings: 2,
    activeMin: 20,
    totalMin: 25,
    difficulty: 'medium',
    items: [
      { ref: 'spaghetti', grams: 200 },
      { ref: 'guanciale', grams: 120, note: 'rind removed, cut into 5 mm thick strips' },
      { ref: 'egg', grams: 136, note: '2 whole eggs plus 2 extra yolks, at room temperature' },
      { ref: 'pecorino', grams: 60, note: 'Pecorino Romano, grated as finely as you can' },
      { ref: 'parmesan', grams: 20, note: 'grated, to soften the sharpness', optional: true },
      { ref: 'black_pepper', grams: 3, note: 'coarsely cracked, not fine ground' },
      { ref: 'salt', grams: 10, absorption: 0.1, note: 'for the pasta water only — almost all of it is drained away' },
      { ref: 'water', grams: 2000, note: 'reserve 200 g of the cooking water before draining' },
      { ref: 'olive_oil', grams: 5, note: 'only if the guanciale is unusually lean', optional: true },
    ],
    method: [
      {
        n: 1,
        text: 'Put 2 litres of water on to boil with the salt. Use less water than you would normally: the more concentrated the starch, the better the sauce binds.',
        minutes: 8,
        tip: 'Season the water lightly, around 5 g of salt per litre. Guanciale and pecorino are both very salty and there is no other stage where you can take salt out.',
      },
      {
        n: 2,
        text: 'Put the guanciale into a cold, dry frying pan and set it over medium-low heat. Let it render slowly for 8 to 10 minutes, stirring occasionally, until the fat has run out and the strips are golden and crisp at the edges but still yielding in the middle.',
        minutes: 10,
        tip: 'Cold pan, low heat. Guanciale dropped into a hot pan seizes, burns on the outside and leaves its fat locked inside, and that rendered fat is a third of the sauce.',
      },
      {
        n: 3,
        text: 'Take the pan off the heat. Lift out about a third of the crisp pieces onto a plate for the top, and leave the rest sitting in the fat.',
        minutes: 1,
      },
      {
        n: 4,
        text: 'Toast the cracked black pepper in a small dry pan over medium heat for 30 seconds until it smells sharp and floral, then tip it into the guanciale fat.',
        minutes: 1,
      },
      {
        n: 5,
        text: 'Cook the spaghetti in the boiling water for 1 minute less than the packet says, so it still has a definite bite.',
        minutes: 9,
      },
      {
        n: 6,
        text: 'While the pasta cooks, whisk the whole eggs and extra yolks in a large bowl with the pecorino and parmesan until you have a thick, smooth paste with no streaks of white. It should look like a loose cheese custard.',
        minutes: 3,
        tip: 'Whisk until the cheese has fully disappeared into the egg. Any dry pockets of pecorino will clump the moment they hit heat and you will get grit through the sauce.',
      },
      {
        n: 7,
        text: 'Scoop out 200 g of the starchy cooking water into a mug before you drain the pasta.',
        minutes: 1,
        tip: 'Almost everyone forgets this and drains it all away. That cloudy water is the only thing that will hold the emulsion together.',
      },
      {
        n: 8,
        text: 'Temper the eggs: whisking the egg and cheese mixture constantly with one hand, trickle in about 60 g of the hot pasta water with the other. The mixture will loosen and turn glossy and pourable.',
        minutes: 2,
        tip: 'Trickle, do not pour. Adding hot water in one go will scramble the eggs in the bowl before the pasta ever gets there.',
      },
      {
        n: 9,
        text: 'Drain the spaghetti and tip it straight into the frying pan with the guanciale and fat, off the heat, tossing hard for 30 seconds so every strand is coated.',
        minutes: 1,
      },
      {
        n: 10,
        text: 'Now pour the tempered egg mixture over the pasta, still off the heat, and toss and stir continuously for about a minute. The sauce will thicken as the residual heat of the pasta cooks the egg just enough to cling.',
        minutes: 2,
        tip: 'The pan must be off the heat and, if it is cast iron or very heavy, off the hob entirely. Direct heat at this stage turns carbonara into spaghetti with scrambled egg in under ten seconds, and it cannot be rescued.',
      },
      {
        n: 11,
        text: 'Judge the consistency. It should flow slowly and coat the strands like a thin custard; loosen it with the reserved water a tablespoon at a time until it does. If it is still too loose, hold the pan a few centimetres above a low flame for a few seconds at a time, stirring, and take it away between each.',
        minutes: 1,
      },
      {
        n: 12,
        text: 'Serve immediately into warmed bowls, top with the reserved crisp guanciale, more grated pecorino and another crack of pepper. It waits for nobody.',
        minutes: 1,
        tip: 'Warm the bowls under the hot tap and dry them. Cold ceramic pulls the heat out of the sauce and it stiffens into a paste on the way to the table.',
      },
    ],
    failures: [
      { symptom: 'Scrambled egg clinging to the pasta', cause: 'The pan was still on the heat when the egg went in; take it fully off the hob, and temper the eggs with hot pasta water first so the shock is smaller.' },
      { symptom: 'Sauce is thin and pooling in the bottom of the bowl', cause: 'Not enough starch or not enough tossing; use less cooking water so it is more concentrated, toss vigorously for a full minute, and finish with brief pulses of low heat.' },
      { symptom: 'Sauce is gritty rather than smooth', cause: 'The pecorino was grated too coarsely or not fully whisked in; grate it to a powder on the fine side of the grater and whisk it into the egg until it disappears.' },
      { symptom: 'Far too salty to eat', cause: 'The pasta water was salted as usual on top of salty guanciale and pecorino; use about 5 g salt per litre and never add salt to the finished sauce.' },
      { symptom: 'Guanciale is chewy and pale with fat still in it', cause: 'It went into a hot pan; start it in a cold dry pan over medium-low heat and give it a full 10 minutes to render.' },
    ],
    variants: [
      {
        id: 'carbonara_bacon',
        label: 'With streaky bacon',
        swaps: [
          { from: 'guanciale', to: 'bacon_streaky', grams: 120 },
        ],
        methodDeltas: [
          { step: 1, change: 'Bacon is cured with more salt but gives less of it up into the fat; drop the pasta water to 4 g salt per litre and taste before serving.' },
          { step: 2, change: 'Bacon is wetter and leaner than guanciale: it will spit and steam for the first two minutes, then crisp in about 6 rather than 10. Add the 5 g olive oil at the start, because it renders roughly half as much fat.' },
          { step: 9, change: 'There is less fat in the pan to coat the pasta, so add an extra 20 g of the reserved pasta water when the spaghetti goes in.' },
        ],
        tags: [],
        note: 'Not carbonara to a Roman, but it is what most people actually have in the fridge.',
      },
      {
        id: 'carbonara_leggera',
        label: 'Lighter, with peas',
        swaps: [
          { from: 'guanciale', to: 'bacon_streaky', grams: 70 },
          { from: 'parmesan', to: 'peas_frozen', grams: 120 },
        ],
        methodDeltas: [
          { step: 2, change: 'With only 70 g of bacon, render it in a cold pan for 6 minutes then pour off all but 1 tablespoon of the fat. Keep the crisp pieces and set the drained fat aside in case the sauce needs loosening.' },
          { step: 5, change: 'Drop the frozen peas into the pasta water for the last 2 minutes of the spaghetti cooking time and drain them together.' },
          { step: 6, change: 'Without the parmesan the cheese mixture is sharper and saltier; use 55 g pecorino rather than 60 g and add an extra egg yolk to keep the sauce rich enough to bind with less fat in the pan.' },
        ],
        tags: [],
        note: 'Roughly 10 g less fat per portion and 5 g more fibre; the sauce is noticeably less unctuous.',
      },
      {
        id: 'carbonara_mushroom',
        label: 'No pork, with mushrooms',
        swaps: [
          { from: 'guanciale', to: 'mushroom', grams: 250 },
          { from: 'olive_oil', to: 'butter', grams: 30 },
        ],
        methodDeltas: [
          { step: 2, change: 'Mushrooms need the opposite treatment to guanciale: a hot dry pan, in one layer, undisturbed for 4 minutes until they have released their water and it has boiled off, and only then add the butter and fry 3 minutes more until deeply browned. Crowding them steams them grey.' },
          { step: 3, change: 'Season the mushrooms with a pinch of salt at the end rather than the start, since salting early draws water out and stops them browning.' },
          { step: 9, change: 'There is no rendered fat, so the butter and 30 g extra pasta water do that job; toss for a full minute before the egg goes in so the strands are properly slicked.' },
          { step: 10, change: 'Mushrooms hold less heat than fat-coated pasta, so work faster and consider giving the pan 5 seconds over a low flame before the egg to bring the temperature up.' },
        ],
        tags: ['nut_free'],
        note: 'Pecorino Romano is made with animal rennet, so this is pork free rather than strictly vegetarian; swap in a rennet-free hard cheese if that matters.',
      },
      {
        id: 'carbonara_vegan',
        label: 'Vegan, with tofu and cashew',
        swaps: [
          { from: 'guanciale', to: 'mushroom', grams: 250 },
          { from: 'egg', to: 'tofu_firm', grams: 200 },
          { from: 'pecorino', to: 'cashews', grams: 70 },
          { from: 'parmesan', to: null },
        ],
        methodDeltas: [
          { step: 2, change: 'Fry the mushrooms in a hot dry pan in one layer for 4 minutes until dry and browned, then add 30 g olive oil, up from the 5 g in the base recipe, and 2 g extra black pepper.' },
          { step: 6, change: 'Instead of whisking, blend the tofu with the cashews, which have been soaked in boiling water for 20 minutes, plus 100 g of the pasta water, 10 g lemon juice and 4 g salt, until completely smooth. Blend for longer than feels necessary; any cashew grit will not dissolve later.' },
          { step: 8, change: 'There is no egg to curdle, so skip the tempering entirely and add the blended sauce straight to the pan.' },
          { step: 10, change: 'This sauce will not set from residual heat. Return the pan to a low flame and stir for 2 minutes until it thickens, which is the exact opposite of the egg version, then loosen with pasta water.' },
        ],
        tags: ['vegan', 'vegetarian'],
      },
    ],
    restaurantGBP: 13.50,
    tags: ['pork'],
  },
];
