import { Recipe } from './types';

export const RECIPES_B: Recipe[] = [
  // ============================================================
  // 1. Seven-Vegetable Couscous with lamb — Morocco
  // ============================================================
  {
    id: 'moroccan_couscous',
    name: 'Seven-Vegetable Couscous with Lamb',
    localName: 'كسكس',
    cuisine: 'Moroccan',
    country: 'MA',
    blurb: 'Lamb and seven vegetables simmered in a saffron-and-ras-el-hanout broth, spooned over steamed couscous with harissa on the side.',
    servings: 2,
    activeMin: 35,
    totalMin: 100,
    difficulty: 'medium',
    items: [
      { ref: 'lamb_diced', grams: 250, note: 'shoulder, 3 cm cubes, patted dry' },
      { ref: 'couscous', grams: 160, note: 'dry, medium grain' },
      { ref: 'onion', grams: 120, note: 'halved and sliced thick' },
      { ref: 'carrot', grams: 120, note: 'cut into 5 cm batons' },
      { ref: 'sweet_potato', grams: 150, note: 'peeled, large chunks' },
      { ref: 'courgette', grams: 130, note: 'thick half-moons, added late' },
      { ref: 'aubergine', grams: 130, note: 'large chunks, added late' },
      { ref: 'red_pepper', grams: 120, note: 'deseeded, quartered' },
      { ref: 'tomato_fresh', grams: 150, note: 'roughly chopped' },
      { ref: 'chickpeas_tinned', grams: 120, note: 'drained and rinsed' },
      { ref: 'tomato_puree', grams: 20 },
      { ref: 'garlic', grams: 8, note: '2 cloves, crushed' },
      { ref: 'ginger', grams: 6, note: 'grated' },
      { ref: 'ras_el_hanout', grams: 8, note: 'about 4 tsp' },
      { ref: 'turmeric', grams: 2 },
      { ref: 'cinnamon_ground', grams: 2 },
      { ref: 'black_pepper', grams: 1 },
      { ref: 'salt', grams: 3, note: 'the stock cube is already most of the seasoning — taste first' },
      { ref: 'stock_cube_chicken', grams: 10, note: '1 cube' },
      { ref: 'water', grams: 900, note: 'plus 160 for the couscous' },
      { ref: 'olive_oil', grams: 25 },
      { ref: 'butter', grams: 20, note: 'forked through the couscous at the end' },
      { ref: 'saffron', grams: 0.1, note: 'a pinch, soaked in 2 tbsp warm water', optional: true },
      { ref: 'harissa', grams: 20, note: 'served alongside, loosened with broth', optional: true },
      { ref: 'coriander_fresh', grams: 10, note: 'chopped, to finish', optional: true },
      { ref: 'parsley_fresh', grams: 10, note: 'chopped, to finish', optional: true },
    ],
    method: [
      { n: 1, text: 'Pat the lamb completely dry with kitchen paper and season it with half the salt and all the black pepper. Wet meat steams instead of browning, so if the cubes still glisten, keep blotting.', minutes: 5 },
      { n: 2, text: 'Heat the olive oil in a heavy casserole over medium-high heat until it shimmers. Brown the lamb in two batches, about 3 minutes per side, until each piece has a deep brown crust. Lift the browned lamb onto a plate.', minutes: 12, tip: 'Crowding the pan drops the temperature and the lamb will grey rather than brown. Two batches is not optional at this quantity.' },
      { n: 3, text: 'Lower the heat to medium and add the onion to the same pan. Cook for 6 minutes, scraping the brown residue off the base with a wooden spoon as the onion releases its water.', minutes: 6 },
      { n: 4, text: 'Add the garlic, ginger, ras el hanout, turmeric and cinnamon. Stir constantly for 45 seconds until the pan smells strongly of the spices, then stir in the tomato puree and cook it for another minute.', minutes: 2, tip: 'Ground spices burn in well under a minute at this heat. Move them constantly and go straight to the next step the moment you can smell them.' },
      { n: 5, text: 'Return the lamb and any juices to the pan. Add the chopped tomato, the crumbled stock cube, the saffron with its soaking water if using, and 900 ml of water. Bring to a boil, then drop the heat until the surface only just trembles.', minutes: 5 },
      { n: 6, text: 'Cover and simmer gently for 45 minutes. The lamb should be tender enough to press apart with a spoon but not falling into threads.', minutes: 45, tip: 'A rolling boil makes lamb shoulder tighten and go stringy. You want lazy bubbles breaking the surface every second or two, no more.' },
      { n: 7, text: 'Add the carrot, sweet potato and red pepper. Simmer uncovered for 12 minutes.', minutes: 12 },
      { n: 8, text: 'Add the aubergine, courgette and drained chickpeas. Simmer for a further 10 minutes, until a knife slides into the carrot with no resistance. Taste and add the remaining salt.', minutes: 10, tip: 'Courgette goes from firm to mush in about 4 minutes of over-cooking. Put it in last and check it early.' },
      { n: 9, text: 'While the vegetables finish, put the couscous in a wide bowl with a pinch of salt. Pour over 160 ml of boiling water, stir once, cover with a plate and leave it strictly alone for 8 minutes.', minutes: 8 },
      { n: 10, text: 'Uncover the couscous, drop in the butter and rake the grains apart with a fork, working from the outside in until there are no lumps and the butter has vanished. Check the thickest piece reads 75 C before it goes back in.', minutes: 3, tip: 'Use a fork, never a spoon. A spoon compresses the grains into a paste that no amount of stirring will fix.' },
      { n: 11, text: 'Spoon the couscous into two wide bowls, pile the lamb and vegetables on top and ladle over enough broth to soak the grains without flooding them, roughly a ladleful each.', minutes: 3 },
      { n: 12, text: 'Loosen the harissa with a spoonful of hot broth in a small dish and serve it on the side rather than stirring it through: heat tolerance varies and you cannot take it back out. Scatter the coriander and parsley over the bowls.', minutes: 2 },
    ],
    failures: [
      { symptom: 'Couscous is claggy and clumped into lumps.', cause: 'Too much water or it was stirred with a spoon. Use equal volumes of couscous and boiling water, and separate the grains with a fork only.' },
      { symptom: 'Lamb is dry and stringy after the long simmer.', cause: 'The broth was boiling rather than trembling. Drop the heat until bubbles break slowly, and add 10 minutes rather than more heat.' },
      { symptom: 'Vegetables have collapsed into the broth.', cause: 'They all went in at once. Stagger them by density: carrot and sweet potato first, aubergine and courgette 12 minutes later.' },
      { symptom: 'Broth tastes flat and dusty.', cause: 'Spices were added to liquid rather than fried in fat. Bloom them in the oil for 45 seconds before any water goes in, and salt again at the end.' },
      { symptom: 'Everything tastes vaguely of cinnamon and nothing else.', cause: 'Too heavy a hand with the cinnamon against the ras el hanout, which already contains it. Keep cinnamon to 1 tsp for this quantity.' },
    ],
    variants: [
      {
        id: 'couscous_chicken',
        label: 'Chicken instead of lamb',
        swaps: [{ from: 'lamb_diced', to: 'chicken_thigh', grams: 300 }],
        methodDeltas: [
          { step: 2, change: 'Chicken thigh browns in about 4 minutes total, not 6. Take it further than looks necessary on the skin side only, then turn once.' },
          { step: 6, change: 'Cut the covered simmer from 45 minutes to 20. Thigh is tender at that point and turns woolly past 30 minutes, unlike lamb shoulder.' },
          { step: 7, change: 'Lift the chicken out before adding the root vegetables and return it for the final 10 minutes, or it will shred into the broth.' },
        ],
        tags: ['halal', 'nut_free'],
        note: 'Total time drops to about 70 minutes.',
      },
      {
        id: 'couscous_vegan',
        label: 'Vegan seven-vegetable',
        swaps: [
          { from: 'lamb_diced', to: null },
          { from: 'stock_cube_chicken', to: 'stock_cube_veg', grams: 10 },
          { from: 'butter', to: 'olive_oil', grams: 15 },
          { from: 'chickpeas_tinned', to: 'chickpeas_tinned', grams: 240 },
        ],
        methodDeltas: [
          { step: 2, change: 'With no meat there is no browned fond to build on. Instead brown the onion hard for 10 minutes until the edges are genuinely dark, and add a chopped aubergine early to caramelise in the oil.' },
          { step: 4, change: 'Fry the spices for a full 60 seconds in the oil and add an extra teaspoon of ras el hanout. Vegetable broth carries less body, so it needs more aromatic weight.' },
          { step: 6, change: 'Skip the 45-minute covered simmer entirely. Simmer the broth alone for 15 minutes to concentrate it, then go straight to the vegetable stages.' },
          { step: 8, change: 'Taste and salt twice as carefully. Without lamb fat the seasoning point is much harder to hit and undersalted vegetable broth tastes watery.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
      },
      {
        id: 'couscous_lean',
        label: 'Leaner, higher-protein chicken breast',
        swaps: [
          { from: 'lamb_diced', to: 'chicken_breast', grams: 320 },
          { from: 'butter', to: null },
          { from: 'olive_oil', to: 'olive_oil', grams: 15 },
        ],
        methodDeltas: [
          { step: 2, change: 'Sear the breast whole for 2 minutes a side and remove it immediately. Diced breast browned to a crust is already overcooked inside.' },
          { step: 6, change: 'Do not simmer the breast at all during this stage. Build the broth without it.' },
          { step: 8, change: 'Slide the seared breast back in for the last 15 minutes at a bare simmer, then lift it out, rest it 3 minutes and slice across the grain. It must reach 74 C in the thickest part — 71 C is the target for minced beef, not poultry, and a whole breast will not get there in eight minutes.' },
          { step: 10, change: 'Without butter, fork 1 tbsp of the hot broth through the couscous instead so the grains do not dry out.' },
        ],
        tags: ['halal', 'dairy_free', 'nut_free'],
      },
    ],
    restaurantGBP: 14.5,
    tags: ['halal', 'nut_free'],
  },

  // ============================================================
  // 2. Chicken Tacos — Mexico
  // ============================================================
  {
    id: 'chicken_tacos',
    name: 'Chicken Tacos with Lime and Salsa',
    localName: 'Tacos de Pollo',
    cuisine: 'Mexican',
    country: 'MX',
    blurb: 'Cumin and smoked-paprika chicken thigh seared hard, chopped, and piled into warmed corn tortillas with raw tomato salsa and lime.',
    servings: 2,
    activeMin: 30,
    totalMin: 45,
    difficulty: 'easy-medium',
    items: [
      { ref: 'chicken_thigh', grams: 300, note: 'boneless, skinless, opened out flat' },
      { ref: 'tortilla_corn', grams: 180, note: '6 small tortillas' },
      { ref: 'cumin_ground', grams: 4, note: '2 tsp' },
      { ref: 'paprika_smoked', grams: 4, note: '2 tsp' },
      { ref: 'oregano_dried', grams: 2 },
      { ref: 'chilli_powder', grams: 2 },
      { ref: 'garlic', grams: 8, note: '2 cloves, crushed' },
      { ref: 'vegetable_oil', grams: 15 },
      { ref: 'salt', grams: 5 },
      { ref: 'black_pepper', grams: 1 },
      { ref: 'lime', grams: 60, note: 'half juiced for the marinade, half in wedges' },
      { ref: 'tomato_fresh', grams: 200, note: 'firm, deseeded and finely diced' },
      { ref: 'red_onion', grams: 60, note: 'finely diced, rinsed under cold water' },
      { ref: 'green_chilli', grams: 12, note: 'deseeded and minced' },
      { ref: 'coriander_fresh', grams: 15, note: 'leaves and thin stems, chopped' },
      { ref: 'white_cabbage', grams: 80, note: 'shredded as fine as you can' },
      { ref: 'avocado', grams: 130, note: 'sliced, added at the table', optional: true },
      { ref: 'natural_yogurt', grams: 60, note: 'thinned with lime juice', optional: true },
      { ref: 'feta', grams: 40, note: 'crumbled, standing in for queso fresco', optional: true },
    ],
    method: [
      { n: 1, text: 'Mix the cumin, smoked paprika, oregano, chilli powder, garlic, half the salt, the black pepper, 1 tbsp of the oil and the juice of half the lime in a bowl. Add the chicken thighs and turn them until coated.', minutes: 5 },
      { n: 2, text: 'Leave the chicken to marinate for 15 minutes at room temperature, or up to 4 hours in the fridge.', minutes: 15, tip: 'Do not push past 4 hours. The lime acid starts to firm and whiten the surface of the meat, which then cooks to a chalky texture.' },
      { n: 3, text: 'Meanwhile make the salsa. Rinse the diced red onion under cold water for 20 seconds, which strips the raw sulphurous bite that would otherwise dominate, then combine it with the diced tomato, green chilli, two thirds of the coriander, the juice of a quarter lime and the remaining salt.', minutes: 8 },
      { n: 4, text: 'Salt the tomatoes last and taste after 5 minutes. They will release liquid; tip off any pool that gathers or the tortillas will go soggy.', minutes: 5 },
      { n: 5, text: 'Heat a heavy frying pan or griddle over high heat for a full 3 minutes with no oil in it. It should be hot enough that a drop of water skitters and vanishes.', minutes: 3, tip: 'A pan that is merely hot will poach the chicken in its own marinade. Wait for the water-drop test before anything goes in.' },
      { n: 6, text: 'Add the remaining oil, then lay the thighs flat in the pan without crowding. Cook undisturbed for 5 to 6 minutes until the underside is deeply browned and releases on its own.', minutes: 6, tip: 'If the chicken sticks when you try to lift it, it is not ready. It releases itself when the crust has formed.' },
      { n: 7, text: 'Turn and cook for a further 4 to 5 minutes, until the thickest part reads 75 C or the juices run clear when pierced.', minutes: 5 },
      { n: 8, text: 'Move the chicken to a board and rest it for 5 minutes before cutting. Cutting straight away loses the juice to the board.', minutes: 5 },
      { n: 9, text: 'While it rests, warm the tortillas. Put them one at a time into the same hot dry pan for 30 seconds a side, until they smell toasty and are pliable. Stack them under a clean tea towel as they come off.', minutes: 5, tip: 'Cold corn tortillas crack the moment you fold them. Warming plus 2 minutes of steaming under the towel is what makes them bend.' },
      { n: 10, text: 'Chop the rested chicken into rough 1.5 cm pieces and toss it back through any juices left on the board.', minutes: 2 },
      { n: 11, text: 'Build each taco: shredded cabbage first as a moisture barrier, then chicken, then salsa, then avocado and a spoon of lime-thinned yogurt.', minutes: 4, tip: 'Cabbage under the meat is not garnish. It keeps the tortilla from turning to paper before you finish eating.' },
      { n: 12, text: 'Scatter over the remaining coriander and the crumbled feta, and serve with lime wedges to squeeze at the table.', minutes: 2 },
    ],
    failures: [
      { symptom: 'Tortillas tear apart as you fold them.', cause: 'They went in cold or were warmed too briefly. Give each 30 seconds a side in a dry hot pan, then stack under a towel so they steam soft.' },
      { symptom: 'Chicken is grey and sitting in liquid rather than browned.', cause: 'Pan was not hot enough or was overloaded. Preheat 3 minutes on high and cook in two batches if your pan is small.' },
      { symptom: 'Salsa is watery and floods the taco.', cause: 'Tomatoes were not deseeded, or were salted too early. Deseed, dice, and salt no more than 5 minutes before serving, then drain off the pooled liquid.' },
      { symptom: 'Everything tastes flat despite plenty of spice.', cause: 'No acid at the end. The lime squeezed at the table is doing real work, not decoration.' },
    ],
    variants: [
      {
        id: 'tacos_prawn',
        label: 'Prawn tacos',
        swaps: [{ from: 'chicken_thigh', to: 'prawns_raw', grams: 280 }],
        methodDeltas: [
          { step: 2, change: 'Marinate for 15 minutes maximum. Lime juice will chemically cure raw prawns into ceviche and they turn rubbery when they then hit the pan.' },
          { step: 6, change: 'Prawns need 90 seconds a side, not 6 minutes. Pull them the moment they turn opaque and curl into a loose C; a tight O means overcooked.' },
          { step: 8, change: 'Skip the rest entirely and skip the chopping. Prawns go straight from pan to tortilla whole.' },
        ],
        tags: ['halal', 'gluten_free', 'nut_free'],
      },
      {
        id: 'tacos_tofu_vegan',
        label: 'Vegan tofu tacos',
        swaps: [
          { from: 'chicken_thigh', to: 'tofu_firm', grams: 320 },
          { from: 'natural_yogurt', to: 'soya_yogurt', grams: 60 },
          { from: 'feta', to: null },
          { from: 'vegetable_oil', to: 'vegetable_oil', grams: 25 },
        ],
        methodDeltas: [
          { step: 1, change: 'Press the tofu between two plates with a weight on top for 20 minutes first and pour off the water. Unpressed tofu cannot absorb the marinade and will not brown.' },
          { step: 2, change: 'Tofu absorbs almost nothing in 15 minutes. Give it a minimum of 30 minutes, and rub the dry spices directly onto the pressed surfaces before adding the wet ingredients.' },
          { step: 6, change: 'Tear the tofu into rough chunks rather than slicing. Fry in the larger quantity of oil for 8 minutes total, turning only twice, until at least two faces are crisp and golden.' },
          { step: 11, change: 'Tofu carries no fat of its own, so double the avocado and add an extra squeeze of lime directly onto the tofu before assembling.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'gluten_free', 'nut_free'],
      },
      {
        id: 'tacos_lean_fish',
        label: 'Leaner white fish',
        swaps: [
          { from: 'chicken_thigh', to: 'white_fish', grams: 320 },
          { from: 'vegetable_oil', to: 'olive_oil', grams: 12 },
        ],
        methodDeltas: [
          { step: 1, change: 'Leave the lime juice out of the marinade completely and rub the fish with the dry spices and oil only. Lime turns raw white fish opaque before it reaches the pan.' },
          { step: 6, change: 'Cook in one layer for 3 minutes on the first side, then turn once with a fish slice. Fish will not release cleanly from a crowded pan.' },
          { step: 10, change: 'Do not chop. Flake the fish into large pieces with a fork so it does not disintegrate.' },
        ],
        tags: ['halal', 'gluten_free', 'nut_free'],
      },
    ],
    restaurantGBP: 10.5,
    tags: ['halal', 'gluten_free', 'nut_free'],
  },

  // ============================================================
  // 3. Jollof Rice with chicken — Nigeria / West Africa
  // ============================================================
  {
    id: 'jollof_rice',
    name: 'Jollof Rice with Chicken',
    localName: 'Iresi Jollof',
    cuisine: 'West African',
    country: 'NG',
    blurb: 'Long-grain rice steamed in a fried pepper-and-tomato base with browned chicken thigh, cooked until the bottom layer catches and smokes.',
    servings: 2,
    activeMin: 35,
    totalMin: 80,
    difficulty: 'medium',
    items: [
      { ref: 'chicken_thigh', grams: 350, note: 'bone-in or boneless, seasoned ahead' },
      { ref: 'long_grain_rice', grams: 200, note: 'rinsed until the water runs clear' },
      { ref: 'passata', grams: 300 },
      { ref: 'tomato_puree', grams: 30 },
      { ref: 'red_pepper', grams: 150, note: 'deseeded, blitzed with the onion' },
      { ref: 'onion', grams: 150, note: 'half blitzed into the base, half sliced' },
      { ref: 'scotch_bonnet', grams: 8, note: 'deseeded unless you know what you are doing' },
      { ref: 'garlic', grams: 10, note: 'about 2 large cloves' },
      { ref: 'ginger', grams: 8, note: 'peeled' },
      { ref: 'vegetable_oil', grams: 45 },
      { ref: 'stock_cube_chicken', grams: 10, note: '1 cube, crumbled' },
      { ref: 'coriander_ground', grams: 3, note: 'standing in for curry powder' },
      { ref: 'turmeric', grams: 2, note: 'for colour, with the coriander' },
      { ref: 'paprika_smoked', grams: 3 },
      { ref: 'bay_leaf', grams: 1, note: '2 leaves' },
      { ref: 'salt', grams: 6 },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'water', grams: 350 },
      { ref: 'spring_onion', grams: 20, note: 'sliced, to finish', optional: true },
    ],
    method: [
      { n: 1, text: 'Season the chicken all over with half the salt, the black pepper and 1 tsp of the paprika. Leave it while you make the base.', minutes: 5 },
      { n: 2, text: 'Blitz the red pepper, half the onion, the scotch bonnet, garlic and ginger to a smooth puree in a blender; it should be thin enough to pour. Wash your hands straight afterwards, as scotch bonnet oil stays on skin through several rinses.', minutes: 5 },
      { n: 3, text: 'Heat 2 tbsp of the oil in a heavy lidded pan over medium-high heat and brown the chicken for 4 minutes a side until well coloured. Lift it out onto a plate.', minutes: 10 },
      { n: 4, text: 'Add the rest of the oil and the sliced onion to the same pan. Fry for 5 minutes until softened and going golden at the edges. The chicken must read 75 C at the thickest point.', minutes: 5 },
      { n: 5, text: 'Stir in the tomato puree and fry it for 2 minutes until it darkens from bright red to brick.', minutes: 2, tip: 'Undercooked tomato puree tastes tinny and sour, and no amount of later simmering hides it. Wait for the colour change.' },
      { n: 6, text: 'Pour in the blended pepper base and the passata. Bring it to a simmer and cook uncovered for 15 to 20 minutes, stirring every few minutes, until the raw smell is gone and the oil separates out and pools on the surface.', minutes: 20, tip: 'The oil rising to the top is the signal that the base is properly fried. Stopping before this is the single most common reason home jollof tastes thin.' },
      { n: 7, text: 'Stir in the crumbled stock cube, ground coriander, turmeric, remaining paprika, bay leaves and the remaining salt. Cook for a further 2 minutes.', minutes: 2 },
      { n: 8, text: 'Add the rinsed rice and stir until every grain is coated red. Pour in the water, which should sit roughly 1 cm above the rice, and nestle the chicken and its juices back on top.', minutes: 3, tip: 'Rinse the rice until the water runs clear beforehand. Surface starch is what turns jollof into a sticky mass rather than separate grains.' },
      { n: 9, text: 'Bring to a boil, then drop the heat to the lowest setting. Cover the pan with foil pressed down onto the rim, put the lid on top of that, and leave it for 25 minutes.', minutes: 25, tip: 'Do not lift the lid to check. Every peek releases the steam that is actually cooking the rice, and the top layer stays hard.' },
      { n: 10, text: 'After 25 minutes, uncover and taste a grain from the top. If it is still firm, add 3 tbsp of hot water, re-cover and give it 5 more minutes.', minutes: 5 },
      { n: 11, text: 'For the smoky bottom layer, turn the heat to medium-high for the final 3 minutes with the lid on. You want to hear a faint crackle and smell toasting, not burning.', minutes: 3, tip: 'The line between party-jollof smoke and acrid burn is about 60 seconds. Stay at the pan and pull it the moment the smell sharpens.' },
      { n: 12, text: 'Turn off the heat and leave the pan covered and undisturbed for 10 minutes.', minutes: 10 },
      { n: 13, text: 'Fluff the rice up from the bottom with a fork, folding the darker crusted grains through the rest. Discard the bay leaves, scatter over the spring onion and serve.', minutes: 3 },
    ],
    failures: [
      { symptom: 'Rice is sticky and clumped into one mass.', cause: 'The rice was not rinsed, or there was too much liquid. Rinse until clear and keep the water at 1 cm above the rice, no more.' },
      { symptom: 'Top layer is crunchy while the bottom is cooked.', cause: 'Steam escaped. Seal with foil under the lid and resist lifting it; if it happens, add 3 tbsp hot water and give it 5 more covered minutes.' },
      { symptom: 'Sauce tastes sharp and raw rather than deep.', cause: 'The pepper base was not fried long enough. Cook it until oil visibly separates and pools on the surface, usually 15 to 20 minutes.' },
      { symptom: 'The bottom is black and bitter, not smoky.', cause: 'Too long or too high on the final blast. Three minutes on medium-high is the limit, and you go by smell not by clock.' },
      { symptom: 'Colour is orange-brown rather than deep red.', cause: 'Too much turmeric or over-reduced puree. Turmeric is a supporting colour only; the red should come from the pepper and passata.' },
    ],
    variants: [
      {
        id: 'jollof_vegan',
        label: 'Vegan jollof with soya chunks',
        swaps: [
          { from: 'chicken_thigh', to: 'soya_chunks', grams: 70 },
          { from: 'stock_cube_chicken', to: 'stock_cube_veg', grams: 10 },
          { from: 'vegetable_oil', to: 'vegetable_oil', grams: 60 },
        ],
        methodDeltas: [
          { step: 1, change: 'Soak the dry soya chunks in hot seasoned stock for 15 minutes, then squeeze them out hard like a sponge. Unsqueezed chunks release water into the rice and it will not cook properly.' },
          { step: 3, change: 'Fry the squeezed chunks in the oil for 6 minutes until browned and slightly crisp at the edges, then set aside. There is no chicken fat here, which is why the oil quantity goes up.' },
          { step: 8, change: 'Do not add the soya chunks with the rice. They will turn to mush over 25 minutes of steaming.' },
          { step: 12, change: 'Fold the fried chunks through during the 10-minute rest so they warm without stewing.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'dairy_free', 'nut_free'],
      },
      {
        id: 'jollof_beef',
        label: 'Beef jollof',
        swaps: [
          { from: 'chicken_thigh', to: 'beef_brisket', grams: 350 },
          { from: 'stock_cube_chicken', to: 'stock_cube_beef', grams: 10 },
        ],
        methodDeltas: [
          { step: 3, change: 'Brown the brisket, then simmer it separately in 700 ml of water with the stock cube for 90 minutes until tender. Brisket will still be tough after the 25-minute rice steam.' },
          { step: 8, change: 'Use 350 ml of the beef cooking liquid in place of plain water. This is where the depth comes from, so do not throw it away.' },
          { step: 9, change: 'Add the cooked brisket on top of the rice for the covered steam so it only needs reheating, not cooking.' },
        ],
        tags: ['halal', 'dairy_free', 'nut_free'],
        note: 'Adds about 90 minutes, most of it unattended.',
      },
      {
        id: 'jollof_lean',
        label: 'Leaner chicken breast',
        swaps: [
          { from: 'chicken_thigh', to: 'chicken_breast', grams: 320 },
          { from: 'vegetable_oil', to: 'vegetable_oil', grams: 25 },
        ],
        methodDeltas: [
          { step: 3, change: 'Sear the breast whole for 2 minutes a side only, then remove. Do not try to cook it through at this stage.' },
          { step: 9, change: 'Steam the rice without the chicken on top for the full 25 minutes.' },
          { step: 11, change: 'Slice the seared breast into 1 cm strips and bury them in the rice for the whole 25-minute covered steam, not just the last few minutes. Check 74 C in the thickest strip before serving. Do not rely on residual heat in a pot that is off the heat — it will not finish a whole breast.' },
        ],
        tags: ['halal', 'dairy_free', 'nut_free'],
      },
    ],
    restaurantGBP: 12.0,
    tags: ['halal', 'dairy_free', 'nut_free'],
  },

  // ============================================================
  // 4. Dal Tadka with rice — India
  // ============================================================
  {
    id: 'dal_tadka',
    name: 'Dal Tadka with Rice',
    localName: 'दाल तड़का',
    cuisine: 'Indian',
    country: 'IN',
    blurb: 'Red lentils simmered soft with turmeric, then finished with a ghee tempering of cumin, mustard seed, garlic and chilli poured over at the table.',
    servings: 2,
    activeMin: 25,
    totalMin: 50,
    difficulty: 'easy',
    items: [
      { ref: 'red_lentils', grams: 180, note: 'rinsed in three changes of water' },
      { ref: 'water', grams: 900, note: 'for the lentils' },
      { ref: 'turmeric', grams: 2 },
      { ref: 'salt', grams: 6 },
      { ref: 'basmati_rice', grams: 160, note: 'rinsed and drained' },
      { ref: 'ghee', grams: 30, note: 'for the tadka' },
      { ref: 'cumin_ground', grams: 4, note: 'whole seeds if you have them' },
      { ref: 'mustard_seeds', grams: 3 },
      { ref: 'garlic', grams: 12, note: '3 cloves, thinly sliced not crushed' },
      { ref: 'ginger', grams: 8, note: 'julienned' },
      { ref: 'onion', grams: 100, note: 'finely diced' },
      { ref: 'tomato_fresh', grams: 150, note: 'chopped small' },
      { ref: 'green_chilli', grams: 10, note: 'slit lengthways' },
      { ref: 'kashmiri_chilli', grams: 3, note: 'added off the heat' },
      { ref: 'coriander_ground', grams: 3 },
      { ref: 'garam_masala', grams: 2, note: 'stirred in at the very end' },
      { ref: 'lemon', grams: 30, note: 'juice, to finish' },
      { ref: 'curry_leaves', grams: 2, note: 'if you can get them fresh', optional: true },
      { ref: 'fenugreek_leaves', grams: 1, note: 'crushed between the palms', optional: true },
      { ref: 'coriander_fresh', grams: 10, note: 'chopped', optional: true },
    ],
    method: [
      { n: 1, text: 'Rinse the lentils in a bowl of cold water, pouring off the cloudy water and repeating three times until it runs nearly clear. Skipping this gives a grey scummy foam and a slightly bitter finish.', minutes: 3 },
      { n: 2, text: 'Put the lentils in a saucepan with 900 ml of water and the turmeric. Bring to a boil, then skim off the pale foam that rises in the first two minutes and discard it.', minutes: 6 },
      { n: 3, text: 'Lower the heat and simmer partly covered for 20 to 25 minutes, stirring occasionally, until the lentils have completely lost their shape and the dal coats the back of a spoon.', minutes: 25, tip: 'Leave the lid ajar. Lentils foam up and boil over the moment the pan is fully covered, and they catch on the base if you never stir.' },
      { n: 4, text: 'While the dal simmers, cook the rice. Put the rinsed basmati in a pan with 320 ml of water, bring to a boil, cover, drop to the lowest heat and cook for 10 minutes, then leave covered off the heat for 10 more.', minutes: 20, tip: 'The 10 minutes standing off the heat is not optional. That is when the grains finish absorbing and firm up; uncovering early gives wet rice.' },
      { n: 5, text: 'When the lentils are soft, add the salt and whisk the dal briefly to break down any remaining lumps. Add hot water a splash at a time until it is the consistency of single cream.', minutes: 3, tip: 'Salt only after the lentils are soft. Salting at the start slows them down noticeably.' },
      { n: 6, text: 'Now the tadka. Heat the ghee in a small frying pan over medium heat until it is fluid and shimmering but not smoking.', minutes: 2 },
      { n: 7, text: 'Add the mustard seeds, keeping a lid to hand because they genuinely jump out of the pan. When they start to pop, about 20 seconds, add the cumin and let it sizzle for 10 seconds until it smells nutty. If they have not popped within 30 seconds, the ghee was not hot enough.', minutes: 1 },
      { n: 8, text: 'Add the sliced garlic and cook for 60 to 90 seconds until it is pale gold at the edges only.', minutes: 2, tip: 'Garlic goes from gold to bitter brown in about 15 seconds. Pull the pan off the heat while it still looks slightly underdone; it keeps cooking in the hot fat.' },
      { n: 9, text: 'Add the ginger, onion and slit green chilli. Cook for 5 minutes until the onion is soft and translucent, then add the curry leaves if using and stand back, they spit.', minutes: 5 },
      { n: 10, text: 'Stir in the chopped tomato and ground coriander. Cook for 5 to 6 minutes, pressing the tomato with the spoon, until it collapses and the ghee separates out around the edges.', minutes: 6 },
      { n: 11, text: 'Take the pan off the heat and stir in the kashmiri chilli. It colours the fat deep red in the residual heat without burning.', minutes: 1, tip: 'Kashmiri chilli added to a hot pan on the heat turns black and acrid within seconds. Off the heat, always.' },
      { n: 12, text: 'Pour the tadka over the dal. Do not stir it in immediately; let it sit for a minute so it hits the table as a distinct red slick on the surface.', minutes: 2 },
      { n: 13, text: 'Stir through the garam masala, the crushed fenugreek leaves and the lemon juice, then taste. If the dal tastes heavy or flat at this point it almost always needs more lemon rather than more salt; add it half a teaspoon at a time.', minutes: 2 },
      { n: 14, text: 'Serve the dal in bowls alongside the rice, scattered with fresh coriander.', minutes: 2 },
    ],
    failures: [
      { symptom: 'Lentils are still firm after 30 minutes.', cause: 'Salt or tomato went in too early, or the lentils are old stock. Cook them plain with turmeric only and season at the end.' },
      { symptom: 'Dal is gluey and stodgy by the time it reaches the table.', cause: 'It thickens fast as it sits. Loosen with hot water just before serving until it pours like single cream.' },
      { symptom: 'Tadka tastes bitter and burnt.', cause: 'The garlic browned past gold or the chilli powder went in on the heat. Pull the garlic at pale gold and add the kashmiri chilli off the heat.' },
      { symptom: 'It tastes of lentils and not much else.', cause: 'The tadka was stirred in too early or made in too little fat. Use the full 30 g of ghee and pour it over at the last moment.' },
    ],
    variants: [
      {
        id: 'dal_vegan',
        label: 'Vegan tadka',
        swaps: [{ from: 'ghee', to: 'vegetable_oil', grams: 30 }],
        methodDeltas: [
          { step: 6, change: 'Vegetable oil reaches its smoke point sooner than ghee and gives no aroma of its own. Heat it over medium rather than medium-high and watch for the first wisp.' },
          { step: 7, change: 'Bloom the cumin for 15 seconds rather than 10 and use a little more of it. Without ghee, the spices are doing all the aromatic work.' },
          { step: 13, change: 'Add an extra squeeze of lemon at the end. Ghee supplies a rounded richness that oil does not, and acid compensates for its absence more effectively than extra salt.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
      },
      {
        id: 'dal_paneer',
        label: 'Higher-protein, with paneer',
        swaps: [
          { from: 'curry_leaves', to: 'paneer', grams: 150 },
          { from: 'ghee', to: 'ghee', grams: 40 },
        ],
        methodDeltas: [
          { step: 6, change: 'Fry the paneer cubes in the ghee first, over medium heat for 2 minutes a side, until golden on two faces. Lift them out and make the tadka in the same flavoured fat.' },
          { step: 12, change: 'Fold the paneer into the dal only after the tadka has gone in and the heat is off. Paneer that simmers turns squeaky and tough within 5 minutes.' },
        ],
        tags: ['vegetarian', 'halal', 'gluten_free', 'nut_free'],
      },
      {
        id: 'dal_palak',
        label: 'Dal with spinach',
        swaps: [{ from: 'fenugreek_leaves', to: 'spinach_fresh', grams: 150 }],
        methodDeltas: [
          { step: 10, change: 'Add the spinach to the tadka pan a handful at a time after the tomato has collapsed. It wilts in about 90 seconds.' },
          { step: 12, change: 'Spinach releases a surprising amount of water into the dal. Cook the dal a further 3 minutes uncovered after combining, or it will taste diluted.' },
          { step: 13, change: 'Re-season after the spinach goes in. It flattens the salt noticeably and needs another pinch plus the lemon.' },
        ],
        tags: ['vegetarian', 'halal', 'gluten_free', 'nut_free'],
      },
    ],
    restaurantGBP: 9.5,
    tags: ['vegetarian', 'halal', 'kosher', 'gluten_free', 'nut_free'],
  },

  // ============================================================
  // 5. Pho Bo — Vietnam
  // ============================================================
  {
    id: 'beef_pho',
    name: 'Vietnamese Beef Noodle Soup',
    localName: 'Phở Bò',
    cuisine: 'Vietnamese',
    country: 'VN',
    blurb: 'Charred onion and ginger simmered with brisket and whole spices for three hours, poured boiling over rice noodles and raw sliced sirloin.',
    servings: 2,
    activeMin: 45,
    totalMin: 240,
    difficulty: 'hard',
    items: [
      { ref: 'beef_brisket', grams: 400, note: 'in one piece, for the broth and to slice' },
      { ref: 'beef_sirloin', grams: 150, note: 'frozen 20 min then sliced paper-thin, raw' },
      { ref: 'onion', grams: 250, note: '2 onions, halved and charred skin-on' },
      { ref: 'ginger', grams: 80, note: 'unpeeled, halved lengthways and charred' },
      { ref: 'star_anise', grams: 4, note: '4 whole stars' },
      { ref: 'cinnamon_ground', grams: 3, note: 'or one 8 cm stick if you have it' },
      { ref: 'cloves_whole', grams: 1, note: '4 cloves' },
      { ref: 'cardamom_green', grams: 2, note: '2 pods, lightly crushed' },
      { ref: 'coriander_ground', grams: 4, note: 'toasted dry for 30 seconds' },
      { ref: 'water', grams: 2500 },
      { ref: 'fish_sauce', grams: 15, note: 'season the broth at the end, tasting as you go — pho broth should taste of beef, not of fish sauce' },
      { ref: 'sugar', grams: 12, note: 'rock sugar if you have it' },
      { ref: 'salt', grams: 4, absorption: 0.7, note: 'a little in the parboil water, the rest to finish — the parboil water is thrown away' },
      { ref: 'rice_noodles', grams: 200, note: 'dried flat banh pho, 3 to 5 mm' },
      { ref: 'spring_onion', grams: 30, note: 'green parts sliced thin, white parts in the broth' },
      { ref: 'coriander_fresh', grams: 15, note: 'whole sprigs, at the table' },
      { ref: 'basil_fresh', grams: 15, note: 'Thai basil ideally, torn at the table' },
      { ref: 'beansprouts', grams: 100, note: 'raw, at the table' },
      { ref: 'lime', grams: 60, note: 'cut into wedges' },
      { ref: 'green_chilli', grams: 10, note: 'sliced into rings', optional: true },
      { ref: 'stock_cube_beef', grams: 10, note: 'insurance if the broth tastes thin', optional: true },
    ],
    method: [
      { n: 1, text: 'Put the brisket in a large pan, cover with cold water, bring to a boil and let it boil hard for 5 minutes. Grey scum will rise thickly.', minutes: 10, tip: 'This parboil is the difference between clear amber broth and cloudy grey soup. It looks wasteful and it is not.' },
      { n: 2, text: 'Tip the whole pan into the sink, discard that water, and rinse both the brisket and the pan under cold running water until no scum remains.', minutes: 5 },
      { n: 3, text: 'Char the aromatics. Put the halved onions cut-side down and the halved ginger directly into a dry heavy pan over high heat, or under a hot grill, and leave them until the surfaces are blackened in patches, about 8 minutes, turning once.', minutes: 10, tip: 'You want genuine black blistering, not golden. Undercharred aromatics give a broth that tastes like beef water rather than pho.' },
      { n: 4, text: 'Toast the star anise, cinnamon, cloves, cardamom and ground coriander in a dry pan over medium heat for 30 to 45 seconds, until fragrant. Tie them into a square of muslin or a tea infuser: loose ground spice clouds the broth and you will be picking cloves out of your noodles.', minutes: 2 },
      { n: 5, text: 'Return the rinsed brisket to the clean pan with the charred onion and ginger, the spices, the spring onion whites and 2.5 litres of cold water. Bring it slowly up to a bare simmer, starting from cold: a fast boil emulsifies the fat into the liquid and you cannot get it clear again.', minutes: 15 },
      { n: 6, text: 'Simmer uncovered for 3 hours at the gentlest possible heat, where a bubble breaks the surface every second or so. Skim the surface with a ladle every 30 minutes.', minutes: 180, tip: 'If the broth is ever rolling, it is too hot. Use the smallest burner on its lowest setting and move the pan half off it if you need to.' },
      { n: 7, text: 'After roughly 90 minutes, test the brisket with a skewer. When it slides in with only slight resistance, lift the brisket out and plunge it into cold water for 10 minutes, then wrap and refrigerate; this stops it drying out and firms it enough to slice thinly, whereas hot brisket shreds under the knife. Let the broth carry on.', minutes: 15 },
      { n: 8, text: 'Strain the finished broth through a fine sieve into a clean pan and discard the solids. You should have roughly 1.5 litres of clear amber liquid.', minutes: 5 },
      { n: 9, text: 'Season the broth with the fish sauce, sugar and salt. Taste it hot and push it slightly past what tastes right in the spoon: it should be assertively savoury and very slightly sweet, because a bowl of unseasoned noodles absorbs a lot of that intensity.', minutes: 5 },
      { n: 10, text: 'Soak the dried rice noodles in warm water for 20 minutes, then drop them into boiling water for 20 to 40 seconds only and drain. Divide them between two deep bowls.', minutes: 22, tip: 'Rice noodles go from firm to disintegrating in well under a minute of boiling. Taste one at 20 seconds and take them out slightly firm.' },
      { n: 11, text: 'Slice the chilled brisket across the grain as thinly as you can and lay it over the noodles. Freeze the sirloin for 20 minutes before slicing it, since fully soft beef cannot be cut thin enough for the broth to cook it, then lay the paper-thin slices alongside, spread out rather than piled.', minutes: 8 },
      { n: 12, text: 'Bring the seasoned broth back to a hard rolling boil, then ladle it straight over the meat and noodles. The raw sirloin should turn from red to pink within seconds.', minutes: 5, tip: 'The broth must be at a genuine boil, not merely hot. Broth below boiling leaves the raw beef grey and unpleasantly chewy.' },
      { n: 13, text: 'Scatter over the sliced spring onion greens and serve immediately, with the beansprouts, coriander, basil, lime wedges and chilli on a plate for each person to add themselves.', minutes: 3 },
    ],
    failures: [
      { symptom: 'Broth is cloudy and grey rather than clear amber.', cause: 'The parboil was skipped or the broth was allowed to boil. Parboil and rinse the bones and meat, then hold the pot at the gentlest simmer for the whole 3 hours.' },
      { symptom: 'Broth tastes like plain beef stock with no perfume.', cause: 'The onion and ginger were not charred hard enough. They need actual blackening in patches, not colour.' },
      { symptom: 'Noodles are mushy and broken.', cause: 'They were boiled instead of blanched. Soak in warm water, then no more than 40 seconds in boiling water, and drain immediately.' },
      { symptom: 'Raw sirloin stays red and chewy in the bowl.', cause: 'The broth was not boiling when poured, or the slices were too thick. Roll-boil the broth and freeze the beef 20 minutes before slicing.' },
      { symptom: 'The bowl tastes bland once assembled even though the broth tasted right.', cause: 'The noodles diluted it. Season the broth to just past what tastes correct on its own, and let people add fish sauce and lime at the table.' },
    ],
    variants: [
      {
        id: 'pho_cheat_30',
        label: '30-minute cheat pho',
        swaps: [
          { from: 'beef_brisket', to: null },
          { from: 'stock_cube_beef', to: 'stock_cube_beef', grams: 20 },
          { from: 'beef_sirloin', to: 'beef_sirloin', grams: 300 },
          { from: 'water', to: 'water', grams: 1500 },
        ],
        methodDeltas: [
          { step: 1, change: 'Skip the parboil entirely; with no brisket there is nothing to clarify.' },
          { step: 3, change: 'Still char the onion and ginger. This is the one step you cannot skip, and it takes 8 minutes. Cheat pho made without charring tastes like beef Cup-a-Soup.' },
          { step: 6, change: 'Replace the 3-hour simmer with 20 minutes: dissolve the stock cubes in 1.5 litres of water, add the charred aromatics and toasted spices, and simmer gently.' },
          { step: 9, change: 'Stock-cube broth is already salty, so hold back the 8 g of salt and season with fish sauce and sugar only, tasting as you go.' },
          { step: 11, change: 'Double the raw sirloin to make up for the missing brisket, and slice it even thinner since it is now the only beef in the bowl.' },
        ],
        tags: ['halal', 'dairy_free', 'gluten_free', 'nut_free'],
        note: 'Thinner body and less depth, but a real weeknight bowl in 30 minutes.',
      },
      {
        id: 'pho_ga_chicken',
        label: 'Chicken pho',
        swaps: [
          { from: 'beef_brisket', to: 'chicken_thigh', grams: 450 },
          { from: 'beef_sirloin', to: null },
          { from: 'stock_cube_beef', to: 'stock_cube_chicken', grams: 10 },
          { from: 'star_anise', to: 'star_anise', grams: 2 },
        ],
        methodDeltas: [
          { step: 1, change: 'Parboil the chicken for 3 minutes only, not 5. Longer and the thigh meat starts cooking through before the broth has begun. Poach the chicken to 75 C at the thickest point, not just until it turns opaque.' },
          { step: 4, change: 'Halve the star anise and drop the cloves to two. Chicken broth is far more delicate than beef and the same spice load simply buries it.' },
          { step: 6, change: 'Simmer for 60 minutes, not 3 hours. Chicken broth turns dull and slightly bitter past about 90 minutes.' },
          { step: 11, change: 'There is no raw beef here. Lift the poached thighs out at 40 minutes, cool them, and hand-shred rather than slice.' },
          { step: 12, change: 'The broth still needs to be boiling when poured, but now it is only reheating cooked chicken rather than cooking anything.' },
        ],
        tags: ['halal', 'dairy_free', 'gluten_free', 'nut_free'],
      },
      {
        id: 'pho_vegan',
        label: 'Vegan pho',
        swaps: [
          { from: 'beef_brisket', to: 'tofu_firm', grams: 300 },
          { from: 'beef_sirloin', to: 'mushroom', grams: 200 },
          { from: 'fish_sauce', to: 'soy_sauce', grams: 45 },
          { from: 'stock_cube_beef', to: 'stock_cube_veg', grams: 20 },
        ],
        methodDeltas: [
          { step: 1, change: 'No parboil. Instead press the tofu under a weight for 20 minutes and pour off the water.' },
          { step: 3, change: 'Char the mushrooms alongside the onion and ginger until they are properly blackened at the edges. They are now the main source of savoury depth and need real colour.' },
          { step: 6, change: 'Simmer the charred aromatics, mushrooms and spices in 1.8 litres of water with the vegetable stock cubes for 45 minutes. There is no collagen here, so a longer simmer adds nothing except evaporation.' },
          { step: 9, change: 'Soy sauce is saltier and less funky than fish sauce. Add it in stages and add an extra teaspoon of sugar, then finish with a generous squeeze of lime for the sourness fish sauce would have carried.' },
          { step: 11, change: 'Slice the pressed tofu into 1 cm slabs and pan-fry in a dry non-stick pan for 3 minutes a side until golden. Untouched tofu in broth is texturally flat.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
      },
    ],
    restaurantGBP: 12.5,
    tags: ['halal', 'dairy_free', 'gluten_free', 'nut_free'],
  },

  // ============================================================
  // 6. Falafel bowl — Levant
  // ============================================================
  {
    id: 'falafel_bowl',
    name: 'Falafel Bowl with Tahini and Flatbread',
    localName: 'فلافل',
    cuisine: 'Levantine',
    country: 'LB',
    blurb: 'Dried chickpeas soaked overnight and blitzed raw with herbs, fried until dark and crisp, served with tahini sauce, chopped salad and warm flatbread.',
    servings: 2,
    activeMin: 40,
    totalMin: 780,
    difficulty: 'medium',
    items: [
      { ref: 'chickpeas_dried', grams: 150, note: 'dried, soaked 12 h and drained — never tinned, see step 1' },
      { ref: 'onion', grams: 80, note: 'roughly chopped' },
      { ref: 'garlic', grams: 16, note: '3 cloves for the mix, 1 crushed into the tahini sauce' },
      { ref: 'parsley_fresh', grams: 25, note: 'leaves and stems, well dried' },
      { ref: 'coriander_fresh', grams: 20, note: 'leaves and stems, well dried' },
      { ref: 'cumin_ground', grams: 6, note: '3 tsp' },
      { ref: 'coriander_ground', grams: 4 },
      { ref: 'salt', grams: 7, note: '5 g in the mix, 2 g for the salad' },
      { ref: 'black_pepper', grams: 2 },
      { ref: 'plain_flour', grams: 20, note: 'binder, added just before frying' },
      { ref: 'sesame_seeds', grams: 10, note: 'pressed onto the outside', optional: true },
      { ref: 'vegetable_oil', grams: 500, note: 'for deep frying; only about 40 g is absorbed', absorption: 0.08 },
      { ref: 'tahini', grams: 60 },
      { ref: 'lemon', grams: 50, note: 'juice, for the sauce and the salad' },
      { ref: 'water', grams: 60, note: 'iced, for loosening the tahini' },
      { ref: 'cucumber', grams: 120, note: 'diced 5 mm' },
      { ref: 'tomato_fresh', grams: 150, note: 'deseeded and diced 5 mm' },
      { ref: 'red_onion', grams: 50, note: 'finely diced' },
      { ref: 'flatbread', grams: 160, note: '2 large, warmed' },
      { ref: 'olive_oil', grams: 15, note: 'for the salad' },
      { ref: 'olives_black', grams: 30, note: 'pitted', optional: true },
      { ref: 'harissa', grams: 20, note: 'to serve', optional: true },
    ],
    method: [
      { n: 1, text: 'The night before, cover 250 g of DRIED chickpeas with three times their volume of cold water and leave them for at least 12 hours. They will roughly double in weight.', minutes: 720, tip: 'Tinned chickpeas will not work here and this is not a matter of preference. They are already cooked through and waterlogged, so they puree to a wet hummus that disintegrates the moment it touches hot oil. If tinned is all you have, use the baked variant below.' },
      { n: 2, text: 'Drain the soaked chickpeas thoroughly and spread them on a clean tea towel for 10 minutes to dry the surface. Wash and dry the herbs properly too. Every gram of surface water works against you: a wet mix will not hold its shape, and wet anything spits violently in hot oil.', minutes: 12 },
      { n: 3, text: 'Put the drained raw chickpeas, onion, 3 cloves of garlic, parsley, coriander, cumin, ground coriander, 5 g of salt and the black pepper into a food processor. Pulse in short bursts, scraping down twice.', minutes: 6, tip: 'Pulse, do not blend. You are aiming for the texture of coarse wet sand or couscous, with visible flecks. A smooth paste behaves like hummus and falls apart.' },
      { n: 4, text: 'Tip the mix into a bowl, cover and chill it in the fridge for 30 minutes. This firms the starch and is the cheapest insurance against the falafel breaking up in the oil, so do not skip it because you are hungry.', minutes: 30 },
      { n: 5, text: 'Make the tahini sauce. Whisk the tahini with the crushed garlic clove and 30 ml of lemon juice; it will seize into a stiff paste and look ruined. Keep whisking and add iced water a tablespoon at a time until it loosens into a pourable cream. The seizing is normal and expected; cold water and patience bring it back, whereas adding oil or more tahini will not.', minutes: 6 },
      { n: 6, text: 'Make the salad. Toss the cucumber, tomato, red onion, olive oil, the remaining lemon juice and 2 g of salt. Leave it at room temperature.', minutes: 8 },
      { n: 7, text: 'Pour the oil into a deep heavy pan to a depth of about 4 cm and heat it to 170 to 175 C. If you have no thermometer, a cube of bread should brown in 45 seconds.', minutes: 8, tip: 'Below 165 C the falafel absorb oil and go greasy; above 185 C they darken outside while the middle stays raw and pasty. This 10-degree window matters more than anything else in the recipe.' },
      { n: 8, text: 'Sprinkle the flour over the chilled mix and work it in with your hands. Squeeze a walnut-sized amount tightly in your fist; if it holds together when you open your hand, it is ready. If it crumbles apart, add flour 1 tsp at a time; if it feels sticky and wet, chill it another 15 minutes rather than adding more flour, which makes them dense.', minutes: 4 },
      { n: 9, text: 'Shape one test falafel, roughly 35 g, into a slightly flattened ball, press one face into the sesame seeds if using, and fry it alone for 3 minutes.', minutes: 4, tip: 'Always fry one first. If it disintegrates you have lost one falafel instead of twelve, and you know to add more flour and chill for longer.' },
      { n: 10, text: 'If the test holds, shape the rest and fry in batches of four or five for 3 to 4 minutes, turning once, until they are a deep chestnut brown and float. Take them further than instinct says: pale golden falafel are undercooked in the middle.', minutes: 12 },
      { n: 11, text: 'Lift them out with a slotted spoon onto a wire rack, not kitchen paper. Salt them lightly while the surface is still hot.', minutes: 3, tip: 'On kitchen paper the trapped steam softens the base within two minutes. A rack keeps them crisp all round.' },
      { n: 12, text: 'Warm the flatbreads for 30 seconds a side in a dry pan or 3 minutes in a 180 C oven wrapped in foil.', minutes: 4 },
      { n: 13, text: 'Build the bowls: salad on one side, falafel on the other, tahini sauce poured over, olives and harissa alongside, flatbread torn and tucked in. Eat immediately: falafel are at their best within 10 minutes of leaving the oil, and while they are still good later, nothing recovers that shattering crust.', minutes: 4 },
    ],
    failures: [
      { symptom: 'Falafel disintegrate into the oil and you are left with brown crumbs.', cause: 'Tinned or cooked chickpeas were used, the mix was blended too smooth, or it was not chilled. Use soaked raw dried chickpeas, pulse to coarse sand, and chill 30 minutes before frying.' },
      { symptom: 'Dark outside, raw and pasty in the middle.', cause: 'Oil was too hot. Hold it at 170 to 175 C and make the balls no larger than 35 g.' },
      { symptom: 'Heavy and greasy rather than crisp.', cause: 'Oil was too cool, or the pan was overloaded so the temperature crashed. Fry four or five at a time and let the oil recover between batches.' },
      { symptom: 'Tahini sauce seized into a thick grey paste.', cause: 'That is what tahini does when acid hits it. Keep whisking and add iced water a tablespoon at a time until it turns pourable and pale.' },
      { symptom: 'Falafel taste dusty and bland.', cause: 'Not enough salt or herbs, and no acid on the plate. Use the full 25 g parsley and 20 g coriander, and make sure lemon reaches the bowl.' },
    ],
    variants: [
      {
        id: 'falafel_baked_tinned',
        label: 'Baked, using tinned chickpeas',
        swaps: [
          { from: 'vegetable_oil', to: 'olive_oil', grams: 30 },
          { from: 'plain_flour', to: 'plain_flour', grams: 45 },
        ],
        methodDeltas: [
          { step: 1, change: 'No soaking. Drain 2 tins of chickpeas, rinse and pat dry. Accept up front that these will be soft baked patties, not shattering-crisp falafel, because cooked chickpeas cannot produce that texture.' },
          { step: 2, change: 'Spread the tinned chickpeas on a tray and dry them in a 180 C oven for 15 minutes first. This drives off the tinning liquid that would otherwise turn the mix to slurry.' },
          { step: 3, change: 'Pulse even more sparingly. Cooked chickpeas break down far faster than raw ones and go to puree in seconds.' },
          { step: 8, change: 'You will need roughly double the flour, about 45 g, to get a mix that holds a shape at all.' },
          { step: 10, change: 'Do not deep fry these, they will fall apart. Shape into flattened patties, brush both sides with olive oil and bake at 200 C for 25 minutes, turning once at 15 minutes.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
        note: 'The honest fallback when you have not planned 12 hours ahead.',
      },
      {
        id: 'falafel_halloumi',
        label: 'Higher-protein, with halloumi',
        swaps: [{ from: 'olives_black', to: 'halloumi', grams: 120 }],
        methodDeltas: [
          { step: 6, change: 'Slice the halloumi 1 cm thick and dry-fry it in a non-stick pan over medium-high heat for 2 minutes a side, with no oil. It releases enough of its own fat.' },
          { step: 13, change: 'Halloumi must go into the bowl straight from the pan. Left more than 5 minutes it stiffens into rubber, so cook it last, after the falafel are out of the oil.' },
        ],
        tags: ['vegetarian', 'halal', 'nut_free'],
      },
      {
        id: 'falafel_gf_rice',
        label: 'Gluten-free, over rice',
        swaps: [
          { from: 'flatbread', to: 'basmati_rice', grams: 160 },
          { from: 'plain_flour', to: 'cornflour', grams: 25 },
        ],
        methodDeltas: [
          { step: 4, change: 'Cornflour binds less securely than wheat flour. Extend the chill to a full 60 minutes and start the rice during it.' },
          { step: 8, change: 'Work the cornflour in gradually and repeat the fist test twice. Cornflour also makes the crust slightly more brittle, so handle the shaped balls gently on the way into the oil.' },
          { step: 12, change: 'In place of warming flatbread, cook 160 g rinsed basmati in 320 ml water: boil, cover, lowest heat 10 minutes, then 10 minutes standing off the heat.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'gluten_free', 'dairy_free', 'nut_free'],
      },
    ],
    restaurantGBP: 9.95,
    tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
  },

  // ============================================================
  // 7. Poached eggs on sourdough with avocado — brunch
  // ============================================================
  {
    id: 'poached_eggs_avocado',
    name: 'Poached Eggs on Sourdough with Avocado',
    cuisine: 'Global brunch',
    country: 'GB',
    blurb: 'Two eggs per person poached in barely-moving vinegared water, set on toasted sourdough spread with lemon-crushed avocado.',
    servings: 2,
    activeMin: 15,
    totalMin: 22,
    difficulty: 'easy-medium',
    items: [
      { ref: 'egg', grams: 220, note: '4 large, as fresh as you can get' },
      { ref: 'bread_sourdough', grams: 160, note: '4 slices, cut 2 cm thick' },
      { ref: 'avocado', grams: 200, note: '1 large ripe, flesh only' },
      { ref: 'lemon', grams: 25, note: 'juice, into the avocado' },
      { ref: 'vinegar_white', grams: 15, note: '1 tbsp, into the poaching water' },
      { ref: 'salt', grams: 4 },
      { ref: 'black_pepper', grams: 1, note: 'coarsely ground, at the table' },
      { ref: 'olive_oil', grams: 10, note: 'drizzled over at the end' },
      { ref: 'butter', grams: 15, note: 'on the toast', optional: true },
      { ref: 'kashmiri_chilli', grams: 1, note: 'a pinch, for colour and mild heat', optional: true },
      { ref: 'spinach_fresh', grams: 60, note: 'wilted, under the eggs', optional: true },
      { ref: 'feta', grams: 50, note: 'crumbled over', optional: true },
      { ref: 'tomato_fresh', grams: 100, note: 'halved and blistered in the pan', optional: true },
    ],
    method: [
      { n: 1, text: 'Test your eggs before you commit. Crack one into a small bowl: if the white sits in a tight raised mound around the yolk, it is fresh enough to poach well. If it spreads thin and watery across the bowl, it is old.', minutes: 2, tip: 'Egg freshness is the single biggest factor in poaching, ahead of vinegar, vortexes and every other trick. Old eggs have thin whites that shred into the water no matter what you do.' },
      { n: 2, text: 'If the whites are loose, tip each egg into a fine sieve over a bowl for 20 seconds and let the watery outer white drain away. Then slide what is left into a small bowl or cup.', minutes: 3, tip: 'This sieve step does more for a neat poached egg than anything else, and it is what most cafe kitchens actually do.' },
      { n: 3, text: 'Fill a wide saucepan with about 8 cm of water, add the vinegar and 1 g of the salt, and bring it to a boil. Then turn the heat down until the water is barely moving, with just the occasional bubble rising, around 82 to 85 C.', minutes: 6, tip: 'A rolling boil tears poached eggs apart. If the surface is agitating, it is too hot; you want it trembling, not bubbling.' },
      { n: 4, text: 'A word on the tricks: vinegar helps the white set slightly faster at the edges, but it is a small effect and too much makes the egg taste sour. The vortex helps wrap a loose white around itself, but it only works for one egg at a time and it is no substitute for fresh eggs. For four eggs, forget the vortex entirely: sieve the whites, keep the water still, and space the eggs apart.', minutes: 1 },
      { n: 5, text: 'Toast the sourdough while the water comes to temperature, and halve, stone and scoop the avocado into a bowl.', minutes: 4 },
      { n: 6, text: 'Crush the avocado roughly with a fork, leaving it chunky rather than smooth, then mix in the lemon juice and 2 g of salt. The lemon is not only for flavour, the acid slows the browning, so add it as soon as the avocado is open rather than at serving time.', minutes: 3 },
      { n: 7, text: 'Get the lip of the cup right down to the surface of the water and let each egg slide in gently, spacing them well apart around the pan. Dropping an egg from height breaks the yolk and disperses the white.', minutes: 2 },
      { n: 8, text: 'Poach for 3 minutes for a fully runny yolk with set white, or 4 minutes for jammy. Do not stir, do not poke.', minutes: 4, tip: 'Time from the moment the last egg goes in, not the first. A minute of drift is the difference between runny and hard.' },
      { n: 9, text: 'Lift each egg out with a slotted spoon and rest it briefly on a folded piece of kitchen paper or a clean tea towel to drain. Five seconds is enough; skip it and the poaching water soaks straight into your toast.', minutes: 2 },
      { n: 10, text: 'Trim off any ragged wisps of white with a knife or your fingers if you want the cafe look. This is cosmetic only.', minutes: 1 },
      { n: 11, text: 'Butter the toast if using, spread the crushed avocado thickly, and set two eggs on each portion.', minutes: 2 },
      { n: 12, text: 'Drizzle over the olive oil, season with the remaining salt, plenty of coarse black pepper and a pinch of kashmiri chilli, then scatter the feta over. Serve immediately.', minutes: 2, tip: 'Salt the egg only at the table. Salting a poached egg while it sits draws out moisture and pits the surface.' },
    ],
    failures: [
      { symptom: 'The white shreds into wispy clouds and the pan looks like egg-drop soup.', cause: 'The eggs were old or the water was boiling. Sieve off the watery white first and keep the water at a bare tremble, around 82 C.' },
      { symptom: 'Yolk is set solid instead of runny.', cause: 'Overcooked, usually because timing started when the first egg went in. Three minutes from the last egg, then straight out.' },
      { symptom: 'Toast goes soggy within a minute.', cause: 'Water was carried over on the egg. Drain each egg on kitchen paper for a few seconds, and toast the bread properly dark so it has structure.' },
      { symptom: 'Avocado has gone brown and grey by the time you plate up.', cause: 'It was crushed without acid, or too far ahead. Add lemon the moment it is opened and make it while the water heats, not before.' },
      { symptom: 'Everything tastes faintly of vinegar.', cause: 'Too much in the water. One tablespoon in 8 cm of water is plenty; the effect is marginal anyway.' },
    ],
    variants: [
      {
        id: 'eggs_salmon',
        label: 'With salmon, higher protein',
        swaps: [
          { from: 'feta', to: 'salmon', grams: 100 },
          { from: 'butter', to: null },
        ],
        methodDeltas: [
          { step: 11, change: 'Cook the salmon: 3 to 4 minutes a side in a dry hot pan, skin down first, until it flakes and the thickest part reaches 63 C. Flake it over the avocado and set the eggs on top. This was written for cold-smoked salmon, but the salmon in the shopping list is a RAW fillet — do not serve it raw. Home-cured or raw fish needs commercial freezing first.' },
          { step: 12, change: 'Cut the added salt in half. Smoked salmon carries a lot of its own, and the dish tips over easily.' },
        ],
        tags: ['dairy_free', 'nut_free'],
      },
      {
        id: 'eggs_vegan_tofu',
        label: 'Vegan tofu scramble version',
        swaps: [
          { from: 'egg', to: 'tofu_firm', grams: 250 },
          { from: 'butter', to: 'olive_oil', grams: 15 },
          { from: 'feta', to: null },
          { from: 'vinegar_white', to: 'turmeric', grams: 1 },
        ],
        methodDeltas: [
          { step: 1, change: 'No poaching at all. Press the tofu under a weighted plate for 20 minutes and pour off the water; unpressed tofu steams in the pan instead of frying.' },
          { step: 3, change: 'Skip the pan of water entirely. Heat the olive oil in a frying pan over medium-high instead.' },
          { step: 8, change: 'Crumble the pressed tofu into the hot pan in irregular pieces, add the turmeric, and fry for 6 to 7 minutes without stirring constantly so some faces catch and brown.' },
          { step: 12, change: 'Season only after cooking. Salt added to tofu at the start pulls water out and you end up boiling it in its own liquid.' },
        ],
        tags: ['vegan', 'vegetarian', 'halal', 'kosher', 'dairy_free', 'nut_free'],
      },
      {
        id: 'eggs_sweet_potato',
        label: 'Lower carb, on roasted sweet potato',
        swaps: [
          { from: 'bread_sourdough', to: 'sweet_potato', grams: 350 },
          { from: 'olive_oil', to: 'olive_oil', grams: 20 },
        ],
        methodDeltas: [
          { step: 1, change: 'Start here, not with the eggs. Cut the sweet potato into 1.5 cm rounds, toss in half the olive oil and salt, and roast at 200 C for 25 minutes, turning once. This takes longer than every other step combined.' },
          { step: 5, change: 'Put the poaching water on only when the sweet potato has 10 minutes left, so everything lands together.' },
          { step: 11, change: 'Overlap the roasted rounds into two beds on the plates and spread the avocado over them. They are less absorbent than toast, so drain the eggs just as carefully or the plate will pool.' },
        ],
        tags: ['vegetarian', 'halal', 'kosher', 'gluten_free', 'nut_free'],
      },
    ],
    restaurantGBP: 9.5,
    tags: ['vegetarian', 'halal', 'kosher', 'nut_free'],
  },
];
