/* Ingredient → Open Food Facts category tag, plus the weight of one "unit" for
   things the recipes count rather than weigh (1 egg, 1 lime). The tags are the
   lookup key for both nutrition (Open Food Facts) and price (Open Prices).
   Unit weights are stated assumptions, not scraped — flagged as such in the app. */
export const MAP = {
  'Rice noodles': { off: 'en:rice-noodles' },
  'Rice noodles, flat 5 mm': { off: 'en:rice-noodles' },
  'Tamarind paste': { off: 'en:tamarind' },
  'Fish sauce': { off: 'en:fish-sauces' },
  'Brown sugar': { off: 'en:brown-sugars' },
  'Raw prawns, peeled': { off: 'en:prawns' },
  'Firm tofu': { off: 'en:tofu' },
  'Eggs': { off: 'en:chicken-eggs', unit: 58 },
  'Garlic': { off: 'en:garlic', unit: 5 },
  'Garlic powder': { off: 'en:garlic-powder' },
  'Vegetable oil': { off: 'en:vegetable-oils' },
  'Olive oil': { off: 'en:olive-oils' },
  'Spring onions': { off: 'en:spring-onion' },
  'Beansprouts': { off: 'en:bean-sprouts' },
  'Roasted peanuts': { off: 'en:roasted-peanuts' },
  'Lime': { off: 'en:limes', unit: 67 },
  'Limes': { off: 'en:limes', unit: 67 },
  'Chilli powder': { off: 'en:chili-powder' },
  'Fresh coriander': { off: 'en:coriander' },
  'Chicken wings': { off: 'en:chicken-wings' },
  'Chicken breast': { off: 'en:chicken-breasts' },
  'Chicken thighs': { off: 'en:chicken-thighs' },
  'Mango, ripe or frozen': { off: 'en:mangoes' },
  'Habanero chilli': { off: 'en:chili-peppers', unit: 9 },
  'Scotch bonnet': { off: 'en:chili-peppers', unit: 9 },
  'Honey': { off: 'en:honeys' },
  'Rice vinegar': { off: 'en:rice-vinegars' },
  'Cornflour': { off: 'en:corn-starches' },
  'Baking powder': { off: 'en:baking-powders' },
  'Salt': { off: 'en:salts' },
  'Soured cream, to dip': { off: 'en:sour-creams' },
  'Long grain rice': { off: 'en:long-grain-rices' },
  'Basmati rice': { off: 'en:basmati-rice' },
  'Soy sauce': { off: 'en:soy-sauces' },
  'Fresh ginger': { off: 'en:ginger' },
  'Ginger': { off: 'en:ginger' },
  'Carrot': { off: 'en:carrots', unit: 70 },
  'Carrots': { off: 'en:carrots', unit: 70 },
  'Tenderstem broccoli': { off: 'en:broccoli' },
  'Red pepper': { off: 'en:red-bell-peppers', unit: 150 },
  'Red peppers': { off: 'en:red-bell-peppers', unit: 150 },
  'Cheddar': { off: 'en:cheddar' },
  'Mature cheddar': { off: 'en:cheddar' },
  'Butter': { off: 'en:butters' },
  'Chives or parsley': { off: 'en:parsley' },
  'Bread': { off: 'en:breads' },
  'Sweet potato': { off: 'en:sweet-potatoes', unit: 130 },
  'Chickpeas, tinned': { off: 'en:canned-chickpeas' },
  'Coconut milk': { off: 'en:coconut-milks' },
  'Curry powder': { off: 'en:curry-powder' },
  'Turmeric': { off: 'en:turmeric' },
  'Ground cumin': { off: 'en:cumin' },
  'Cumin': { off: 'en:cumin' },
  'Cumin seeds': { off: 'en:cumin' },
  'Spinach': { off: 'en:spinachs' },
  'Onion': { off: 'en:onions', unit: 110 },
  'Onions': { off: 'en:onions', unit: 110 },
  'Red onion': { off: 'en:red-onions', unit: 110 },
  'Tinned tomatoes': { off: 'en:canned-tomatoes' },
  'Chopped tomatoes': { off: 'en:canned-tomatoes' },
  'Tomatoes': { off: 'en:tomatoes', unit: 120 },
  'Tomato puree': { off: 'en:tomato-purees' },
  'Pasta': { off: 'en:pastas' },
  'Spaghetti': { off: 'en:spaghetti' },
  'Tuna in spring water': { off: 'en:canned-tunas' },
  'Sweetcorn': { off: 'en:canned-sweetcorn' },
  'Stock cube': { off: 'en:stock-cubes', unit: 10 },
  'Feta': { off: 'en:feta' },
  'Smoked paprika': { off: 'en:paprika' },
  'Corn tortillas': { off: 'en:tortillas', unit: 30 },
  'Avocado': { off: 'en:avocados', unit: 200 },
  'Dried oregano': { off: 'en:oregano' },
  'Beef bones': { off: 'en:beef' },
  'Beef brisket': { off: 'en:beef' },
  'Star anise': { off: 'en:star-anise' },
  'Cinnamon stick': { off: 'en:cinnamon', unit: 2 },
  'Cloves': { off: 'en:cloves' },
  'Black peppercorns': { off: 'en:black-pepper' },
  'Thai basil': { off: 'en:basil' },
  'Celery sticks': { off: 'en:celery', unit: 40 },
  'Red lentils': { off: 'en:red-lentils' },
  'Ghee': { off: 'en:ghee' },
  'Garam masala': { off: 'en:garam-masala' },
  'Kashmiri chilli': { off: 'en:chili-powder' },
  'Dried fenugreek leaf': { off: 'en:fenugreek' },
  'Dried red chillies': { off: 'en:dried-chili-peppers' },
  'Dried thyme': { off: 'en:thyme' },
  'Bay leaves': { off: 'en:bay-leaf' },
  'Double cream': { off: 'en:creams' },
  'Yoghurt': { off: 'en:yogurts' },
  'Guanciale': { off: 'en:pork-cheek' },
  'Pecorino Romano': { off: 'en:pecorino-romano' },
  'Flatbread': { off: 'en:flatbreads' },
};
