// Turns the reviewed cut-outs into a bundled module.
//
// Photographs and drawn layers coexist on the same plate: an ingredient uses its
// photograph when there is one and its vector form when there is not. That is
// the only arrangement that gives real imagery AND keeps the dish pullable
// apart — a photograph of a finished plate cannot have its pasta removed,
// but a plate composed from one photograph per ingredient can.
//
// Attribution travels with the image. Anything from a CC BY or CC BY-SA source
// carries a credit obligation, and share-alike passes to the cut-out derived
// from it, so the credit list is generated from the manifest rather than
// maintained by hand — a hand-maintained credit list is one that goes stale.
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'cutouts';
const mpath = join(DIR, 'manifest.json');
if (!existsSync(mpath)) { writeFileSync('lib/photo-data.ts', 'export const PHOTOS: Record<string,string> = {};\nexport const PHOTO_CREDITS: {ref:string;title:string;licence:string;author:string;page:string}[] = [];\n'); process.exit(0); }

const man = JSON.parse(readFileSync(mpath, 'utf8'));
const photos = {};
const credits = [];
let bytes = 0;

for (const [ref, m] of Object.entries(man)) {
  const f = join(DIR, m.file);
  if (!existsSync(f)) continue;
  const b = readFileSync(f);
  bytes += b.length;
  photos[ref] = `data:image/webp;base64,${b.toString('base64')}`;
  if (m.needs_credit) {
    credits.push({
      ref,
      title: String(m.title || '').replace(/^File:/, ''),
      licence: m.licence,
      author: String(m.author || '').replace(/<[^>]*>/g, '').trim().slice(0, 80),
      page: m.page || '',
    });
  }
}

const out =
`// GENERATED by scripts/build-photos.mjs — do not edit.
// ${Object.keys(photos).length} cut-outs, ${(bytes / 1024).toFixed(0)} KB of image data.
export const PHOTOS: Record<string, string> = ${JSON.stringify(photos)};
export interface PhotoCredit { ref: string; title: string; licence: string; author: string; page: string }
export const PHOTO_CREDITS: PhotoCredit[] = ${JSON.stringify(credits, null, 1)};
export const hasPhoto = (ref: string) => !!PHOTOS[ref];
`;
writeFileSync('lib/photo-data.ts', out);
console.log(`photos: ${Object.keys(photos).length} bundled, ${(bytes / 1024).toFixed(0)} KB raw, ${credits.length} need credit`);
