// Bundles dish photographs as FILES, not base64.
//
// Inlining them took the single HTML file from 425 KB to 2.7 MB, which is what
// broke it. As files they are cached by the browser and the service worker,
// the page paints immediately, and a deploy is a normal static upload.
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
const D='dishpix', mp=join(D,'manifest.json');
mkdirSync('public/pix', { recursive: true });
if(!existsSync(mp)){ writeFileSync('lib/dish-photos.ts','export const DISH_PHOTOS: Record<string,string> = {};\nexport const DISH_CREDITS: {id:string;article:string;licence:string;author:string;page:string}[] = [];\nexport const dishPhoto = (id: string): string | null => null;\n'); process.exit(0); }
// Where the same files also live, publicly, so a lone copy of the HTML with no
// pix/ folder beside it still shows photographs. Pointing back at Wikipedia
// would work too but hands over the full-size original — several megabytes for
// a thumbnail. These are the exact files the build produced.
const CDN = 'https://iokudugeqfwjtifomyis.supabase.co/storage/v1/object/public/app/pix';
const man=JSON.parse(readFileSync(mp,'utf8'));
const pics={}, remote={}, credits=[]; let bytes=0;
for(const [id,m] of Object.entries(man)){
  const f=join(D,m.img); if(!existsSync(f)) continue;
  copyFileSync(f, join('public/pix', m.img));
  bytes+=readFileSync(f).length;
  pics[id]='pix/'+m.img;
  remote[id]=`${CDN}/${m.img}`;
  credits.push({id, article:m.article, licence:m.licence, author:m.author||'unknown', page:m.page||''});
}
writeFileSync('lib/dish-photos.ts',
`// GENERATED by scripts/build-dishpix.mjs — do not edit.
// ${Object.keys(pics).length} photographs served as files (${(bytes/1024).toFixed(0)} KB on disk).
export const DISH_PHOTOS: Record<string, string> = ${JSON.stringify(pics)};
export const DISH_REMOTE: Record<string, string> = ${JSON.stringify(remote)};
export interface DishCredit { id: string; article: string; licence: string; author: string; page: string }
export const DISH_CREDITS: DishCredit[] = ${JSON.stringify(credits,null,1)};
export const dishPhoto = (id: string): string | null => DISH_PHOTOS[id] ?? null;
`);
console.log(`dish photos: ${Object.keys(pics).length} as files, ${(bytes/1024).toFixed(0)} KB`);
