// Ingredient cut-outs as files, for the same reason as the dish photographs.
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
const D='ingpix', mp=join(D,'manifest.json');
mkdirSync('public/pix', { recursive: true });
if(!existsSync(mp)){ writeFileSync('lib/ing-photos.ts','export const ING_PHOTOS: Record<string,string> = {};\nexport const ING_CREDITS: {ref:string;article:string;licence:string;author:string;page:string}[] = [];\nexport const ingPhoto = (r: string): string | null => null;\n'); process.exit(0); }
// The cut-out manifest never recorded a source URL, so until now these had no
// fallback at all: open the HTML on its own and every ingredient was a broken
// frame. Same public copy as the dish photographs.
const CDN = 'https://iokudugeqfwjtifomyis.supabase.co/storage/v1/object/public/app/pix';
const man=JSON.parse(readFileSync(mp,'utf8'));
const pics={}, remote={}, credits=[]; let bytes=0;
for(const [ref,m] of Object.entries(man)){
  const f=join(D,m.img); if(!existsSync(f)) continue;
  copyFileSync(f, join('public/pix','ing-'+m.img));
  bytes+=readFileSync(f).length;
  pics[ref]='pix/ing-'+m.img;
  remote[ref]=`${CDN}/ing-${m.img}`;
  credits.push({ref, article:m.article, licence:m.licence, author:m.author||'unknown', page:m.page||''});
}
writeFileSync('lib/ing-photos.ts',
`// GENERATED by scripts/build-ingpix.mjs — do not edit.
// ${Object.keys(pics).length} cut-outs served as files (${(bytes/1024).toFixed(0)} KB on disk).
export const ING_PHOTOS: Record<string, string> = ${JSON.stringify(pics)};
export const ING_REMOTE: Record<string, string> = ${JSON.stringify(remote)};
export interface IngCredit { ref: string; article: string; licence: string; author: string; page: string }
export const ING_CREDITS: IngCredit[] = ${JSON.stringify(credits,null,1)};
export const ingPhoto = (r: string): string | null => ING_PHOTOS[r] ?? null;
`);
console.log(`ingredient cut-outs: ${Object.keys(pics).length} as files, ${(bytes/1024).toFixed(0)} KB`);
